### ISSUE TITLE
Displaying Shap Plots in Azure Databricks

### ISSUE THREAD

**Issue by jstremme** [shap/shap#101]
Love shap.

Is there a way to save shap plots to html? This is the only way to display plots in Azure Databricks without accessing the figure object itself in order to call the Databricks' display function.

Here's an example of saving to HTML with Bokeh, then using the Databricks displayHTML function to show the plot in the Databricks notebook:

from bokeh.plotting import figure
from bokeh.embed import components, notebook_div, file_html
from bokeh.resources import CDN

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

# create an html document that embeds the Bokeh plot
html = file_html(p, CDN, "my plot1")

# display this html
displayHTML(html)

https://docs.databricks.com/user-guide/visualizations/bokeh.html

Thanks for any help you can provide.  You may have a function for saving to html, but I can't seem to find it.

Best,

Joel

**Comment by slundberg** [comment]
Glad you are finding it useful. Which plot function do you have in mind? force_plot produces html and dumps it to the display using jupyter notebook utils, while the other methods use matplotlib. Currently we use `IPython.core.display(IPython.core.HTML("XXXXX"))` for the force_plot code. Perhaps just using displayHTML would work here. 

For force plot all the stuff happens in https://github.com/interpretable-ml/iml/blob/master/iml/visualizers.py

Note that initjs() dumps html as well as the call to force_plot

**Comment by jstremme** [comment]
Thanks for the help.  I'm now able to use the display function to show all of the matplot figures.  Sounds like I'll need to monkey a bit with the HTML display source code in order to get force_plot to show in the Databricks notebooks.

**Comment by slundberg** [comment]
Great. If you get it working let me know, perhaps we can make it easier for
others.

**Comment by jvanlier** [comment]
Found a workaround. You have to include the JavaScript everytime you create a plot, since each cell output of a Databricks notebook is an iframe.
For example:

```
html = shap.force_plot(shap_values_test[i, :], ex)
html_js = '<script type="text/javascript" src="https://jvlanalytics.nl/assets/iml-bundle.js" charset="utf-8"></script>'
displayHTML(html_js + html.data)
```

Not pretty but it works!

**Comment by jstremme** [comment]
jvanlier, what's the .js file in src?  I tried using the same file, but I'm getting:

Visualization omitted, Javascript library not loaded!
Have you run `initjs()` in this notebook? If this notebook was from another user you must also trust this notebook (File -> Trust notebook). If you are viewing this notebook on github the Javascript has been stripped for security.

I have run shap.initjs() already, so I'm wondering if it has something to do with accessing the .js file you linked?

Thanks for the workaround.  Really appreciate it.

**Comment by jvanlier** [comment]
Hey @jstremme, it's the bundle.js from the `iml` package. Here's the original: https://github.com/interpretable-ml/iml/blob/2769e747a6af032ff91a048ee5d87bd0ca5a3e95/javascript/build/bundle.js

`shap.initjs()` actually calls this bit of code from `iml`:

https://github.com/interpretable-ml/iml/blob/2769e747a6af032ff91a048ee5d87bd0ca5a3e95/iml/visualizers.py#L25-L33

Which doesn't seem to work in Databricks.

I just took the `bundle.js` from latest master in the `iml` repo and uploaded it somewhere public to make it available to Databricks, and then include the Javascript using HTML tags everytime I make one of those shap HTML/JS plots.
 
I only tested this in Chrome though, it might not work in other browsers? Tip: open the Javascript console to debug.

This workaround also might not work if your shap package isn't fully up to date, I suppose the shap/iml version you have installed must match the Javascript version you insert here.

**Comment by jstremme** [comment]
@jvanlier, Thanks for your help on this.  It's funny, the src http isn't accessible through my company network, but I was able to snag a copy of it outside of work.  

Have you or @slundberg had any luck saving html from force plot to a png file?  I'd really like to be able to display these plots in a Dash application: https://plot.ly/products/dash/, and I think the easiest way to do that would be to just serve up a png of a saved force plot.

**Comment by slundberg** [comment]
@jstremme I have only done it by screen grab, which is not very automated.

**Comment by jstremme** [comment]
@slundberg, I suppose since the other plots are matplot objects, you could use plt.savefig on those, but you mentioned that force_plot does not create a matplot object?

Will continue to explore this, as these shap plots would be incredibly useful inside of web applications. My team builds dashboards to help explain ML model predictions to physicians and pop health managers.

**Comment by slundberg** [comment]
That's right, force_plot is a D3.js and React based plot. So if you are building a web app the best approach would be to include the JS code directly. ...it was actually originally built for a web app that was shown to physicians and then taken out of there to be useful for the broader ML community.

**Comment by minglan02** [comment]
@jstremme Have you figured out how to display force_plot chart on dash? I'm also facing same problem and I barely can find the solution.

**Comment by minglan02** [comment]
@slundberg is it possible to export force_plot as svg format? I checked the source code of shap, but it doesn't seem there is internal function to do that. Did I miss something?

**Comment by slundberg** [comment]
@minglan02 there is not a function to do that, partially since the SVG is not generated by python code but by D3 JS code, so it has to be running in a browser. You can check out: https://github.com/slundberg/shap/issues/27#issuecomment-406784617

**Comment by PrashantSaikia** [comment]
Hi Scott. I have a related issue. I'm making a plotly dashboard with your plots. For one, I too am not able to modify the IML visualizations to be displayed on the web. But for now, the problem that has more precedence for me is the `dependence_plot`.

The problem boils down to this - instead of plotting the matplotlib plots, I want to store the matplotlib figure object in a variable, convert that to a plotly figure object, and then plot it. I modified the `shap.dependence_plot` function by doing `return pl.figure()` instead of `pl.show()`, and saved a local copy of the function as `shap_dependence_plot`. This works fine when I use the `dependence_plot` with `shap_values` like so:

```
lis = []
for i in features:
    mpl_fig = shap_dependence_plot(i, shap_values, X)
    plotly_fig = mpl_to_plotly(mpl_fig)
    lis.append(plotly_fig)
lis
```

This prints out a list of the figure objects. But when I use `shap_interaction_values`, this does not work. Instead of storing the matplotlib figure objects in the variable, it proceeds to plot the matplotlib figures, which I think is the root cause of the problem. This is most probably due to the recursion involved when using `shap_interaction_values` as opposed to `shap_values` where there's no recursion involved.

----------

To further illustrate the issue, if you try to `get_axes` of the matplotlib figure objects, it works for `shap_values`:

mpl_fig = shap_dependence_plot(i, shap_values, X)
mpl_fig.get_axes()
>>> [, ] 

but does not work with `shap_interaction_values`:

```
mpl_fig = shap_dependence_plot ( (i, j), shap_interaction_values, X, display_features=X )
mpl_fig.get_axes()
>>>[]
```

As a result, you can't get the axes bounds of the matplotlib figure:

```
x_min, x_max, y_min, y_max = [], [], [], []
for axes_obj in mpl_fig.get_axes():
    bounds = axes_obj.get_position().bounds
    x_min.append(bounds[0])
    x_max.append(bounds[0]+bounds[2])
    y_min.append(bounds[1])
    y_max.append(bounds[1]+bounds[3])
x_min, y_min, x_max, y_max = min(x_min), min(y_min), max(x_max), max(y_max)

>>> ### ValueError: min() arg is an empty sequence
```

So, if you could you please point to how do I get `shap_dependence_plot` to save the matplotlib figure object instead of plotting it when using `shap_interaction_values`, it would be a great help.

**Comment by PrashantSaikia** [comment]
Hi @slundberg. I have a related issue. I'm making a plotly dashboard with your plots. For one, I too am not able to modify the IML visualizations to be displayed on the web. But for now, the problem that has more precedence for me is the `dependence_plot`.

The problem boils down to this - instead of plotting the matplotlib plots, I want to store the matplotlib figure object in a variable, convert that to a plotly figure object, and then plot it on a web page. I modified the `shap.dependence_plot` function by doing `fig = pl.figure()` in the beginning and `return fig` at the end instead of `pl.show()`, and saved a local copy of the function as `shap_dependence_plot`. This works fine when I use `shap_values` like so:

```
lis = []
for i in features:
    mpl_fig = shap_dependence_plot(i, shap_values, X)
    plotly_fig = mpl_to_plotly(mpl_fig)
    lis.append(plotly_fig)
lis
```

This prints out a list of the figure objects. But when I use `shap_interaction_values`, this does not work. Instead of storing the matplotlib figure objects in the variable, it proceeds to plot the matplotlib figures, which I think is the root cause of the problem. I think this might have something to do with the recursion involved when using `shap_interaction_values` as opposed to `shap_values` where there's no recursion involved.

----------

To further illustrate the issue, if you try to `get_axes` of the matplotlib figure objects, it works for `shap_values`:

```
mpl_fig = shap_dependence_plot(i, shap_values, X)
mpl_fig.get_axes()
>>> [, ] 
```

but does not work with `shap_interaction_values`:

```
mpl_fig = shap_dependence_plot ( (i, j), shap_interaction_values, X )
mpl_fig.get_axes()
>>>[]
```

As a result, you can't get the axes bounds of the matplotlib figure:

```
x_min, x_max, y_min, y_max = [], [], [], []
for axes_obj in mpl_fig.get_axes():
    bounds = axes_obj.get_position().bounds
    x_min.append(bounds[0])
    x_max.append(bounds[0]+bounds[2])
    y_min.append(bounds[1])
    y_max.append(bounds[1]+bounds[3])
x_min, y_min, x_max, y_max = min(x_min), min(y_min), max(x_max), max(y_max)

>>> ### ValueError: min() arg is an empty sequence
```

So, if you could you please point to how do I get `shap_dependence_plot` to save the matplotlib figure object instead of plotting it when using `shap_interaction_values`, it would be a great help.

**Comment by slundberg** [comment]
Played around with it a bit but I am not sure the exact cause. Perhaps it is because you need to add another return statement at the following recursive call?https://github.com/slundberg/shap/blob/1330bd979e0fb2e943c44e99231e579c9b4f0999/shap/plots/dependence.py#L82-L85

**Comment by naarkhoo** [comment]
I appreciate to hear how to display force_plot chart on dash ? let's call it a feature request :-)

**Comment by slundberg** [comment]
@naarkhoo I am sure it could be embedded. I am not going to focus on it right now, but feel free to open separate issue and we can tag it "help wanted"
