### ISSUE TITLE
GradientExplainer returns different results

### ISSUE THREAD

**Issue by sakura7621** [shap/shap#1010]
Dear Slundberg,

When using GradientExplainer, I see that each time I run the code, it returns a different SHAP value.

    for i in range(3):
        explainer = shap.GradientExplainer(model, X_train)
        shap_values = explainer.shap_values(X_test, nsamples = len(X_test))
        print(np.sum(shap_values)) ## check by calculating the sum

The output is

> -27.40142326031844
-29.111287849052133
-44.29400186671478

DeepExplainer returns the same result, but why it's not the case for GradientExplainer? 

Besides, I couldn't find the expected values when using GradientExplainer.
Does GradientExplainer have the expected values?

Thanks

**Comment by HughChen** [comment]
GradientExplainer is an implementation of Expected Gradients (introduced in this [paper](https://arxiv.org/abs/1906.10670)) which is an extension of [Integrated Gradients](https://arxiv.org/abs/1703.01365) which aims to approximate Aumann-Shapley values.  My understanding is that GradientExplainer works by integrating the gradients of all interpolations between a the foreground sample (the sample being explained) and a background sample (the sample being compared to).  

However, since this is computationally expensive, it does so by randomly sampling the amount of interpolation and the background sample.  This random sampling means that GradientExplainer is non-deterministic.  If you increase `nsamples` for `explainer.shap_values(*)`, it should converge eventually.

My explanation was a pretty short summary of Expected Gradients.  For a better description, feel free to check out one of our lab member's great [distill article](https://distill.pub/2020/attribution-baselines/).

As a final note, I don't believe the expected values are returned for GradientExplainer.  I think the expected values should be the average over the predictions made.  But as a word of caution, for non-converged GradientExplainer attribution values, it will not satisfy local accuracy (efficiency) where the attribution values should add up to the difference between the prediction and the expected value:
`self.run(self.model_output, self.model_inputs, self.data).mean(0)`

**Comment by LinkToPast1990** [comment]
Hi, @HughChen 

I think GradientExplainer (IG+SHAP) is similar to Deep SHAP (DeepLift+SHAP), right?

In the original nips 2017 paper section 4.2, the authors said that: "Since DeepLIFT is an additive feature attribution method that satisfies **local accuracy** and **missingness**, we know that Shapley values represent the only attribution values that satisfy **consistency**. This motivates our adapting DeepLIFT to become a compositional approximation of SHAP values, leading to Deep SHAP."

However, after checking the great distill article that you shared, I feel that IG+SHAP or Expected Gradients is still addressing the problem of not well-defined **missingness**.

Any idea about the **consistency**?

**Comment by HughChen** [comment]
Here is a [paper](https://arxiv.org/abs/1908.08474) discussing some of the axioms satisfied by expected gradients and baseline shapley (which DeepLIFT can be viewed as a biased approximation of, note that DeepSHAP is analogous to an approximation of what they call random baseline shapley).

Hope that helps!

**Comment by GZingaro** [comment]
> GradientExplainer is an implementation of Expected Gradients (introduced in this [paper](https://arxiv.org/abs/1906.10670)) which is an extension of [Integrated Gradients](https://arxiv.org/abs/1703.01365) which aims to approximate Aumann-Shapley values. My understanding is that GradientExplainer works by integrating the gradients of all interpolations between a the foreground sample (the sample being explained) and a background sample (the sample being compared to).
> 
> However, since this is computationally expensive, it does so by randomly sampling the amount of interpolation and the background sample. This random sampling means that GradientExplainer is non-deterministic. If you increase `nsamples` for `explainer.shap_values(*)`, it should converge eventually.
> 
> My explanation was a pretty short summary of Expected Gradients. For a better description, feel free to check out one of our lab member's great [distill article](https://distill.pub/2020/attribution-baselines/).
> 
> As a final note, I don't believe the expected values are returned for GradientExplainer. I think the expected values should be the average over the predictions made. But as a word of caution, for non-converged GradientExplainer attribution values, it will not satisfy local accuracy (efficiency) where the attribution values should add up to the difference between the prediction and the expected value: `self.run(self.model_output, self.model_inputs, self.data).mean(0)`

Thanks for sharing the Distill link. That's very helpful information.

**Comment by Yiru-Jiao** [comment]
> Dear Slundberg,
> 
> When using GradientExplainer, I see that each time I run the code, it returns a different SHAP value.
> 
> ```
> for i in range(3):
>     explainer = shap.GradientExplainer(model, X_train)
>     shap_values = explainer.shap_values(X_test, nsamples = len(X_test))
>     print(np.sum(shap_values)) ## check by calculating the sum
> ```
> 
> The output is
> 
> > -27.40142326031844
> > -29.111287849052133
> > -44.29400186671478
> 
> DeepExplainer returns the same result, but why it's not the case for GradientExplainer?
> 
> Besides, I couldn't find the expected values when using GradientExplainer. Does GradientExplainer have the expected values?
> 
> Thanks

I encountered the same problem and my search for a reason guided me here. Thanks for asking this out so that we have the chance to help other users who might meet the same question in the future. 

I think the inconsistency between different runs, although on the same test data, originates from the random setting of a random seed per each run of `explainer.shap_values()`. This can be seen in the source code in [Line563](https://github.com/shap/shap/blob/cadb4d0300eb2c9104a48a604910d114ffd0a84c/shap/explainers/_gradient.py#L563), which sets a random seed with `np.random.randint(0, 1e6)` if a user did not specify the argument `rseed` (by default `None`) when calling `explainer.shap_values()`.

Therefore a solution could be setting `rseed` to a fixed value when calling the function. Or if the user knows what they are doing, another solution could be setting a fixed seed when defining the explainer. If the developers of shap, a great loads of thanks for your efforts and opening spirit, noticed this problem and would be willing to make a change, we are all good.
