### ISSUE TITLE
On generating a general waterfall_plot for a multi-class classification

### ISSUE THREAD

**Issue by ivan-marroquin** [shap/shap#1034]
Hi,

I am using Python 3.6.5 on a windows machine with Shap version 0.34.0.

In the case of a multi-class classification, a way to generate a waterfall_plot is by using this command:

shap.waterfall_plot(shap_explainer.expected_value[0], shap_values[0][0], features= pd_test_inputs.iloc[0,:], feature_names= feature_names, show= False)

The produced display is based on the first row of samples in both "shap_values" and "pd_test_inputs"

If I would like to build a general waterfall_plot that includes all samples in both "shap_values" and "pd_test_inputs", what command would be the most indicated:

a) shap.waterfall_plot(shap_explainer.expected_value[0], np.sum(shap_values[0], axis= 0), features= np.sum(pd_test_inputs, axis= 0))

which produced the figure named "waterfall_first_version.png" in zip file

b) shap.waterfall_plot(shap_explainer.expected_value[0], np.sum(np.abs(shap_values[0]), axis= 0), features= np.sum(np.abs(pd_test_inputs), axis= 0))

which produced the figure named "waterfall_second_version.png" in zip file

Also, I have this suggestion: for symbols in the plot that can't have text inside because of their small size, is it possible to post the text to the right of the symbol?

One more thing. Along the x-axis, I noticed this text E[f(X)].  What value is associated with this text?

Many thanks,

Ivan

[multi-class_waterfall_plot.zip](https://github.com/slundberg/shap/files/4167537/multi-class_waterfall_plot.zip)

**Comment by slundberg** [comment]
Great suggestions! I spent some time improving the plot and now you can see both the value of E[f(X)] (the expected value of the model evaluated on the background dataset), and the values of small effects.

As for you question do (b) because (a) would always lead to values being close to zero because of cancelations. One small change I would do though is use np.mean instead of np.sum. Then you will match what the summary plot does internally.
