### ISSUE TITLE
summary plot assumes squared picture data in case shap_values.shape is 3d

### ISSUE THREAD

**Issue by wkirgsn** [shap/shap#1051]
Looking through the source code of shap.summary_plot I found that if shap values have a 3d shape, the function assumes my model is estimating squared pictures.
However, I am estimating time series with 1d-convolutional data, ending up with a shape of e.g. (1000, 8, 108) which corresponds to (observations, window_size, features).

Can we have support for time series estimation models?

**Comment by slundberg** [comment]
Ah. That is a limitation of not knowing if the extra dimension is because you have computed interaction effects or have a high dimensional input. We are working on a new explanation object API that will address that, but for now you can just flatten the last two dimensions and then remap those new indexes back to the old 2D index format (I know that is not the best right now).

**Comment by wkirgsn** [comment]
Thank you for the quick response.
I did a workaround by summing the 3d shap values over axis 1 (time-axis) making it 2d, and inserting only the last time step of features, i.e. X[:, -1, :], as this is the point in time where a prediction is made by the model.
I'm not 100% sure whether I'm distorting things by this though.
