### ISSUE TITLE
Problem with interpretation.

### ISSUE THREAD

**Issue by MarioSuaza** [shap/shap#1138]
Hello, I have the following problem with the interpretation of the graph. 
The values of the right with the yellow line, what is the meaning?
**My dataset have categorical features but i transform it in dummy variables, I don't know if shap interprets each new variable or interprets the original ones, I mean, do the names of the originals or the new variables created appear in the graph?.**

I'm using LightGBM

![image](https://user-images.githubusercontent.com/55261068/78469388-6064dd00-76e6-11ea-9a48-59d5f39bfd9f.png)

**Comment by amirrezamafi** [comment]
In this graph, each point represents the SHAP values for related feature (declared in the y-axis) for all rows in your dataset.  Since there some points for all the features in the yellow part, It means that for all the features there are some instances which their SHAP values are in 1< X < 6 
About the dummy variables, you have to consider those features (in y-axis) and theirs SHAP values in that line in the graph, then you can investigate their SHAP values. SHAP interpret what you entered for the features. So I think the results are based on your new variables.

**Comment by detrin** [comment]
@thatlittleboy CFC
