### ISSUE TITLE
Isolation forest model_output: "decision_function" not implemented

### ISSUE THREAD

**Issue by FrederickDeny** [shap/shap#1152]
Hello, while running this:

```
explainer=shap.TreeExplainer(model, X_train_scaled, model_output ="decision_function")
```

I get the following error:
```
SHAPError: Unrecognized model_output parameter value: decision_functon! If model.decision_function is a valid function open a github issue to ask that this method be supported.
```

**Comment by alexcoca** [comment]
I get this error as well when passing e.g., `model_output=predict` for xgboost. Does your model output the decision scores anyway? In this case you could try and set `model_output=raw`. Perhaps it's worth looking at the isolation forest implementation in `tree.py` to see if you can bypass the error.

**Comment by FrederickDeny** [comment]
When leave the `model_output=raw` I get a certain set of shap values, expected values, base values, that have nothing to do with the output of my model: I don't understand what shap does to get these outputs. So I am indeed working on debugging tree.py to see how it works to implement my parameter value

**Comment by alexcoca** [comment]
A few questions:

1. Are you using a background dataset or not? 

2. By base value do you mean the prediction for a sample you want to explain? 

3. What check are you performing to draw the conclusion that the shap values don't have anything to do with the model?

**Comment by FrederickDeny** [comment]
1 I am not familiar with the notion of background dataset, but I can say that I am doing anomaly detection on a log based dataset (dataset made from parsing logs).

2 No, the base value (also the expected value) is what shap believes to be the "usual" output of the model, and is simply calculated as the mean of your explained observations' outputs (In my previous answer I told about the expected value and base value separatly, that was a mistake those are the same thing sorry)

3 First of all, the `model.predict()` of my model, isolation forest, has an int of 0 or 1 for an output, but shap gives me an expected value of 12.829.. (`mode.predict()` being the standard output, corresponding to shap's `model_output=raw`).
To determine what is happening, I went through `tree.py` to see how the expected value was calculated. I then applied the code directly into my project and the output was 0.9512.
My conclusion is that I don't truly understand how shap works, so I am going throught the code to understand what it's output represents

**Comment by alexcoca** [comment]
Hi @FrederickDeny ,

1. Given your answer to 1), I presume the way you initialise the explanation model is as `TreeExplainer(model)` ?

2. What you say is not quite true for the path-dependent feature perturbation algorithm, which is what runs if you instantiate the explainer as above. The lines of code that you're looking for are lines `525-529` in `tree.h` and also `1283 - 1284` in the same file. These merely operate on the basis of the information included in the `values` attribute of the tree. In `tree.py` you will see how these values are computed if you start following the python code at lines `549-553`. Then you can see this gets back into python from C at line `272` in `tree.py`. What value means is specific for your model and you will have to check the `sklearn` docs. In general it is an attribute derived from the training data on the basis of the training data subsets that flow through a particular tree branch. In general, the "usual" output of the tree ensambles is computed by taking the weighted values of the values of the root for each tree in the ensamble. 

3. `shap` cannot be used to explain hard labels. Since it is an additive method, it is usually best used in 'margin' space (i.e. before converting outputs to probabilities). Although your `sklearn` predict method returns a hard label, you should note that when you explain something, this is executed in `C++` in `tree.h`. What you are explaining the is `raw` model output (which is likely a decision score, with values over the entire real numbers), the weighted summation of your tree output acroos your ensamble. This happens because the `C++` code gets a representation of your model in a standardised format and applies the algorithm to it. 

What your output represents is a a decomposition of the score returned by your tree ensamble - the expected value across, for each input feature. If you do `shap_values.sum(1) - model.decision_function(X_explain) + explainer.expected_value` you should get 0 (or maybe some constant offset).

**Comment by FrederickDeny** [comment]
I now understand what is a background dataset, I didn't realise it was a shap related notion, sorry about that, because I absolutely use one.
Otherwise, your other points made me understand what shap was returning: indeed not a label but the average number of splits before my observation's corresponding leaves, which is how IsolationForest detects anomalies.

Thanks you so very much for your time and help.

I don't know if I'm supposed to close this issue, as the original purpose of it is to ask the implementation of the decision function, eventhought you answered my underlying issue

**Comment by alexcoca** [comment]
No problem at all, I'm glad you got to the bottom of it. And yes, if you passed the background dataset to then it would just average the actual model output over the background examples.

I'm not sure how @slundberg plans to design regarding the use of `decision_function`, he will be best placed to advise in this respect. Maybe docs should state that to explain the `decision_function`    output one should pass `model_output=raw` for this example.

**Comment by xm4ch1n3** [comment]
@alexcoca, the following example demonstrates that `shap_values.sum(1) - model.decision_function(X_explain) + explainer.expected_value` is way off:

```python 
X_, y_ = shap.datasets.boston()
model = IsolationForest()
model.fit(X_)

explainer = shap.TreeExplainer(model, data=X_)
shap_vals = explainer.shap_values(X_[:10])

assert all(abs(shaps.sum(1) - (model.decision_function(X_[:10]) + explainer.expected_value)) < 1e-6) # fails
``` 

However, it seems that the `KernelExplainer` returns a constant offset 
```python 
X_, y_ = shap.datasets.boston()
model = IsolationForest()
model.fit(X_)

f = lambda x: model.decision_function(x)
explainer = shap.KernelExplainer(f, data=shap.sample(X_, 100))
shap_vals = explainer.shap_values(X_[:10])

assert len(set(shap_vals.sum(1) - (f(X_[:10]) + explainer.expected_value))) == 1
```

**Comment by wundermahn** [comment]
@leoentersthevoid this is a great example. Thank you. 

Why is it necessary to run this as a lambda function? Why can I not do:
```
X_, y_ = shap.datasets.boston()
model = IsolationForest()
model.fit(X_)

explainer = shap.KernelExplainer(model.decision_function, data=shap.sample(X_, 100))
shap_vals = explainer.shap_values(X_[:10])
```

Thanks for your great example of the issue.

**Comment by alexcoca** [comment]
> @alexcoca, the following example demonstrates that `shap_values.sum(1) - model.decision_function(X_explain) + explainer.expected_value` is way off:
> 
> ```python
> X_, y_ = shap.datasets.boston()
> model = IsolationForest()
> model.fit(X_)
> 
> explainer = shap.TreeExplainer(model, data=X_)
> shap_vals = explainer.shap_values(X_[:10])
> 
> assert all(abs(shaps.sum(1) - (model.decision_function(X_[:10]) + explainer.expected_value)) < 1e-6) # fails
> ```
> 
> However, it seems that the `KernelExplainer` returns a constant offset
> 
> ```python
> X_, y_ = shap.datasets.boston()
> model = IsolationForest()
> model.fit(X_)
> 
> f = lambda x: model.decision_function(x)
> explainer = shap.KernelExplainer(f, data=shap.sample(X_, 100))
> shap_vals = explainer.shap_values(X_[:10])
> 
> assert len(set(shap_vals.sum(1) - (f(X_[:10]) + explainer.expected_value))) == 1
> ```

Hi @leoentersthevoid ,

I no longer work on this, but I remember making a remark about the expected value for the interventional TreeShap algorithm in the examples to [alibi](https://docs.seldon.io/projects/alibi/en/stable/examples/interventional_tree_shap_adult_xgb.html). You can check that example out and my thoughts about it there.

**Comment by pjgao** [comment]
> @alexcoca, the following example demonstrates that `shap_values.sum(1) - model.decision_function(X_explain) + explainer.expected_value` is way off:
> 
> ```python
> X_, y_ = shap.datasets.boston()
> model = IsolationForest()
> model.fit(X_)
> 
> explainer = shap.TreeExplainer(model, data=X_)
> shap_vals = explainer.shap_values(X_[:10])
> 
> assert all(abs(shaps.sum(1) - (model.decision_function(X_[:10]) + explainer.expected_value)) < 1e-6) # fails
> ```
> 
> However, it seems that the `KernelExplainer` returns a constant offset
> 
> ```python
> X_, y_ = shap.datasets.boston()
> model = IsolationForest()
> model.fit(X_)
> 
> f = lambda x: model.decision_function(x)
> explainer = shap.KernelExplainer(f, data=shap.sample(X_, 100))
> shap_vals = explainer.shap_values(X_[:10])
> 
> assert len(set(shap_vals.sum(1) - (f(X_[:10]) + explainer.expected_value))) == 1
> ```

In an IsolationForest, the values of leaf nodes are randomly generated and meaningless. What needs to be calculated is the *traversal depth of each sample*. 
> The `iTree` in `sklearn` is implemented based on `ExtraTreeRegressor`. Therefore, a pseudo label ` y = rnd.uniform(size=X.shape[0])` is generated for consistency.  

![image](https://user-images.githubusercontent.com/22350313/115548168-bef0ff00-a2d9-11eb-97f1-c88954d63e91.png)
In the calculation of `sklearn`:
```python
scores = 2 ** (-depths/  (len(self.estimators_)* _average_path_length([self.max_samples_]))  )
```
whereas `depths/len(self.estimators_)` is the average path of samples in different trees. (`depths` is the sum of path depths of a sample in different trees) , `_average_path_length([self.max_samples_])` is used to normalize the abnormal scores in isolated forests constructed by different sample sizes.
The `IsolationForest` in the `shap` library explains exactly the average depth of samples in different trees : `depths/len(self.estimators_)`.
For example:
```python
import numpy as np
import shap
from sklearn.ensemble import IsolationForest
from sklearn.ensemble.iforest import _average_path_length

X, y = shap.datasets.boston()
model = IsolationForest(max_features=1.0,random_state=1)
model.fit(X)


explainer = shap.TreeExplainer(model)
test = X.iloc[[0],:]
score = model.score_samples(test)

shap_explained = explainer.shap_values(test).sum()+explainer.expected_value
#score = 2 ** (-iso_calculated/ _average_path_length([self.max_samples_]))
iso_calculated = -np.log2(-score) * \
    _average_path_length(np.array([model.max_samples_]))
print(shap_explained, iso_calculated)
# [11.52547704] [11.52547704]
```
You can see:
1. Since the results returned by `score_samples` in `sklearn` are calculated using `score = 2 ** (-iso_calculated/ _average_path_length([self.max_samples_]))`, the average path length that should be interpreted can be calculated, `iso_calculated = -np.log2(-score) * _average_path_length(np.array([model.max_samples_]))`, which is the same as `explainer.shap_values(test)+explainer.expected_value`.
2. Deduce the return value of score_samples from the SHAP interpretation result.

   ```python
   print(2**(-shap_explained/_average_path_length([model.max_samples_])))
   print(score)
   # [0.45849862]
   # [-0.45849862]
   ```
3. Calculation of `explainer.expected_value`. The calculation of `explainer.expected_value` in SHAP is to recalculate the node value. That is, the randomly generated node value is replaced with the average depth of the node, and the average depth of the root node is used as the basic value.

   ```python
   def recalculate_node_value(tree):
       values = tree.value.reshape((tree.value.shape[0]), 1)
   
       def _recalculate_value(tree, i, level):
   
           if tree.children_left[i] == -1 and tree.children_right[i] == -1:
               value = level + \
                   _average_path_length(np.array([tree.n_node_samples[i]]))[0]
               #print(tree.n_node_samples[i])
               values[i, 0] = value
               return value * tree.n_node_samples[i]
           else:
               value_left = _recalculate_value(
                   tree, tree.children_left[i], level + 1)
               value_right = _recalculate_value(
                   tree, tree.children_right[i], level + 1)
               values[i, 0] = (value_left + value_right) / tree.n_node_samples[i]
               return value_left + value_right
       _recalculate_value(tree, 0, 0)
       return values
   
   expected_value = sum((recalculate_node_value(est.tree_) /
                         model.n_estimators)[0][0] for est in model.estimators_)
   print(expected_value)
   print(explainer.expected_value)
   # 11.908404682235796
   # [11.90840468]
   ```

**Comment by xm4ch1n3** [comment]
@pjgao, great insight, 10x a lot
