### ISSUE TITLE
MemoryError: Unable to allocate array with shape (2602, 7470630) and data type float64

### ISSUE THREAD

**Issue by Dola47** [shap/shap#1173]
Hi All,

I am trying to use SHAP kernel to explain my model, however, I am always getting the following error.

Any ideas, how to overcome this error!

I can not attach a jpg file of the error, there is always an error while uploading it. However, to give more details, I am submitting a PandaDataframe to shap.KernelExplainer which is (21654 rows × 345 columns), and  to the explainer.shap_values I am submitting a DataFrame which is 20 rows × 345 columns. I do not know from where the sizes in the error of (2602, 7470630) come?

My full dataset comes in with 40849 rows. if the solution is just to truncate down my dataframes because their sizes is quite large, I think that will not be helpful. I will not be able to explain my data sufficiently then. Any ideas how to overcome the MemoryError without the need to truncate my dataframes severely?

**Comment by slundberg** [comment]
If you are trying to use a background distribution with 21k rows then you might have trouble. Just use 1k and you will still have a really good background sample (even 100 is usually pretty good). Then also see if reducing 20 to 5 or 1 makes a difference.

**Comment by Dola47** [comment]
@slundberg I think you mean that the 1k should be submitted as the train data to the KernelExplainer, Am I right? 

Moreover, what I really aim for is that I have some scrap parts they are exactly 78 rows only, and their columns is 345. I think those ones should be submitted to the explainer.shap_values, to get their explanation. But, what I really want to have at the end is to find out what are the best common features used in the explanation of these 78 parts with their scores, is that possible in SHAP. Or, I can only have the explanation of each single part alone?

Can you also provide a clarification of what explainer.expected_value, and shap_values stand for and why there length is usually 2?

**Comment by slundberg** [comment]
1. Yes. That is the background data used to compute what happens when a feature is missing, so just. random sample of you training data is normally what people use.
2. Just do a summary_plot (with plot_type='bar' if you like). It shows np.abs(shap_values).sum(1) which is a global summary of feature importance.
3. explainer.expected_value is the expected value of the model evaluated on the background dataset (so the average output when the model is run on the background data). It is often of length 2 when you have two output classes in binary classification.

**Comment by Dola47** [comment]
@slundberg  

1- Great, the global summary of feature importance is calculated from the shap_values, so it will be calculated from the important 78 parts I have, is that correct? Because I submit only the most important 78 parts to the explainer.shap_values.

2- Does it make sense to submit the explainer and the shap_values with the same dataset( It will be the most important 78 parts in my case), because I only care about these parts?

3- The jupyter kernel crashes usually, when I submit the 78 interesting parts to the shap_values, Do you know how to overcome that? (It may be becuase some rows of these interesting parts has values of Nan, shap_values can accept nan values, or it crashes because of that?)

**Comment by slundberg** [comment]
1. Right.

2. Depends if you want to know how those parts are different from each other or from a larger population of parts. For example if all the 78 parts have plastic = True, but the larger population of parts are often not plastic, then using the larger population would make plastic = True be informative (and have impact) while if you just use the 78 then plastic = True is not informative since you already expect it from you background.

3. Not sure, but I would try one row at at time until it dies. Then check to see what is coming in to your prediction function and if you die in there.

**Comment by Dola47** [comment]
@slundberg  Thanks a lot for your response.
For the previous point 3 the problem was that the dataset that I passed to the explainer was consisting of 1000 rows, that was so much I passed only 500 rows and it took around 5 hours to be done.

Now, I have the summary_plot as you mentioned, can I access the features and the scores manually to be able to save them in a PandasDataFrame for example, or I can only have a look over them through the plot, but I cannot really access them?

**Comment by Dola47** [comment]
@slundberg  Any further response?

**Comment by manav3475** [comment]
> Hi All,
> 
> I am trying to use SHAP kernel to explain my model, however, I am always getting the following error.
> 
> Any ideas, how to overcome this error!
> 
> I can not attach a jpg file of the error, there is always an error while uploading it. However, to give more details, I am submitting a PandaDataframe to shap.KernelExplainer which is (21654 rows × 345 columns), and to the explainer.shap_values I am submitting a DataFrame which is 20 rows × 345 columns. I do not know from where the sizes in the error of (2602, 7470630) come?
> 
> My full dataset comes in with 40849 rows. if the solution is just to truncate down my dataframes because their sizes is quite large, I think that will not be helpful. I will not be able to explain my data sufficiently then. Any ideas how to overcome the MemoryError without the need to truncate my dataframes severely?

Actually, i was really getting this type of error but it was not solve from last 3 days how to solve this any one have idea
