### ISSUE TITLE
Question: Is the feature importance ranking computed from dataset applicable to a specific instance?

### ISSUE THREAD

**Issue by ghost** [shap/shap#1190]
Say we have 100 features for a binary classification problem. Through a feature importance ranking method, 3 features are determined as the most important features for predicting positive class for the entire dataset for LightGBM. Then we have a new datapoint that is predicted to be in the positive class. Is it still valid to say these 3 features are the most important features that contributes to the prediction?

**Comment by alexcoca** [comment]
@kdlin,

The importances returned for your new feature are just the shap value magnitudes. Check what features they represent and see if they are the same as the 3 features you identified previously - this may or may not be true.

**Comment by detrin** [comment]
@kdlin I think most of the cases it is safe to assume that. Your model is discriminatory, so the new datapoints should be sampled from the distributions from which training data were sampled. Otherwise no, they maybe not the 3 top important features. Also, note that importance is macroscopic in a sense that it is evaluated to the whole set not to one observation.

@thatlittleboy CFC
