### ISSUE TITLE
Base values always conditional?

### ISSUE THREAD

**Issue by dswatson** [shap/shap#12]
Hi,

I've noticed that all the sample notebooks appear to require training data to ascertain base values. But say all I've got is a black box model. I don't know its architecture and I don't have access to the original training data. Will I simply have to guess E[f(x)] from my test data? Is it fair to say that base value estimates are always conditional on some input, and that only the training data used to fit the model is guaranteed to provide unbiased estimates of E[f(x)]?

Thanks,
David

**Comment by slundberg** [comment]
Good points. Hopefully your test data is from the same distribution as your training data. If not then your model will suffer, and I would actually argue that in that case the test data better reflects what you want for feature importance.

As an intuition for why you need some kind of distribution (or reference value) when defining feature importance consider the following example: Imagine a linear model predicts that risk increases with body weight. For a person with lower than average body weight, we would say their weight reduces their risk (negative SHAP value). For a person with above average weight we would say their weight increases their risk (positive SHAP value). These statements require some notion of what "normal" or average is, and this is supplied by the background distribution you provide to the method.

**Comment by dswatson** [comment]
Interesting. That all makes good sense. I was thinking about a hypothetical case where we don't have a great idea what the true distribution of relevant features looks like, but we've got a fully specified model and a single observation whose predicted value we'd like to explain. I suppose we could just simulate data around that point, but without a large dataset or other reliable reference I imagine we'd be at risk of getting biased base values.

**Comment by slundberg** [comment]
When you don't know what the data distribution is, then I think the best bet would be to pick some reasonable reference value and just use that as the reference "distribution." I would not sample around the current data point you are explaining since that would ensure all the of features are are exactly "normal" and hence not important.

**Comment by dswatson** [comment]
Ahh of course, if x is the data centroid then it would by definition have all zero Shapley values! That's interesting, because it seems like you should still be able to learn something about model behavior by recording inputs and outputs in this scenario, no? You could potentially approximate a decision boundary or estimate a regression surface this way, even if your only true observation is far from the training data centroid. I imagine it would be very inefficient in high-dimensional settings, however.

**Comment by slundberg** [comment]
Right, you can map out the entire function by just twiddling inputs, but
without a reference point or distribution it is hard to say if a specific
feature is raising or lowering the prediction (meaning should the SHAP
value be positive or negative). Since "raising" and "lowering" are always
with respect to some alternative.
