### ISSUE TITLE
Extract individuals term in the weighted average

### ISSUE THREAD

**Issue by muhlbach** [shap/shap#122]
Hi! Once again, thanks for a cool contribution to the machine learning toolbox!

I'm wondering whether it is possible to extract all the terms used in the weighted average to estimate the SHAP value for a given regressor? If you could direct me to the specific part of the code that does that, I can maybe do it myself?

Best, Nicolaj

**Comment by slundberg** [comment]
You mean the terms in the weighted average that produce a single SHAP value or the whole vector of SHAP values? For Kernel SHAP the weighted averages are not separated by feature, since they are all coupled in the linear regression equation. The recently pushed SamplingExplainer does use the independent feature averaging and should be fairly straightforward (at least before the final rebalancing step). Does that help?

**Comment by muhlbach** [comment]
It is exactly the terms in the weighted average that produce a single SHAP value per regressor I was looking for. I'll check out your SamplingExplainer. Can you elaborate briefly on what you mean by " in the weighted average that produce a single SHAP value"?

**Comment by muhlbach** [comment]
Relatedly:
If I go to "shap/shap/explainers/sampling.py" and set def explain to return phi_var, i.e. something like "return AdditiveExplanation(self.fnull, model_out, phi,  phi_var,  np.zeros(len(phi)), instance, self.link, self.model, self.data)", then I would get the estimated variance of phi, right?

Sorry for all these questions!


 phi_var

**Comment by slundberg** [comment]
That would give the estimated variance of the phi estimate for the SamplingExplainer. For the variability of SHAP values in general I would recommend using bootstrap resamples of the training data to retrain the model many times and see the variability of the explanations.
