### ISSUE TITLE
Xgboost binary format compatibility

### ISSUE THREAD

**Issue by RAMitchell** [shap/shap#1302]
In #1215, changes to the xgboost binary format break integration with the shap library and lead users to downgrade xgboost or create other hack solutions.

Xgboost makes no promises about the consistency of its binary format, except that it may save and load its own models, so this is likely to occur again in future xgboost releases.

I propose that shap migrates to the newer json based serialisation format that has better compatibility guarantees: https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html (cc the author of this feature @trivialfis)

After migration I propose adding shap tests to xgboost CI in order to prevent this from our end.

**Comment by YannDubs** [comment]
@RAMitchell  I think this would be great. Currently, there are some new features that are not usable due to using the old binary format, for example categorical features (see #2662 ).

**Comment by YannDubs** [comment]
This seems even more important given that Xgboost plans to drop support from old binary format (see: [here](https://github.com/dmlc/xgboost/7547) and [here](https://github.com/dmlc/xgboost/blob/ee382c4153a675b0ecd21cc940e55ae8ae509a25/NEWS.md#new-serialization-format) ).

It seems that SHAP used JSON [before](https://github.com/slundberg/shap/commit/397ed9278fc81c858d3188171dda7591531ccc0d) but it was reverted by @slundberg  [here](https://github.com/slundberg/shap/commit/397ed9278fc81c858d3188171dda7591531ccc0d) due to conversion issues. Maybe the newer UBJSON format of Xgboost can help here?

**Comment by CloseChoice** [comment]
Resolved via #3345
