### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BrunoBarre** [shap/shap#1369]
Hello, is this normal that since a few weeks, the documentation, [Doc page,](https://shap.readthedocs.io/en/latest/) is almost empty. Now it only contains the different function names, but no more.

Is there a better page (couldn't find it yet), or is it possible to come back to a previous version of this page, which had better documentation?

Thanks a lot.

**Comment by slundberg** [comment]
Thanks for bringing this up! I didn't think about how this would happen during the refactor...

The issue is that we just pushed a significant new/cleaner API for SHAP and everything has been moved around. So that must have messed up Sphinx. I will take a look at this as soon as I can, but I expect it will take a week or two since I am about to switch over the docs to the new API (note the old API should all still work fine), and that will change all these pages.

**Comment by jonnor** [comment]
The documentation page is up again now, and have been for a year or so.
This issue can be closed, CC @slundberg
