### ISSUE TITLE
SHAP independent tree explainer: Fractions of zeros and ones for filling up the subsets with EXTEND function

### ISSUE THREAD

**Issue by tgunder** [shap/shap#1371]
Hey there,

Regarding the SHAP treeExplainer I could use your data science expertise regarding the following question about the independent tree SHAP:

In the paper about the shap treeExplainer (https://arxiv.org/pdf/1905.04610.pdf)
![Bildschirmfoto 2020-08-18 um 14 13 15](https://user-images.githubusercontent.com/69851866/90511601-00367b00-e15d-11ea-81e2-fb23ce86827d.png)
 it is stated that the algorithm basically tracks which subsets (and also which fractures) of each subsets lands in the specific leaves of the decision tree.
However, as the subsets are "split" sometimes (as features for a decision at a node might not be part of the subset S), the function EXTEND "grows" the fractions of subsets (to have a similar size of subsets for SHAP-calculation). The subsets are here extended with a "fraction of zeros and ones" that are represented by p_z, p_o and p_i.
 
Is these fraction of zeros and ones basically the representation of the features that are "present" and "absent" in the current subset?

Thanks in advance and have a great day/evening/night :)

**Comment by HughChen** [comment]
Hi!  

The algorithm you've posted is actually TreeExplainer with "tree_path_dependent" set as the feature perturbation method, which I'm not super familiar with.  I think the p_z, p_o, and p_i might have more to do with the fraction of samples rather than features but I could be wrong.

If you'd like to know more about the algorithm for **Independent Tree SHAP** (now called Interventional Tree SHAP) feel free to check out this [article](https://hughchen.github.io/its_blog/public/) (which aims to describe the algorithm with visualizations).  Section 2.3 has the recursive version of the algorithm which I re-implemented iteratively for the package.

I'm biased towards the newer Interventional Tree SHAP which is TreeExplainer with "interventional" set as the feature perturbation method because I wrote the algorithm with Scott.  However, "interventional" is the default method for TreeExplainer if you provide background data and I personally prefer it to "tree_path_dependent" because it gives the same SHAP values as Kernel SHAP and Sampling SHAP, but much faster.

If you have more questions about Interventional Tree Explainer feel free to let me know!
