### ISSUE TITLE
C++ version of shap

### ISSUE THREAD

**Issue by leannejdong** [shap/shap#1397]
In README,
"Fast C++ implementations are supported for XGBoost, LightGBM, CatBoost, scikit-learn and pyspark tree models"
Do you reckon the current repo can be translated into a C++ version as well?

**Comment by jonnor** [comment]
Hi @leannejdong, thank you for your interest!
This is an implementation of Shapley values implemented in Python. There are no plans to re-implement in C++. That would best be done as a new project and Github repository, and anyone is free to start such a project. If anyone does so, or knows of an existing project, please leave a comment here!

But since this is not in scope of this project, I am proposing to makr this issue  as closed. CC @slundberg
