### ISSUE TITLE
Return probability shap_values from DeepExplainer

### ISSUE THREAD

**Issue by vidasci** [shap/shap#1411]
First of all, great library. I'm trying to create a DeepExplainer for a multiclass classification model created in tf.keras. With a TreeExplainer it is possible to set model_output to "probability". I've been looking for a similar option for the DeepExplainer but didn't find it. 

Is there any way to obtain probabilities from a DeepExplainer so that it returns shap_values between -1 and 1? If not, any suggestions on how to transform the shap_values to (approximate) probabilities? 

Any help would be appreciated.

**Comment by slundberg** [comment]
When you explain a keras model you are explaining the output of the function defined by that model, so it that function outputs probabilities then you will get explanations of the probabilities. The reason Tree explainer needs a separate option is because of the unique exact algorithm used inside that method.

So in summary, just pass a different keras model that outputs probabilities instead of margin/log-odds.

**Comment by vidasci** [comment]
Thanks for the explanation, I managed to got it working
