### ISSUE TITLE
Where to find slicer repo?

### ISSUE THREAD

**Issue by JSybrandt** [shap/shap#1414]
Hello,

I'm trying to hunt down the slicer dependency that was added in v0.36.0
I see the files on pypi (https://pypi.org/project/slicer/) but the actual repo (https://github.com/interpretml/slicer) is missing.
It appears that interpretml pulled the repo off github? Is there a new location to find this?

**Comment by slundberg** [comment]
Not pulled off, just not pushed out yet :) It should be very shortly though! The new SHAP API in 0.36 powered by slicer is in collaboration with InterpretML and so we are trying to stay in sync as we roll it out. Once things are fully stable for the new API using slicer we will update the SHAP docs.

As a side-note, slicer was written to support the parallel slicing needs of the new Explanation objects, it just lives as an independent repo since it has more general utility.

**Comment by JSybrandt** [comment]
Thanks for getting back to me. I'll be keeping a lookout for slicer :)
