### ISSUE TITLE
Adding second and third order support for AdditiveExplainer

### ISSUE THREAD

**Issue by nickcorona** [shap/shap#1433]
Is adding support for second and third-order effects in the works for AdditiveExplainer? Currently, I see this explainer as equivalent to LinearExplainer if it doesn't account for second and third-order effects since AdditiveExplainer cannot be used to explain generalized additive models for example.

```py
"""
Computes SHAP values for generalized additive models.

This assumes that the model given only has first order effects. Extending this to
2nd and third order effects is future work (if you apply this to those models right now
you will get incorrect answers that fail additivity).
"""
```

**Comment by HughChen** [comment]
I'm not sure whether second/third order effects are in the works, but I think it's different because LinearExplainer only works for linear models (and supports observational conditional and interventional conditional expectations - see [this paper for details about both](https://arxiv.org/abs/2006.16234)), but AdditiveExplainer works for GAMs, so stuff like univariate tree models, univariate neural networks work too.
