### ISSUE TITLE
Shapv alue

### ISSUE THREAD

**Issue by solracli** [shap/shap#1457]
I'm trying plot the shap graph like this:
![image](https://user-images.githubusercontent.com/41172192/93884148-e8e93100-fcb8-11ea-9651-11588986e78b.png)

but the graph that is ploting is a bar graph like this:
![image](https://user-images.githubusercontent.com/41172192/93884221-fe5e5b00-fcb8-11ea-8841-72a861015a7c.png)

the error: Setting feature_perturbation = "tree_path_dependent" because no background data was given.

Code
import shap
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test)
shap.summary_plot(shap_values, X_test)

what can I do to fix this ??

**Comment by HughChen** [comment]
Hi - that error isn't actually an error it should just be a warning.

Also the reason you have bars is because it's treating it as a multi-class problem even though it looks to be binary.

If you check `shap_values.shape` it should be something like `(# samples, # features, # outputs)`.  Just do `shap.summary_plot(shap_values[:,:,0], X_test)` and you'll get the summary plot for the negative class I believe and `shap.summary_plot(shap_values[:,:,1], X_test)` will give you the beeswarm summary plot for the positive class (which should be like 1 minus the negative class).
