### ISSUE TITLE
Calculating SHAP values for large dataset

### ISSUE THREAD

**Issue by RoyHirsch** [shap/shap#1495]
Hi, thank you for this lovely tool.

I'm trying to calculate the SHAP values for a very large dataset (over 1M samples), I've encountered some performance issues - the computation takes lots of time (the running time of the function: shap_values).
All the examples I've seen are applying the package over relatively small datasets. Does this implementation support ~1M input samples? are there ways to accelerate the computation? 

thank you,
Roy

**Comment by AndreasThinks** [comment]
I'm having pretty similar issues.  I tried to run it on a 100k data-set with 2 output classes and it took far longer to run than I anticipated (comparing to PDPBox, though in hindset very different method!).  I'm finding it limiting to 100 or so rows works, but obviously makes it a lot less useful!  Going to try and run 1000 overnight.

**Comment by mirekphd** [comment]
@RoyHirsch @crimsoneer : great news guys, thanks to @RAMitchell CUDA work there is now a GPU implementation at least for tree-based algos. Have a try yourselves, you may be pleasantly surprised by the performance improvements, just like I was: here's a reproducible performance test using our CUDA 10.1 py38 container: https://github.com/slundberg/shap/issues/1650#issuecomment-748482915. 

When we moved the estimation of SHAP values on a 100k sample (times a few hundred columns) from the CPU (a single thread of Intel Xeon Platinum) to the GPU (a single Tesla V100 utilized at 100% and reaching 80C...:), the wall clock time shortened from an hour to... less than a minute!:) GPU has enormous advantage here, because standard TreeExplainer is only single threaded (so it was like running `glm()`... in R:).

**Comment by pawarbi** [comment]
@RoyHirsch [This answer ](https://github.com/slundberg/shap/issues/77)by @slundberg might help.. I'ld suggest sampling the data instead of using the entire dataset to get the SHAP values

**Comment by djoguns** [comment]
Hi Everyone,

Let me know if this helps anyone, but after running several hours on a dataset of about (1M, 70), I had to do the following:

```
# Tree Explainer
# model_pkl_name -> Model Object
explainer_base = shap.TreeExplainer(model_pkl_name)

# SHAP Values
# Use the following as shown for large dataset
# Set approximate=True and check_additivity=False
# df_shap -> concerned dataset
explainer_base_values = (
    explainer_base.shap_values(
        df_shap,
        approximate=True,
        check_additivity=False
    )
)
