### ISSUE TITLE
(Paper): Conditional Expectation Calculation & Inverse Function Questions

### ISSUE THREAD

**Issue by decodyng** [shap/shap#15]
Note: these questions refer to [the paper underlying this method](http://papers.nips.cc/paper/7062-a-unified-approach-to-interpreting-model-predictions.pdf), not directly to the code 

1) In equation 12, you argue that you can calculate the conditional expectation term by simply calculating the function value using the actual instance values of the features in set S, and the expected value of the features in set S-complement (essentially, it seems, marginalizing over the  features in set S-complement). But, then, in the kernel approach, it's not clear to me how you're calculating this expectation. Is the idea that, for all features in z' that are in set S-complement (that is to say: are set to 0) their corresponding values in the non-simplified vector are set to the overall average (i.e. expected value) of each feature? That seems to be the implication, but I can't find anywhere in the paper where it definitively says so. 

2) In Theorem 2, why is an inverse function of h_x applied to the z' vector? In all prior cases, the mapping function h_x has taken an input of simplified features, and given an output of non-simplified features, suitable for being given to your trained model. Why, in this case, would we be using an inverse of that function when the input we're giving it is a z' simplified feature vector?

**Comment by slundberg** [comment]
Good questions!

1. Equation 12 is a further simplification of Equation 11, and depending on what you pass as a background distribution dataset Kernel SHAP could use either approximation (at least as implemented here). Passing a background dataset with just a single sample does exactly what you guessed, it replaces all the features with a 0 in `z'` with the value from the passed background dataset sample, and leaves all the features with a 1 in `z'` unchanged. If however you pass many samples then it repeats the process for each background dataset sample and then averages the resulting model outputs to get the expected model output over the samples. In practice you can weight the samples and so pass a set of `k` weighted medians rather than an entire dataset to speed up the process.
2. Thanks!!! That's a typo from a last-minute notational change I made. It should not be inverted. Fortunately we are still in the NIPS update period so I'll fix that.

**Comment by decodyng** [comment]
Okay, that makes sense! 

Out of curiosity, what do you think is the best way to approach the "superpixels" simplified features used in the original LIME? Since there doesn't seem to be an obvious definition of what it means to take the "expected" superpixel over the distribution of possible superpixels.  And it seems like there are arguments for either setting all of those pixels to the global pixel average, or else the pixel average within that superpixel. My suspicion is that the practical difference isn't dramatic, but I am curious if your intuitions on this problem cause you to lean in one direction or the other.

**Comment by slundberg** [comment]
Super pixels are tricky. The ideal would be if you built a conditional generative model that could impute arbitrary parts of an image conditioned on the rest. If you had this then you could draw samples from it and integrate over them without the independence assumption of Eq 11 or the linearity assumption of Eq 12.

In practice that would be computationally challenging and I have not seen anyone do that (since I don't focus on images I have not tried either). So given that as the ideal, I would say do whatever approximation to it that you prefer. I imputed with the average of the surrounding super pixels for my experiments and took that as the single reference value (no integration).
