### ISSUE TITLE
deep lift / deep shap vs deep taylor

### ISSUE THREAD

**Issue by BenMacKenzie** [shap/shap#154]
Is there any analysis or comparison between Deep Shap and Deep Taylor layer-wise relevance propogation https://arxiv.org/pdf/1512.02479.pdf?

Best

**Comment by slundberg** [comment]
I want to give a more thoughtful answer here than I have had time for yet. I'll post when I can.

**Comment by BenMacKenzie** [comment]
thanks!

**Comment by slundberg** [comment]
Took me a while but I got back to this going through old issues. Deep SHAP (like DeepLIFT that motivates it) linearizes each node just like Deep Taylor layer-wise relevance propogation does. However it does not constrain the credit assigned to each input feature to be positive (which Deep Taylor layer-wise relevance propogation does). DeepLIFT choses the root points for linearization based on propagating a reference value through the whole network so that the sum of the feature attributions equals the difference between the output of the network on the reference value and the output for the current input. This is different than deep taylor which has a several root point choosing methods. Deep SHAP in contrast to DeepLIFT computes the Shapley values for each small component and then puts them together, which is different than linearizing a node using a taylor approximation (this allows us to have justified rules for complex components like max pooling layers).

Deep SHAP is an approximate SHAP method since combining the attribution values of each network component is done as if all the components of the network were linear, but of course they are not.
