### ISSUE TITLE
Suppress scientific values from force plot

### ISSUE THREAD

**Issue by parulML** [shap/shap#159]
![capture_11111111111](https://user-images.githubusercontent.com/40829427/42756637-a3a82150-891a-11e8-8536-05e559e5da04.PNG)
I want to suppress the scientific values in force plot to numbers for better interpretations. When i went through the package code i inferred that for visualizations IML library is used but i could not reflect any change after slogging whole day. So my question is:
1) Is there any option already available to suppress scientific values as for output values we can see **numbers**. if not then where i can make changes so that i can get rid off scientific values.

**PS**: Apologies if this issue is already there and I ignored. Thanks in advance.

**Comment by slundberg** [comment]
Ah. That is something controlled by a print formatter in D3 in the IML library. In order to change it you need to update the JS code `this.tickFormat = format(",.4");` on line 141 of AdditiveForceVisualizer.jsx then recompile the JS code bundle to something like `this.tickFormat = format(",.6");`. It would be good to have that format string as a parameter like `plot_cmap` is. Do you feel comfortable adding it?
