### ISSUE TITLE
Weird SHAP value on nonsense features

### ISSUE THREAD

**Issue by ZhangTP1996** [shap/shap#1601]
Here is a reproducible example:

```python
import shap
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn import datasets

iris_data = datasets.load_iris()
X = iris_data.data
y = iris_data.target
columns = ["SpealLength", "Spealwidth", "PetalLength", "Petalwidth"]

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=2)
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    X_test[:, 3] = -1
    gbm = lgb.LGBMClassifier()
    gbm.fit(X_train, y_train)

    explainer = shap.TreeExplainer(gbm)
    shap_values = explainer.shap_values(X_test)
    shap_values = np.mean(np.abs(np.array(shap_values))[0], 0)
    feature_sv = sorted(zip(columns, shap_values), key=lambda x: x[1], reverse=True)
    print(feature_sv[:10])
```

And the results show:
[('PetalLength', 4.858092780782831), ('Petalwidth', 0.0012865959831269906), ('Spealwidth', 3.8665361772338584e-05), ('SpealLength', 0.0)]
[('Petalwidth', 2.655228940497153), ('PetalLength', 2.421352212484698), ('Spealwidth', 0.5307075601481597), ('SpealLength', 0.0037697507681040774)]
[('PetalLength', 2.173101023727372), ('Petalwidth', 2.057670109460788), ('Spealwidth', 0.7979735129785577), ('SpealLength', 0.024708537502171113)]
[('PetalLength', 2.867789710676412), ('Petalwidth', 1.9952776618118169), ('Spealwidth', 0.4509510975472647), ('SpealLength', 0.0013865223007028945)]
[('Petalwidth', 2.8352003391762564), ('PetalLength', 2.4441519324102843), ('Spealwidth', 0.4346696659994451), ('SpealLength', 0.020631343251965934)]

What happens?? Since Petalwidth has been set to -1 in X_test which is a nonsense value and never appears in training set before, why it still has such a large shap value?

**Comment by ZhangTP1996** [comment]
And there is an exception if I pass X_train to shap.TreeExplainer:
Exception: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then pleas
e report this on GitHub. This check failed because for one of the samples the sum of the SHAP values was -8.478234, while the model output was -8.813882. If this difference is acceptable you can set c
heck_additivity=False to disable this check.

**Comment by sparvaneh** [comment]
I have a similar issue with both training and test data. I am getting the following exception with scikit-learn=0.23.2 and shap=0.37.0

Exception: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option. This check failed because for one of the samples the sum of the SHAP values was 0.626204, while the model output was 0.710000. If this difference is acceptable you can set check_additivity=False to disable this check.
