### ISSUE TITLE
Tree SHAP and dummy categorical features

### ISSUE THREAD

**Issue by mizukasai** [shap/shap#165]
Hello,

I wanted to get some opinions on using feature groups in tree SHAP (just like in Kernel SHAP) in order to group dummy features that belong together. I wonder if this is actually useful? if it changes anything in the quality of the explanation?

Thanks,

**Comment by slundberg** [comment]
Grouping in Kernel SHAP is primarily for performance reasons (and to make sure we don't break important feature dependencies inside the group during sampling). But for Tree SHAP you can just explain everything and then add the features together afterwards to the get the SHAP value for the whole group. The Shapley value of a group is the sum of the Shapley values of each member in the group. It won't be the same as the SHAP value if you hadn't made dummy variables, but that's because you would have a different tree model.
