### ISSUE TITLE
Interpretation of the sum of shap values for a sample?

### ISSUE THREAD

**Issue by zmabzug** [shap/shap#168]
What is the interpretation of the sum of shap values for a single sample (+ the expected value term) in classification?

My understanding is that in TreeInterpreter, the sum of Saabas values is supposed to estimate the class probability for that sample, but that doesn't seem to be the case for Shap.

**Comment by slundberg** [comment]
It depends on your model. For sklearn random forests shap values (+
expected value) do sum to the probability because that is what the trees
output. But for XGBoost they sum to the margin output of the model, so
whatever output_margin=True would produce from the original model. The sums
will be the same a the saabas values.

**Comment by zmabzug** [comment]
Weird. I'm seeing the same expected value for both shap and saabas (they
call it a "bias") but different sums of the values (saabas adds up to the
probability, shap does not). I'm using sklearn random forest. Any idea what
could be causing this discrepancy?

I'm mobile-only for the next few days but can post my exact code when I get
computer access again.

**Comment by slundberg** [comment]
Hmm...I just ran a simple sanity check and the values did sum to the
probabilities for me, so please do share the example code when you get a
chance.
