### ISSUE TITLE
categorical features in LightGBM caused "could not convert string to float" in TreeExplainer

### ISSUE THREAD

**Issue by chrisadas** [shap/shap#170]
This works:
```
gbm = lgb.LGBMClassifier()
gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)])
explainer = shap.TreeExplainer(gbm)
```

This:
```
gbm = lgb.LGBMClassifier()
gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        categorical_feature=category_columns)
explainer = shap.TreeExplainer(gbm)
```

Caused this:
```
ValueError                                Traceback (most recent call last)
<ipython-input-53-6ed41ccbc5d7> in <module>()
----> 1 explainer = shap.TreeExplainer(gbm)
      2 # shap_values = explainer.shap_values(X_test)

~/.local/lib/python3.5/site-packages/shap/explainers/tree.py in __init__(self, model, **kwargs)
    101             self.model = model.booster_
    102             tree_info = self.model.dump_model()["tree_info"]
--> 103             self.trees = [Tree(e, scaling=len(tree_info)) for e in tree_info]
    104         elif str(type(model)).endswith("catboost.core.CatBoostRegressor'>"):
    105             self.model_type = "catboost"

~/.local/lib/python3.5/site-packages/shap/explainers/tree.py in <listcomp>(.0)
    101             self.model = model.booster_
    102             tree_info = self.model.dump_model()["tree_info"]
--> 103             self.trees = [Tree(e, scaling=len(tree_info)) for e in tree_info]
    104         elif str(type(model)).endswith("catboost.core.CatBoostRegressor'>"):
    105             self.model_type = "catboost"

~/.local/lib/python3.5/site-packages/shap/explainers/tree.py in __init__(self, tree, normalize, scaling)
    380                             self.children_default[vertex['split_index']] = self.children_right[vertex['split_index']]
    381                         self.features[vertex['split_index']] = vertex['split_feature']
--> 382                         self.thresholds[vertex['split_index']] = vertex['threshold']
    383                         self.values[vertex['split_index']] = [vertex['internal_value']]
    384                         self.node_sample_weight[vertex['split_index']] = vertex['internal_count']

ValueError: could not convert string to float: '1||3||4||5||7||13||14||16||20||24||33||35||38||40||42||47||51||53||54||55'
```

lightgbm 2.1.2  
shap 0.20.1  
Ubuntu 16.04

**Comment by slundberg** [comment]
Thanks for pointing this out! It looks like the model loading does not handle the categorical features right now. This model parsing is only needed for the interaction values so I moved it to be only done when computing interaction values (not regular SHAP values). See if that works for you.

**Comment by slundberg** [comment]
Tested and it seems to work for me.

**Comment by nchaly** [comment]
I'm trying to produce 'probability' as model output, and use lightgbm categorical variables... and I'm stuck

I think there is a slight problem with suppressing exceptions - [TreeExplainer 577](https://github.com/slundberg/shap/blob/463e71ac98637be58d8fce2a16ed42ed3cdbf0cc/shap/explainers/tree.py#L577) - the problem with 'probability' as model output, the other exception is raised - `'TreeEnsemble' object has no attribute 'values'`  - because `values` had not created due to categorical threshold issue.  

Can you please advise?


 Code: 

    explainer = shap.TreeExplainer(lgb_classifier,
                               model_output='probability',
                               feature_dependence='independent',
                               data=x_test
                              )

shap version='0.28.5'
lighgbm version='2.2.3'

**Comment by pradm007** [comment]
Any update on this? 
Reproducible with

shap version='0.35.0'
lighgbm version='2.3.1'

**Comment by R4ZZ3** [comment]
Same issue here:

shap version='0.35.0'
lighgbm version='2.3.1'

**Comment by slundberg** [comment]
@nchaly sorry I missed this. The issue is that CatBoost has SHAP integrated into their package to support log odds explanations, but they do not have the `feature_dependence="independent"` option. Since only the feature_dependence="independent" option supports probability output SHAP uses the _cext implementation inside SHAP. However, our internal C++ code does not yet support categorical feature splits. So...you can't have both right now until either we add support for categorical splits, or CatBoost adds support for probability outputs. I want to add categorical feature split support also for the sake of LightGBM, but it takes a significant update to the C++ code.
