### ISSUE TITLE
Image Explanations Viz disappear after initial render

### ISSUE THREAD

**Issue by vivekchettiar** [shap/shap#1733]
Transient issue, where the visualization initially renders and subsequently disappears.

**Comment by anusham1990** [comment]
![Viz bug snapshot](https://user-images.githubusercontent.com/12597369/105414234-38a71d00-5c05-11eb-959e-70ce8ca8fe45.PNG)

When calling the image_to_text visualization feature, output initially loads but disappears quickly and will not be visible when you try to click on the output caption words. After saving the file and reopening, results appear but disappear after keeping the file open for a while. 

This bug was found while trying to use this feature in Visual Studio. Couldn't however test the same in Jupyter Lab to verify if this is only a VS issue or an issue across all notebooks no matter which tool is used to open it. 

Feature enhancement: To be able to see all caption words results at once instead of one word at a time.
