### ISSUE TITLE
Using XGboost with Kernel SHAP

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#179]
Hi,

Can we use xgboost with Kernel SHAP?

Thanks

**Comment by slundberg** [comment]
Yes you can, you just need to define a prediction function to pass to KernelExplainer. Though of course it will be a worse and much slower estimate than what TreeExplainer would give.

**Comment by DiliSR** [comment]
It give an error as booster object not callable. The model is the model that you have used in medical dataset.

**Comment by slundberg** [comment]
Right that's because you need to pass a function to KernelExplainer that accepts a numpy array and outputs a vector of model predictions.

**Comment by DiliSR** [comment]
Could you please give an example for your medical scenario?

**Comment by DiliSR** [comment]
I have tried using
`k=model.predict(xgb_test)`
`explainer_xgk = shap.KernelExplainer(k,med)`

it givens an error as Provided model function fails when applied to the provided data set.

Could you please help me?

**Comment by DiliSR** [comment]
Hi, 

Do you have any example that you have generate the SHAP values from Tree explainer and Kernel explainer using the same model (Xgboost) 

Please help me on this.

**Comment by slundberg** [comment]
@Dilini-Sewwandi-Rajapaksha I am sorry this is causing you trouble. Unfortunately I often can't respond quickly to every issue on here since this is an open source project that I don't maintain as a full time job.

The problem with what you posted is something specific to Python, not SHAP. `k` as you have defined it is not a function but the output of the model.predict function. `k = model.predict` should be what you want. I don't have an example right now of using KernelExplainer for XGBoost, though I expect to as some point soon (couple weeks) as part of some benchmark tests I'll be pushing.

**Comment by DiliSR** [comment]
Thank you. After you have done with that please send me the link .

**Comment by noleto** [comment]
Might be helpful?

=> How to use XGBoost with Kernel SHAP and Tree SHAP (using the same model)
https://gist.github.com/noleto/05dfa4a691ebbc8816c035b86d2d00d4

**Comment by DiliSR** [comment]
Thank you very much @noleto

**Comment by slundberg** [comment]
thanks!

**Comment by mayer79** [comment]
@noleto: sweet workaround, thx. Would prefer of course if KernelExplainer would natively deal with pandas dfs.

**Comment by ajoules** [comment]
Hi, 

Thank you for the above discussion - I just wanted to agree with Mayer79 as it would be great if one day we could feed the model predictions into Kernel SHAP (instead of the prediction function) as this would allow us to explain models built outside of Python.

Thank you Scott for all of your work on SHAP - the package is a game changer and myself and my colleagues are extremely grateful!

**Comment by detrin** [comment]
Since @slundberg made it clear how to work with the KernelExplainer and there is provided gist example from @noleto I think we can close the issue for now @thatlittleboy
