### ISSUE TITLE
Weird KernelExplainer behavior on Image Classification Network

### ISSUE THREAD

**Issue by NTNguyen13** [shap/shap#180]
Hi,

I'm using SHAP to explain the prediction of an Image Classification Network. I follow[ this notebook](https://github.com/slundberg/shap/blob/master/notebooks/kernel_explainer/ImageNet%20VGG16%20Model%20with%20Keras.ipynb).

However, when I tried to use it to explain some output, the SHAP values return on the superpixel is sometimes weird, it can either be empty or the top prediction have less SHAP values than the second or the third. In a lot of cases, the area of the image with high SHAP values even falls on the empty region of the image. 

Example:
Top prediction has less empty value:
![a549--eztt0lbzsdi6wvpt3mjbkpqakuxge0fa_20180329_cell6_shap](https://user-images.githubusercontent.com/39985901/43189717-3591cf08-9032-11e8-892b-0839d5f6fd69.png)
Most of the high-SHAP-value of top prediction is on empty region, contrast with the third one
![mcf7--xbfoes6kdjggrvcnuiv49wzemppldm5j_20180329_cell17_shap](https://user-images.githubusercontent.com/39985901/43189951-db9bfdf6-9032-11e8-8408-708fa2f9048e.png)

Can you give me an idea of how this phenomenon happen? Thank you

Edit 1: One more thing: about the 
```
explainer = shap.KernelExplainer(f, np.zeros((1, 50)))
shap_values = explainer.shap_values(np.ones((1, 50)), nsamples=1000) 
```
is those functions needed to be updated for every images or it will run for all the dataset specified in `nsamples`? I'm going to apply a forloop to explain multiple images each iteration

**Comment by slundberg** [comment]
Hmm. As a sanity check can you confirm the SHAP values + explainer.expected_value sum to the output of the model for each prediction? And the that the output of f is larger for the top prediction than the others? Also since your images have a clear black background, it might make more sense to set missing super pixels to black rather than the mean of the image. That would prevent the black regions from getting importance for being black. It could be that by changing the black regions to some other color it might have a big effect on the model.

**Comment by NTNguyen13** [comment]
Hi, it turns out that the input was not preprocessed the same way with training, lead to wrong calculation of SHAP values.

I also set the `background = 0` in the mask_image, and it works better now. Thank you

**Comment by slundberg** [comment]
Great! One other thing to try if run into future issues is to play with the
`l1_reg` parameter and set it to `0` instead of `auto`. This turns off AIC
feature selection.
