### ISSUE TITLE
Python Version of Tree SHAP gives ZeroDivisionError 

### ISSUE THREAD

**Issue by TGalaxy** [shap/shap#183]
Hello,

I am trying to run the python tree shap but ran into some error

x = np.ones(X.shape[1])
TreeExplainer(model).shap_values(x)

Also, is there any simple examples to help understand how exactly Tree Shap (algorithm 2) work? For example, a walk through of the algorithm through the "and_model" would be extremely helpful. 

Thanks!

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-16-c85c77a55c0e> in <module>()
      1 x = np.ones(X.shape[1])
----> 2 TreeExplainer(model).shap_values(x)

<ipython-input-5-c6b4b1fa0394> in shap_values(self, X, **kwargs)
     29             x_missing = np.zeros(X.shape[0], dtype=np.bool)
     30             for t in self.trees:
---> 31                 self.tree_shap(t, X, x_missing, phi)
     32             phi /= len(self.trees)
     33         elif len(X.shape) == 2:

<ipython-input-5-c6b4b1fa0394> in tree_shap(self, tree, x, x_missing, phi, condition, condition_feature)
     52             tree.thresholds, tree.values, tree.node_sample_weight,
     53             x, x_missing, phi, 0, 0, self.feature_indexes, self.zero_fractions, self.one_fractions, self.pweights,
---> 54             1, 1, -1, condition, condition_feature, 1
     55         )
     56 

ZeroDivisionError: division by zero

**Comment by slundberg** [comment]
Hmm. How do you train the model? Just so I can reproduce it. I should give a walk through, I'll see what I can do.

**Comment by TGalaxy** [comment]
Thanks Scott! I didn't modify the notebook so it's strange. I'm wondering if the training gives some edge tree cases therefore lead to zero division? 

Look forward to the algorithm 2 walk through!

**Comment by ferlocar** [comment]
Not sure if it's related, but I'm also getting a ZeroDivisionError with the KernelExplainer. I was testing the package for the first time, and I wanted to know how well it approximates the true Shapley value as I increase the number of features in a very simple "model". Here's the code:

`import numpy as np
import shap


def predict(x):
    return np.sum(x, axis=1).astype(float)/x.shape[1] > 0.5


feature_size = 10
explainer = shap.KernelExplainer(predict, np.zeros((1, feature_size)), link="logit")
shap_values = explainer.shap_values(np.ones((1, feature_size)))`

As you can see, the "model" consists of a very simple function that receives a bunch of binary features and predicts one if more than half of the features are set to one and zero otherwise. However, I get the following error:
_________________________________________________________________________________________
Traceback (most recent call last):
  File "C:/Users/ferlo/OneDrive/Documents/NYU/Machine Learning/Project/data_value/shap_mine_test2.py", line 12, in <module>
    shap_values = explainer.shap_values(np.ones((1, feature_size)))
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\shap\explainers\kernel.py", line 203, in shap_values
    explanations.append(self.explain(data, **kwargs))
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\shap\explainers\kernel.py", line 366, in explain
    vphi, vphi_var = self.solve(self.nsamples / self.max_samples, d)
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\shap\explainers\kernel.py", line 446, in solve
    eyAdj = self.linkfv(self.ey[:, dim]) - self.link.f(self.fnull[dim])
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\numpy\lib\function_base.py", line 2218, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\numpy\lib\function_base.py", line 2287, in _vectorize_call
    outputs = ufunc(*inputs)
  File "C:\Users\ferlo\Anaconda3\lib\site-packages\iml\links.py", line 28, in f
    return np.log(x/(1-x))
ZeroDivisionError: float division by zero
___________________________________________________________________________________________
I would really appreciate any hint on what am I doing wrong. Thanks in advance for any help you may provide me!

**Comment by ferlocar** [comment]
Just in case, I found that the error occurs whenever the prediction is exactly zero. So, to my understanding, the current implementation would not work for binary predictors (but it would work for predictors that return a probability).

**Comment by slundberg** [comment]
@ferlocar It is because you are using the logit link function. That is undefined when the probability is 1 or 0 since it would imply infinite log-odds. Just take out the `link="logit"` option and you should be fine. That option causes the model to try and explain in the log-odds space as opposed to the orignal model output space.

**Comment by ferlocar** [comment]
Awesome, works like a charm now! Thanks a lot!
