### ISSUE TITLE
missing value treatment  - model trained with xgboost 

### ISSUE THREAD

**Issue by ybeybe** [shap/shap#186]
When using xgboost to train the model, the algorithm knows to treat missing value differently by assigning them to a different branch at splitting. 

My question is, how does SHAP handle missing value? if I imputate missing value with a number before hand (say, 99999), I can tell xgboost this by configuring missing_value = 99999. If I then use SHAP to explain the model trained, will it cause problem since SHAP is using a regression based model in approximation to get Shapley value? 

I just started studying SHAP. Please point out if I'm missing something here. Thanks!

**Comment by ybeybe** [comment]
sorry I missed the point that tree shap is calculated differently as in 
"Consistent Individualized Feature Attribution for Tree Ensembles". I'll go study this first. Thanks.

**Comment by slundberg** [comment]
SHAP treats variables as missing by holding them out of a conditional expectation of the model output. This is different than a 'missing' value in XGBoost, since a 'missing' value in XGBoost might not be missing at random and so still convey information about the output. The "simple" algorithm in the Tree SHAP paper should give an intuitive idea of this (Tree SHAP is just a faster version of that).

**Comment by ybeybe** [comment]
Thank you @slundberg ! This is helpful.

**Comment by slundberg** [comment]
Great!
