### ISSUE TITLE
Error when attempting to create bar-plot for multiclass classification with Scikit-learn RandomForestClassifier

### ISSUE THREAD

**Issue by artokarj** [shap/shap#1865]
Following code produces Index-error:

import numpy as np
import pandas as pd

df = pd.DataFrame({'count': {0: 0, 1: 2, 2: 3, 3: 0, 4: 0, 5: 2, 6: 1, 7: 0, 8: 2, 9: 3},
 'month': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
 'day_of_week': {0: 3, 1: 4, 2: 5, 3: 6, 4: 0, 5: 1, 6: 2, 7: 3, 8: 4, 9: 5}})

X_train = df.drop(['count'], axis=1)
y_train = df['count']

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state=42, min_samples_leaf=1, n_estimators=10, oob_score=False, max_features=0.5, n_jobs=-1)
classifier.fit(X_train, y_train)
print('validation_score:', round(classifier.score(X_train, y_train), 2))

import shap
shap.initjs()

explainer = shap.TreeExplainer(classifier, data=X_train)
shap_values = explainer(X_train)
shap.plots.bar(shap_values)

> IndexError                                Traceback (most recent call last)
> <ipython-input-164-2def1732d8f3> in <module>
>       1 explainer = shap.TreeExplainer(classifier, data=X_train)
>       2 shap_values = explainer(X_train)
> ----> 3 shap.plots.bar(shap_values)
> 
> ~\Anaconda3\lib\site-packages\shap\plots\_bar.py in bar(shap_values, max_display, order, clustering, clustering_cutoff, merge_cohorts, show_data, show)
>     157     for pos,inds in enumerate(orig_inds):
>     158         if len(inds) == 1:
> --> 159             feature_names_new.append(feature_names[inds[0]])
>     160         else:
>     161             full_print = " + ".join([feature_names[i] for i in inds])
> 
> IndexError: list index out of range
>

**Comment by asuccurro** [comment]
Hey @artokarj,

check also this issue here: https://github.com/slundberg/shap/issues/1906

With these two different objects:

`shap_obj = explainer(X1_train)`
`shap_values = explainer.shap_values(X1_train)`

You can get a stacked barplot with all classes:

`shap.summary_plot(shap_values, X1_train, class_names=model.classes_)`

Or individual bar plots for each class, e.g. for the first (i=0):

`shap.plots.bar(shap_obj[:, :, 0])`

Cheers,
Antonella
