### ISSUE TITLE
heuristic for displaying the most important features in the explanation to the user?

### ISSUE THREAD

**Issue by ihadanny** [shap/shap#190]
Hey,
I'm using SHAP and getting a vector of contributions per feature as an explanation to a single instance. Now I would like to show to the user only the most important features that contributed to the positive direction (drove the score up). I thought about the following heuristics:

1. Sum all positive contribs, display the features that contributed more than x% of the total sum (e.g. more than 10%).
2. Find the largest positive contrib, display it and all other features that are at least x% of it.
3. Compare the contribs to the bias, display positive features that are at least x% of the bias

Which would be more reasonable? Note that I would like the method to be generic, it should easily migrate between explanation models with ~50 features and other explanation models with ~10 features.

thanks!

**Comment by slundberg** [comment]
Good question. I am not sure if there is a "right" answer here. A few things that come to mind:
1. You must assume there is a cost to showing the user a feature (time, attention span, etc), otherwise you would show them all of them.
2. There is a value that the user gets by learning about the importance of a feature.

In theory each of (1) and (2) could be given a numerical value/cost and then you could optimize that. The issue for generality is that (2) in particular is likely to depend on the application and so may be hard to specify without knowing how the user is using the explanation.

I don't have a strong opinion about your proposals, they all seem reasonable. But if I were evaluating them I would sit down and think about how they relate to (1) and (2).
