### ISSUE TITLE
Explain CNN for time series classification - possible? 

### ISSUE THREAD

**Issue by CCapinha** [shap/shap#1920]
Hi,
thank you for this great work!
Is it possible to apply SHAP for explaining CNN models applied for multivariate time series classification (i.e., i CNN using 3D input - x samples x timesteps x features)?

I found some discussion and examples for RNN/LSTM architectures, but so far could not find an example for CNN. Do you know if this is possible? Any examples (from here or elsewhere) would also be greatly appreciated.
Many thanks in advance.

**Comment by ekrell** [comment]
Also wondering about the use of SHAP for 3D CNN. I have been working with ParititonShap for satellite images: both RGB and 13-band multispectral.

From my understanding, it is not really considering the channels in a 3D way:
1. When generating the clusters, the depth (z) is always the last to be split.
2. I have been printing the masks -> they are of shape (height, width, channels) but all channels are identical. 
3. 2. Removing features is performed with OpenCV's blur or inpainting. So, for example, we can't say we want a (3x3x3) blur. 
4. When I check the output SHAP values, there are values for each [row, col, channel] but identical values across the channels for a given pixel. 

The partition can be provided as an input instead of generated within the library, but I am not sure that even a partition into cubes will be sufficient since the blurring is 2D. I could be totally wrong, this is just my understanding from exploring the code. Hopefully someone has some insights on working with 3D.

**Comment by ekrell** [comment]
I have spent more time studying the code. I think there is potential for 3D CNN support. Hopefully a dev can weigh in, since I could be totally off. 

1. Partitions are created from the image's row, col, bands as I described. Band-wise splits are at the very bottom of the partition tree.
2. The set of masks is generated based on the partition tree. The topmost masks divide the image in half (like the partitions) such that the base case of the recursion is a (row, col, band). So masks do include band-wise splits.
3. How deep our masks go down the partition tree is determined by the `max_evals`. So first it checks the half-split, then four-way, .... down to the channel-wise splits. 
4. But unless you put a really huge `max_splits` and are willing to wait a while -> the masks will never get to that level of granularity. 

Thus:
- PartitionShap can use band-wise masks
- But the partition scheme is such that we are unlikely to use band-granular masks
- But we can specify our own partition scheme instead of relying on the built-in. Pretty sure it is an optional argument. 
- I need to think more about the impact of 2D blurring on band-wise SHAP...

**Comment by ekrell** [comment]
Check this PR: https://github.com/slundberg/shap/pull/1944

I only added a channel-first partition scheme and a way to view the channel-wise SHAP values. But you can check what I did and see if it is at all useful to use or build off of. I would be very interested if you have success with 3D CNN SHAP values!

**Comment by CCapinha** [comment]
Many thanks, Evan. It's a pretty great addition already! Will send you feedback asap.
