### ISSUE TITLE
SHAP values showing f(x) as negative value whereas the data and the predictions are categorical

### ISSUE THREAD

**Issue by jgdpsingh** [shap/shap#1926]
Kindly help in explaining the SHAP value chart. My dataset is entirely categorical because it's a survey data and I am using Catboost classifier and the predictions are binary as well. Whereaas the the f(x) is -0.516. If I am not wrong, f(x) is the output. So, how come the output is taken as negative when the model predictions are in binary? How do you explain the SHAP values as shown in the picture?

![survey](https://user-images.githubusercontent.com/43772996/113828626-413dd700-97a2-11eb-88cd-ae51cf718da1.jpg)

**Comment by jgdpsingh** [comment]
Also, when using beeswarm or summary plot, I am getting grey color plots instead of colored plots. I am using Google Colab for running the code.

![image](https://user-images.githubusercontent.com/43772996/113830493-4c920200-97a4-11eb-9a98-24f4f56a28f4.png)

**Comment by abeboparebop** [comment]
Your first issue is most likely because SHAP defaults to showing the average effect on the logit (log-odds), which can range from negative infinity to positive infinity. If you specify `link="logit"` when you define the explainer, then the force plots will be in probability space rather than logit space.

And I believe the second plot is in greyscale because these are unordered categorical features, so it doesn't make sense to color them by "feature value."
