### ISSUE TITLE
Standard Errors in Kernel Explainer

### ISSUE THREAD

**Issue by ferlocar** [shap/shap#194]
Hello Scott,

Thanks again for your awesome package. I'm using the KernelExplainer, and I was wondering whether it's currently possible to recover the standard errors of the coefficients that are estimated using weighted least squares. Thanks in advance for any help you may provide!

**Comment by slundberg** [comment]
We could, but the problem is that we have eliminated one variable due to the constraint that the values sum to the output. That elimination transformation would need to be accounted for when mapping the standard errors backward to the original inputs. I don't know offhand how to do that, but if anyone has a suggestion after looking at the solve method please speak up.
