### ISSUE TITLE
AttributeError: module 'shap' has no attribute 'plots'

### ISSUE THREAD

**Issue by barber5** [shap/shap#1975]
I'm working with the introductory documentation

The following code works for an appropriate selection of `model` and `X`

```
explainer = shap.Explainer(model)
shap_values = explainer(X)
```

However, this code does not
```
explainer = shap.Explainer(model)
shap_values = explainer(X)

# visualize the first prediction's explanation
shap.plots.waterfall(shap_values[0])
```

I'm using miniconda with conda 4.10.1 with a python 3.8.8 environment on macOS Big Sur v11.2.3

packages installed are
certifi==2020.12.5
click==7.1.2
cloudpickle==1.6.0
Flask==1.1.2
Flask-Cors==3.0.10
itsdangerous==1.1.0
Jinja2==2.11.3
joblib==1.0.1
llvmlite==0.36.0
MarkupSafe==1.1.1
numba==0.53.1
numpy==1.20.2
pandas==1.2.4
python-dateutil==2.8.1
pytz==2021.1
scikit-learn==0.24.2
scipy==1.6.3
shap==0.39.0
six==1.15.0
slicer==0.0.7
threadpoolctl==2.1.0
tqdm==4.60.0
treeinterpreter==0.2.3
Werkzeug==1.0.1

Any suggestions would be appreciated

**Comment by thomelane** [comment]
I also had this issue, but found the function at `shap.waterfall_plot`.

**Comment by cmougan** [comment]
Why was this closed? 
Is it a version problem?

**Comment by fratamico** [comment]
This worked for me:

`from shap.plots import *`

then can just use the functions as so:
`waterfall(shap_values[0])`

(shap version 0.40.0)

**Comment by klieret** [comment]
Could this be an issue with not having `matplotlib` installed? I noticed that it's not listed in the conda package list at the top of this thread. And if you look at [`__init__.py`](https://github.com/slundberg/shap/blob/master/shap/__init__.py), a lot of imports will only happen if `matplotlib` is installed.

Installing `matplotlib` resolved the issue described in this issue for me.

The real bug is therefore that no meaningful warning is issued when attempting to access `shap.plots`.

I will prepare a PR for this.

**Comment by Jacck** [comment]
If I have a coalitions values already, how can I use SHAP?

**Comment by jiahang171013** [comment]
I also had this issue, does anyone has good suggestions？:(
