### ISSUE TITLE
Simple Questions About Interaction Examples

### ISSUE THREAD

**Issue by BrianMiner** [shap/shap#198]
In the example notebook https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Basic%20SHAP%20Interaction%20Value%20Example%20in%20XGBoost.ipynb

I. The last plot is as follows. I am confused as to why the dots are the same color for a given value of Feature 2. I assumed that for each value of feature 2, one dot would be red and one blue based on the value of feature 3?

![image](https://user-images.githubusercontent.com/8807554/43585891-344d2982-9634-11e8-967e-b26aa4ae3f6a.png)

II. In the notebook https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/NHANES%20I%20Survival%20Model.ipynb

In this image, is the correct interpretation really that for females, being younger actually increases the risk of death, but for males, being younger lowers the risk (which would be expected for both genders I would  think).

![image](https://user-images.githubusercontent.com/8807554/43587087-607004d2-9637-11e8-86e7-7ee19ca88c3b.png)

**Comment by slundberg** [comment]
Good questions. For the first one I think that plot was run a while back and the color is just a redundant encoding of feature 2's value (since there is no color bar saying the colors are for another feature). This default behavior is different now so I should probably re-run the notebook.

If you look at the marginal effect of age on both genders it does lower the risk for everyone, but the effect you are seeing here is from interaction effects involving age and sex. Since the marginal effect of age has already been taken are of, we are just looking at the interactions, which seem to imply that being young has a slightly larger benefit if you are male than if you are female (potentially because being old is just worse for men, not that being young is better).
