### ISSUE TITLE
alternative `shap.visualize`

### ISSUE THREAD

**Issue by kodonnell** [shap/shap#20]
I think it looks awesome, but it did somewhat confuse me, e.g.:

- I got directions wrong. The things that increase the prediction are on the 'negative' side of the graph. (I think.)
- I wasn't sure if the arrows were overlapping or stacked. Either way, it's hard to compare multiple variables. (If it's interactive, then that's OK, but it's of less use for e.g. a printed copy, or in a PPT).

So possibly you could provide different plot styles, as per `summary_plot`. The obvious example is a horizontal bar chart, though you can do prettier things with e.g. scatters. That said, these will be less pretty when there are many features.

Just a thought - of course, we can always do our own. (I am quite happy with a printed list!)

**Comment by slundberg** [comment]
Fair suggestion. The reason things that increase a prediction are on the left side pushing right is that otherwise things will go off the plot for large predictions (if we want to keep the baseline in view)

If there are useful and non-trivial alternatives I would be happy to include them to help make the SHAP values easier to communicate.

**Comment by kodonnell** [comment]
Great. I'll have a think, and forward this on to some others interested. We could do some really awesome d3 visualizations, though that'd be more work. Will leave this open if someone else wants to pick it up for a PR.

**Comment by ShaikhIrshadSij** [comment]
Is this visualizations done in this is done by D3.js in backend?
