### ISSUE TITLE
Question on "Understanding Tree Shap for Simple Models"

### ISSUE THREAD

**Issue by BrianMiner** [shap/shap#203]
Can you explain the logic of say, the Two feature AND example?
I am unsure why this looks as expected. How do you traverse the tree to see that the impacts of each feature is the same and that the values match the SHAP values?

**Comment by slundberg** [comment]
Well it is easiest to see by ignoring the tree structure and just thinking about what function the tree is defining. It is just an AND function between two binary features. Since both inputs to an AND function have equal responsibility for the output (and the background dataset is equally distributed), they should get assigned equal credit. So this gives us one constraint that we "expect" (equal credit).

Second we know that SHAP values are supposed to capture the difference between the expected model output and the current model output. So for the two feature AND example the expected output is 1/4 and the current output is 1, so the SHAP values should sum to 0.75.

Given both those constraints we know the values must be 0.75 / 2 or 0.375.

**Comment by BrianMiner** [comment]
Ah thats all there is huh? OK I was trying to reconcile the AND case with x = the zero vector. The output was 0 because of X1 <0.5. But the point is even though if you run the zero vector through the tree, you output '1' after the first split and never even evaluate X0, the values need to be the same because we consider all possible orderings of the features.... do i have that right?

On 08/08/2018 11:42 AM, Scott Lundberg wrote:

Well it is easiest to see by ignoring the tree structure and just thinking about what function the tree is defining. It is just an AND function between two binary features. Since both inputs to an AND function have equal responsibility for the output (and the background dataset is equally distributed), they should get assigned equal credit. So this gives us one constraint that we "expect" (equal credit).

Second we know that SHAP values are supposed to capture the difference between the expected model output and the current model output. So for the two feature AND example the expected output is 1/4 and the current output is 1, so the SHAP values should sum to 0.75.

Given both those constraints we know the values must be 0.75 / 2 or 0.375.

**Comment by slundberg** [comment]
That's right. The problem is that I could write the tree to start with X1
or X0 and it would define the same AND function. So if I give different
attributions depending on the order then something about my attributions
does not depend on the actual function but just on an arbitrary
implementation detail. Depending on arbitrary implementation details leads
inevitably to inconsistencies like the one shown in the arXiv paper.
