### ISSUE TITLE
Warning: unrecognized nn.Module: CELU

### ISSUE THREAD

**Issue by ezedonovan** [shap/shap#2082]
Hi,
First wanted to thank you for this great tool.
I'm starting to use the repo with the model I'm currently using for my research and I'm getting the warning for using CELU activation functions.

`Warning: unrecognized nn.Module: CELU`

How concerned should I be about this?
Could you give me some advice/hint on some possible implications behind the results I get?

Thank you very much in advance.
Ezequiel

**Comment by guyj-s1** [comment]
@ezedonovan I got similar warnings with my deep learning model:
`Warning: unrecognized nn.Module: LogSoftmax`
`Warning: unrecognized nn.Module: LayerNorm`
`Warning: unrecognized nn.Module: GELU`

and was wondering if because of this, the contribution of those components don't get propagated back to the inputs as intended. If this is so, the calculations of shap values complete, but they are incorrect?

Cheers,
Guy
