### ISSUE TITLE
Shap.TreeExplainer for CatboostClassifier Segmentation Fault

### ISSUE THREAD

**Issue by lperret-prevision** [shap/shap#2085]
Hi team,

I observed a segmentation fault during the instanciation of a shap.TreeExplainer for a catboost.CatboostClassifier when depth >= 7 and classes_count >= 3.

```
from sklearn import datasets
import catboost
import shap

iris = datasets.load_iris()
X = iris.data
y = iris.target

classes_count = len(set(y))
depth = 7

model = catboost.CatBoostClassifier(depth=depth, classes_count=classes_count, verbose=False)
model.fit(X, y)
```
 
here we have a segmentation fault during the call to the
function compute_expectations written in shap/cext/tree_shap.h
I observed the bug only for depth >= 7 and for catboost.CatBoostClassifier with classes_count >= 3,
not for catboost.CatBoostRegressor
print("instanciate shap.TreeExplainer for catboost.CatBoostClassifier model with"\
      "depth = {} and classes_count = {}".format(depth, classes_count))

`explainer = shap.TreeExplainer(model)`

`(test_catboost_2) ➜  engine git:(fix/catboost-explainer) ✗ python train_and_explain_tiny_multiclassification_catboost.py
IPython could not be loaded!
instanciate shap.TreeExplainer for catboost.CatBoostClassifier model withdepth = 7 and classes_count = 3
[1]    18975 segmentation fault (core dumped)  python train_and_explain_tiny_multiclassification_catboost.py
`

Please let me know if you need any other information.

regards

**Comment by TushSK** [comment]
Hi, even i have been facing the memory segmentation error. Though the error is not so frequent in nature, it tends to occur on random intervals. Specifically, it occurs while calling the TreeExplainer method. 
My classes are greater than 5 (7 in number)
Dataset size is merely ~30-40k in row size.
Using catboost classifier.
Using Azure Databricks platform for the training and predictions.

Am using SHAPASH library, which internally uses the SHAP explainer to provide weightage outputs.
The frustrating part is, it works absolutely fine in some instances, and sometimes it fails with the memory segmentation error.

Also, had a word with MS guys if anything to do with the Databricks part, which turned to be negative. 
The cause was found to be at specific location  "shap.TreeExplainer(model)" which runs in backend to perform the action.
