### ISSUE TITLE
Non-full backward hook with shap.DeepExplainer + PyTorch

### ISSUE THREAD

**Issue by mlpotter** [shap/shap#2124]
Error: `Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.`

PyTorch Model: 
```
class aggregation_model(nn.Module):
    def __init__(self,fit_iterations,n_features):
        super(aggregation_model,self).__init__()
        self.models = nn.ModuleDict()
        self.fit_iterations = fit_iterations
        self.n_features = n_features

        for iter_ in tqdm(np.arange(fit_iterations)):
            model_weights = torch.load("model_iterations/model_iteration_cat_{:d}.pt".format(iter_))
            self.models["model_iterations/model_iteration_cat_{:d}".format(iter_)] = nn.Sequential(nn.Linear(n_features,1),nn.Sigmoid())
            self.models["model_iterations/model_iteration_cat_{:d}".format(iter_)].load_state_dict(model_weights)

    print("Initialized Aggregation Model")
    def forward(self, x):
        model_iteration_predictions_open = []#torch.zeros((x.shape[0],1),requires_grad=False)
        for iter_ in np.arange(self.fit_iterations):
            model_iteration_predictions_open.append(self.models["model_iterations/model_iteration_cat_{:d}".format(iter_)](x).view(-1,1))
         
        model_iteration_mean = torch.cat(model_iteration_predictions_open,dim=1).mean(1).unsqueeze(1)
        return model_iteration_mean 

model = aggregation_model(fit_iterations,27)
e = shap.DeepExplainer(model,X_pytorch)
shap_values = e.shap_values(X_pytorch)
```

Versions: PyTorch 1.8.0 , Shap 0.39.0

I have seen similar posts in the closed / open section but no resolution to this issue... Is there a way to rewrite the PyTorch model to avoid this warning? Does this warning mean that it is only using 1 of the models in the nn.Module() function for the shap value calculation? 

Any suggestions would help a lot.

**Comment by scottgigante-immunai** [comment]
+1, would love to see an answer here!

**Comment by noxthot** [comment]
You can not avoid this warning without rewriting `shap`, since `shap` is using a deprecated `torch` method in its code. Prior the deprecation of `register_full_backward_hook` in `torch`, it simply did not show a warning at all while having the same (probably erroneous) behavior. `torch` improved the backward hook and gave the method a new name `register_module_full_backward_hook` in [this](https://github.com/pytorch/pytorch/pull/46163) pull request.

I made a [pull request](https://github.com/shap/shap/pull/3259) which is now using `register_module_full_backward_hook`.

Regarding your question: `shap` does not seem to support every possible model configuration and it does not seem to always give a warning in that case. If you want to be more sure, clone the shap `repository`, follow the installation guide in `CONTRIBUTING.md`, add a test in `test_deep.py` by copying `test_pytorch_single_output()` and replacing the `class Net(nn.module)` with your own network structure. Run the test by calling `pytest ./tests/explainers/test_deep.py` and see if it succeeds.
