### ISSUE TITLE
Categorical features in LGBM cause failure when using __call__ method of the TreeExplainer

### ISSUE THREAD

**Issue by mlisovyi** [shap/shap#2144]
I bumped into the problem that when using the `__call__` method of the `TreeExplainer` on a LGBM model that uses categorical features, one gets an error like _"ValueError: could not convert string to float:"_.

The origin seem to be [this line](https://github.com/slundberg/shap/blob/89855e03d7e92ba0d2ec463c0505878f718664e3/shap/explainers/_tree.py#L206), i.e. one converts the input DataFrame into a numpy array and thus the info about categorical fetures (when those are defined by the types of features) get's lost, when the data are passed to the `shap_values` method [here](https://github.com/slundberg/shap/blob/89855e03d7e92ba0d2ec463c0505878f718664e3/shap/explainers/_tree.py#L211). The `shap_values` method itself works fine when the complete DataFrame is passed as input. 

Below is a minimal reproducible example:
```python
import lightgbm as lgb
import shap

# train XGBoost model
X, y = shap.datasets.adult()
# add a dummy categorical variable
X["Categorical"] = "A"
X["Categorical"] = X["Categorical"].astype("category")
# train a LGBM model with a categorical feature in the data
model = lgb.LGBMClassifier().fit(X, y)

# compute SHAP values
explainer = shap.TreeExplainer(model)
# this works
_ = explainer.shap_values(X.head(100))
# this fails
_ = explainer(X.head(100))
```

My setup:
python 3.8
lightgbm 3.2.1
shap 0.39.0

**Comment by ibobak** [comment]
I have the same issue with exactly the same version of SHAP and lightgbm.  
I've made a patch like this (version 0.39.0)
```
    def __call__(self, X, y=None, interactions=False, check_additivity=True):

        if safe_isinstance(X, "pandas.core.frame.DataFrame"):
            feature_names = list(X.columns)
            # -------------------------------------------------------------------
            # Ihor Bobak:  keep the reference for original DataFrame for lightgbm
            if self.model.model_type == "lightgbm":
                X_original = X
            # -------------------------------------------------------------------
            X = X.values
        else:
            feature_names = getattr(self, "data_feature_names", None)

        if not interactions:
            # -----------------------------------------------------------
            # Ihor Bobak: fix the X to make so that LightGBM works fine
            v = self.shap_values(X_original if self.model.model_type == "lightgbm" else X, y=y, from_call=True, check_additivity=check_additivity)
            # -----------------------------------------------------------
            output_shape = tuple()
            if type(v) is list:
                output_shape = (len(v),)
                v = np.stack(v, axis=-1) # put outputs at the end

            # the explanation object expects an expected value for each row
            if hasattr(self.expected_value, "__len__"):
                ev_tiled = np.tile(self.expected_value, (v.shape[0],1))
            else:
                ev_tiled = np.tile(self.expected_value, v.shape[0])

            e = Explanation(v, base_values=ev_tiled, data=X, feature_names=feature_names)
        else:
            v = self.shap_interaction_values(X)
            e = Explanation(v, base_values=self.expected_value, data=X, feature_names=feature_names, interaction_order=2)
        return e
```

**Comment by ibobak** [comment]
I've made a pull request that fixed this problem.  Watch for newer versions (if authors will accept it, of course)

**Comment by Npaffen** [comment]
Still wondering if you really need `output_shape = (len(v),)` seems that you define but never use it, correct?

**Comment by LawrenceXH** [comment]
Got the same problem when i use shap to analysis my lightgbm model with categories feature,wondering if it will be fixed?

**Comment by LawrenceXH** [comment]
i tried this way to create a shap values object by myself and it works for me

> import shap
shap.initjs()
explainer = shap.TreeExplainer(gbm)
shap_values = explainer.shap_values(X_test)
#this can't work when features has category because it will turn X_test to an ndarray which not support category in pandas
#and raise could not convert to string to float error
#i tried this way to create a shap values object by myself and it works for me
# shap_values2 = explainer(X_test) 
#根据源码自己构建Explanation对象
shap_values2 = shap._explanation.Explanation(shap_values)
shap_values2.base_values  = np.mean(y_train)
shap_values2.data  = X_test.values
shap_values2.feature_names = np.array(list(X_test.columns))
# shap_values2.output_names = np.array(['y'])

# shap.plots.bar(shap_values2[1], show_data=True)
shap.plots.waterfall(shap_values2[300], max_display=20, show=True)

**Comment by LawrenceXH** [comment]
#this can't work when features has category because it will turn X_test to an ndarray which not support category in pandas
#and raise could not convert to string to float error
#i tried this way to create a shap values object by myself and it works for me
#shap_values2 = explainer(X_test) 
#根据源码自己构建Explanation对象
> import shap
shap.initjs()
explainer = shap.TreeExplainer(gbm)
shap_values = explainer.shap_values(X_test)
shap_values2 = shap._explanation.Explanation(shap_values)
shap_values2.base_values  = np.mean(y_train)
shap_values2.data  = X_test.values
shap_values2.feature_names = np.array(list(X_test.columns))
shap.plots.waterfall(shap_values2[300], max_display=20, show=True)
