### ISSUE TITLE
Multiclass example & MNIST

### ISSUE THREAD

**Issue by adebayoj** [shap/shap#22]
HI, 

Do you happen to have an example for the multi-class setting? In your paper, you had an example on MNIST, but couldn't find an MNIST example as one of your notebooks. The key question here is whether to explain each output dimension separately or in a combined manner? 

Thanks!

**Comment by slundberg** [comment]
You can do it in a combined manner so you don't have to rerun the
estimates...I'll work on posting an example here.

**Comment by adebayoj** [comment]
Thanks for the quick reply. How soon should I expect the example? I am sure you are busy, if you describe how to explain for the multi-class setting, I can apply it to my case in the mean time.

**Comment by slundberg** [comment]
It might be a bit given some upcoming deadlines. In the current
non-multi-class example the model function outputs a numpy vector, just
change the model function to produce a matrix and `explain()` should work.
Note that you will have to visualize the `.effects` property of the
explanation object yourself since the visualization code is not currently
setup for multi-class outputs.

**Comment by slundberg** [comment]
A bit slow but I finally posted a multi-class image example: https://slundberg.github.io/shap/notebooks/ImageNet+VGG16+Model+with+Keras.html
