### ISSUE TITLE
Interpretation of Kernel SHAP and its hyperparameters

### ISSUE THREAD

**Issue by Jianbo-Lab** [shap/shap#23]
Hi,

I have the following questions with regards to KernelExplainer:
1. I am setting explainer = KernelExplainer(predictor, background, nsamples)  I observe the algorithm is slow even if I set nsamples=1 when the background data set is large. Let's say I have a data set of size n in the background, and set nsamples=k. Each sample is of dimension d. Can I know how many evaluations of predictor are made in total under this setting?

2. I am interested in the definition of the map x' -> x, and how the algorithm is implemented when we have real valued x. I have the following interpretation of the algorithm:
1.Input a sample x, a model f, and the background data set {x1,x2,...,xN} . We want to interpret x.
2.Replace a subset of entries in x, by entries in xi, where xi is randomly sampled from {x1,x2,...,xN}. Evaluate the function after replacement. 
3.Repeat the above for different subset of entries (dimensions), chosen according to the Shapley kernel. 
4.Compute the Shapley value approximation.

3. Also, It seems a single reference point is assumed in the paper, but not in the implemented algorithm. Does 'background' serve as the function of multiple reference points?

Thanks!

**Comment by slundberg** [comment]
Good questions!

1. All the background examples are evaluated for each sample. In the case you describe there are `n * k` evaluations of the predictor (passed as a batch to the provider predictor function). I should also note that if `k >= 2^d` then the entire space is evaluated directly (rather than random sampling subsets from the kernel distribution) and this leads to an exact computation.

2. Very close except for step 2. As mentioned above, in step 2 we produce `n` copies with each copy using a different `x_i` from the background dataset. The expected value of the prediction is taken over these `n` copies.

3. The paper presents two approximations to conditional expectations that make them easier to compute. The first is feature independence, which allows us to integrate out each feature independent of the others, and the second is model linearity (as an approximation), which allows us to only provide a single reference value for the background. Tree SHAP does not make either of these assumptions (it just assumes the tree has captured any feature dependence), but Kernel SHAP as implemented here always assumes feature independence, and may assume linearity depending on how you use it. If you just pass one reference value for the background then you are assuming linearity, if you pass multiple samples then it will integrate over them to provide a better approximation.

I should make this clearer in the docs, but I recommend using either a single background data point, a small random subset of the true background, or for the best performance a set of k-medians (weighted by how many training points they each represent) designed to represent the background succinctly. Passing a large background dataset wastes lots of effort. Perhaps I'll add a warning about that to the code.

**Comment by Jianbo-Lab** [comment]
I see. It is much clearer now. Thanks!

**Comment by slundberg** [comment]
I should also mention that the choice to use a single background reference or multiple samples depends on the type of input data. For images, integrating over a few instances is unlikely to be any better an approximation that just using a single reference. But for structured data using 20 weighted k-medians or a small random subsample might help.
