### ISSUE TITLE
Shap value visualizer Python Version

### ISSUE THREAD

**Issue by soloist96** [shap/shap#231]
Hi, 

   Just wondering if there is a python code for visualizing a single prediction's explanation.  For example, I want to visualize the figure below and save it in a png file. And the current version seems not supporting saving plots in files. Thank you.

![image](https://user-images.githubusercontent.com/28699387/44352767-d31a3980-a46a-11e8-8b77-03d7baa7f0b7.png)

**Comment by slundberg** [comment]
Check out the discussion in #27

**Comment by RA19** [comment]
Hi slundberg, I am having problems using spyder with python 3.5 to visualize the force plots. I have been trying many things but to no avail. It seems like any relevant posts you are always referring everyone to discussion #27 as if there is an obvious answer there. But there isn't.  I'm at the final parts of writing up a publication and shap values is an amazing tool , particularly the force plots, but its useless if i cannot generate them and find any good documentation on how to do this. I really think alot of people are not using it just because of this issue, which is not resolved at all. Could you please give a clear guidlines on how the force plots can be seen, saved, etc in spyder.?

**Comment by slundberg** [comment]
I am sorry it has caused you trouble. Since I don't use Spyder myself I
can't speak to it directly, but I assume the Javascript library is not
working with it. Probably for the same security reasons it doesn't work
with JupyterLab. Have you already tried using the recent `matplotlib=True`
option to force_plot? It was kindly added by @jverre and currently only
supports single sample visualizations. I suspect you are right that issues
like this limit people's use of SHAP, but unfortunately I only have so much
bandwidth right now, so unless someone else provides a PR I won't be able
to sit down and really address this until after the new year. If you have a
specific critical example that just isn't working feel feel to share it
though.

**Comment by RA19** [comment]
Hi, Thanks for your reply.

So yes I updated SHAP and added the matplotlib=True function which works without any problems. I strongly suggest to make that clear in post 27. Really awesome job, this is going to help interpretability so much going forward. Thanks

**Comment by slundberg** [comment]
Thanks. I added a note to #27 that should make it more obvious.
