### ISSUE TITLE
SingularMatrixException with Shap KernelExplainer on SVM

### ISSUE THREAD

**Issue by 19katz** [shap/shap#240]
Hello, 

Sorry if this is a duplicate post, but I searched for it and didn't find the answer. 

I'm getting a SingularMatrixException with the KernelExplainer on SVM. My setup is that I do a k-fold cross-validation on SVM and after the training, I run the test samples on the SVM to get the predicted probabilities and the feature importances through Shap's KernelExplainer. I use a single sample of mean features as my background sample. 

                       background = np.zeros((1, len(features)))
                        try:
                            estimator.predict_proba(background)
                            explainer = shap.KernelExplainer(estimator.predict_proba, background, link="logit")
                            shap_values = explainer.shap_values(x_test, nsamples=100)
                        except Exception as e:
                            print("Got exception: " + str(e) + " on " + str(data_set))
                            shap_values = []

From time to time, I get the following exception: 

Traceback (most recent call last):
  File "linear_stats_plots.py", line 482, in <module>
    shap_values = explainer.shap_values(x_test, nsamples=100)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/shap/explainers/kernel.py", line 203, in shap_values
    explanations.append(self.explain(data, **kwargs))
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/shap/explainers/kernel.py", line 366, in explain
    vphi, vphi_var = self.solve(self.nsamples / self.max_samples, d)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/shap/explainers/kernel.py", line 483, in solve
    tmp2 = np.linalg.inv(np.dot(np.transpose(tmp), etmp))
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 532, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix

One odd thing is that I don't always get this exception: it depends on the iteration. I would appreciate any insights on this. Thank you very much!

**Comment by slundberg** [comment]
How many features do you have? If you are drawing 100 samples, and have
about 100 features then the linear regression equation will be singular (in
this case you should draw more samples or use the `l1_reg` parameter to add
some regularization for feature selection.

**Comment by PrimozGodec** [comment]
I am having the same issue, but the number of features and samples is much different. The number of samples is 100 and the number of features is 9486. I feed each row in data separately to `explainer.shap_values` method. In background data, there is a sample of 10 clusters produced by `kmeans` function from SHAP. I still get `Singular matrix` error. 

I debugged the code a bit and realize that the error is caused since `etmp` matrix have 90 % zero values. I would like to contribute to this package and make a solution for this error, but I do not understand the code in the `solve` function exactly. Can you give me some more explanation of lines of this function, especially following lines:
https://github.com/slundberg/shap/blob/032fc17e50ad81c6a7edfa1630f1838ae8f9c3e7/shap/explainers/_kernel.py#L558-L567

**Comment by PrimozGodec** [comment]
@slundberg can you just respond to the previous comment?

**Comment by PrimozGodec** [comment]
@slundberg ping

**Comment by PrimozGodec** [comment]
@slundberg can you just consider the comment above? I am interested in fixing this bug, but would really need some additional information and context.

**Comment by slundberg** [comment]
Sorry I have been trying to keep up with issues but have been failing! The issue is that with 100 samples (rows) and 9486 features (columns) the design matrix won't be invertible. If the L1 regularization is set high enough and you select << 100 features then the error will go away.

I think the best solution here (as you have suggested) would be to wrap this in a try statement and then warn the user with an informative error message, that tells them they need to either 1) turn up the number of samples, 2) turn up the L1 regularization with something like `num_features(N)` where `N` is less than the number of samples. or 3) group features together to reduce the number of inputs we need to explain.

Thanks again for offering to do PR! Let me know if you need more details.

**Comment by PrimozGodec** [comment]
@slundberg thanks for this. I will propose a PR. I just suggest you an additional idea. 

Would it be OK for you to compute the pseudo-inverse? Pseudo-inverse is equal to inverse when the matrix is not singular and it also gives the result for non-invertable matrix. Besides, I would also add a warning that would show in cases when exact inverse cannot be computed, and would suggest users to do one of the thing that you suggested in the comment above.

This way computation will not fail but if users would like to have "more correct" results they will follow to the instructions in the warning. It would be also easier for us who implements a package (with graphical interface) where it is nice to always show some results. We then warn users when the computation is not exact and some parameter would need to be changed.
