### ISSUE TITLE
future of shap

### ISSUE THREAD

**Issue by zkurtz** [shap/shap#2423]
@slundberg what is the roadmap for shap? It has been a while since the last version release, and I've started to run into package version difficulties when working with shap.

**Comment by snofydunston** [comment]
The version compatibility issue is popping up for running the given examples of Deep Explainer in the local machine. will be happy if newer version of deep explainer is available with support to the latest version of tensorflow.

**Comment by jonnor** [comment]
0.41.0 was released in June, with many goodies and the largest number of contributors yet. https://github.com/slundberg/shap/releases/tag/v0.41.0

**Comment by CloseChoice** [comment]
Thanks for your interest in shap and its future. 1 1/2 years went by and there are a couple active maintainers here and we do our best to provide you the best possible package. Furthermore we just released a new version. I am closing this since there is active development going on and hope you are fine with this. Otherwise feel free to open a new issue.
