### ISSUE TITLE
Question - Deep and Gradient Explainers with PyTorch and Embeddings

### ISSUE THREAD

**Issue by pdurham2** [shap/shap#2472]
Hello, I am trying to use shap with a PyTorch model that uses embeddings and I was wondering if there are any suggestions/examples for how to accomplish this. I found a couple issues from 2019/2020 (#530 and #1039) that address the limitation of pytorch embeddings since they require longs and gradients are only supported with floats, but have there been any developments on this front?

Following the lead in #1039, I also looked at using the Kernel or Permutation explainers but the model I am using does not really fit a tabular dataset since it is using an encoder/decoder structure with different sequence lengths.

Thank you!

**Comment by su-park** [comment]
Hello.
I am stuck with a similar issue to the above case.

I have fastai (PyTorch) tabular embedding model that has two inputs;
one is long tensor which is processed as embedding in the model
and the other is float tensor.

When I try to get `shap_values` using `DeepExplainer`, it throws 
'only Tensors of floating point dtype can require gradients'.

**Comment by jainraj** [comment]
@slundberg, For Deep Explainers in such case, should we just add up the raw or the absolute value of shap values of all the dimensions. You mentioned to add up the raw values in #530, but the method in that issue was IG. 

And if this is the case, @pdurham2, you can first use the embedding layer to get the embedding out separately, use the part of the model after the embedding layer to get outputs, get the shap values and then add them up.
