### ISSUE TITLE
Shap values for accessing variables influence

### ISSUE THREAD

**Issue by hlbkin** [shap/shap#249]
Hi Team!

I am just starting with shap package and have read both papers (for tree and general framework).

What I am interested in is predicting own impact on y with influence on one of the varibales x_i. The end goal is to use it further in optimal control problem where y=f(X) is just a part of the system where we can control and influence some of x_i's

Is shap values good in measuring such impact and using further in Optimal Control problems? Bascially looking for some non-linear analog of Betas in linear regression.
Im asking this because as far as I understood the paper, SHAP measures impact of x_i in case x_i is missing versus it is present in dataset, not really x_i is 0 versus x_i!=0 (or some particular value)

Note that Im NOT interested in absolute importance of variables or feature selection. Control variable x_i might have very low importance compared to other varibales, but be №1 priority in predicting dy/dx_i.

If not, what are good ways to do it? I saw partial dependence plots in sklearn might do somewhat useful for non-linear models.

Thanks in advance

**Comment by slundberg** [comment]
I am not sure I entirely follow your setup. But if you have a non-linear model (say XGBoost or a DNN) that models the dynamics of a system, then SHAP values and SHAP dependence plots would give you an idea of which features are driving the dynamics model's prediction, and how. If you plan on intervening then you can always just intervene on the model and see what happens. If you don't know where to start intervening, then SHAP values could show you which inputs are important, and with dependence plots, how changing them can effect things.

SHAP dependence plots are very similar to partial dependence plots, but they convey more information (like vertical dispersion from interactions, and where your actual data points fall).

**Comment by hlbkin** [comment]
@slundberg 
I'll give better explanation of our current setup. Hope this helps other people as well.

1) My task is very high noice in the first place (R2 <1%), so it is very hard to measure impact just by intervening through the model on certain variables in real time
2) Currently we have linear model, where we accurately make dataset to make observations trully independent and thus making coefficients represent close to real "average impact" (in a linear setting), thus making it possible to somehow use it as a control variable
3) We would like to replace linear model with non-linear to make better predictions and then look at partial dependence plots (or better interactions) to have a understanding of how we impact through x_i with some other x_j. 
4) Take SHAP values for dependence (with other variables interactions) and approximate it with some easy to compute polynomial. Meaning that I would get "average impact with respect to some other x_j"
5) Replace betas from linear model with this polynomial approximation in production.
6*) Possible make live SHAP predictions for each vector X coming in production

The questions are:
1) Is it mathematically valid to look at SHAP values as a tool for control problems (my concern is specifically about the fact how we compute them, i.e. by removing the variable from the model completely)
2) Is it possible to use SHAP values in online setting for single X vector coming in production and make inference about certain x_i impact given all other x_j that we do not control? Part of this question is also in regard to using it then in Java/C++ which I do not quite understand if it feasible now or not (xgboost might be the easiest probably)

Is my approach valid in general?

**Comment by slundberg** [comment]
Sorry for the late reply, I was away on travel for a while. 

I am not sure I see why having a high noise problem would prevent you from learning by tweaking a feature in your model, since the model (if it is a good one) should have smoothed out the noise. A reason however you might not be able to learn much by tweaking one feature is if there are lots of important high-order interactions that won't show up until you tweak just the right set of features. This would be a case where SHAP (Shapley) values would help because they share credit for the interactions among each of the features in an interaction, making it easy to see that they are important.

As for your questions:

1. Yes (I think), but only if you assume independence between the input features when computing the conditional expectations. If you don't assume feature independence then correlated features will share credit even if the model only directly depends on one of them. This means that you might then decide to intervene on the correlated variable and then it would not actually change the model. However, if you train a model on correlated features it is a bit arbitrary which features the model will depend on so it won't be a good optimal control model anyway. In your case I'll assume you have a good control model and so the features in the training dataset are not highly correlated with one another. In that case you should be good to go. (I should note that TreeExplainer does not currently assume features are independent, but we are working on adding that option).

2. You can calculate SHAP values for any input vector you want, so I would think it will work in an online setting. But I should note again that if you are just trying to figure out how to control a single feature, the best thing is to just tweak it and see what happens.

Hope that's helpful :)

**Comment by hlbkin** [comment]
Great answers. thanks.

Am I getting you correct, that if I have for example multivariate dynamic system (y_i is 1 step ahead prediction), but we are interested in steady state prediction (n steps ahead propagation), SHAP value would not really help in directly giving causal inference, but only give good guidance/feature selection for multivariate model. 

Instead you would still need to fit 1 step ahead fit via non-linear model and then do N steps of iteration through VAR model in order to get final estimate of dynamic causal inference, and SHAP would not really help for that.

However, in case of non-dynamic predictions, SHAP would be very fast approximations of doing tweaking it and getting output (like in partial dependence plot). The only difference is that SHAP is in-sample estimators on exactly the data you have seen (which might be biased or have endogenous problems)
