### ISSUE TITLE
SHAP Summary Plot rendering problem (jupyter lab)

### ISSUE THREAD

**Issue by kormilitzin** [shap/shap#2493]
I tried to reproduce the example from [here](https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/tree_based_models/Census%20income%20classification%20with%20XGBoost.html), but for some unclear reason the right-most side bar ("High-Low") is empty:

![Inkedshap_LI](https://user-images.githubusercontent.com/20815939/162545462-7135f6db-250b-454d-9003-e5c445e8e1ed.jpg)

I am on Ubuntu 16.04, Python 3.9, Jupyter 3.3.3

Any ideas please?

**Comment by francescopisu** [comment]
I had the same problem. I downgraded matplotlib to version 3.4.3 and got the color bar back.

**Comment by kormilitzin** [comment]
@francescopisu Fab! Worked as a charm.

**Comment by NegatedObjectIdentity** [comment]
This problem is mentioned several times, e.g. [here at stack overflow](https://stackoverflow.com/questions/70294681/colormap-bar-on-shap-summary-plot-not-displaying-properly/).
It seems that the handling of colorbar or box aspect ratio has been changed in matplotlib.pyplot version 3.5. However, you can correct that.

- Use shap.summary_plot(..., show=False) to allow altering the plot

- Set the aspect of the colorbar with plt.gcf().axes[-1].set_aspect(1000)

- Then set also the aspect of the color bar's box plt.gcf().axes[-1].set_box_aspect(1000)

This gives you the old result back. If you want to make the colorbar thicker, set the aspect to 100.

Another option from [stack overflow](https://stackoverflow.com/questions/70461753/shap-the-color-bar-is-not-displayed-in-the-summary-plot/) seems to do the following: 

just use 'auto' aspect to do the trick:

- plt.gcf().axes[-1].set_aspect('auto')

- plt.tight_layout()

As mentioned, smaller "box_aspect" value to make colorbar thicker

- plt.gcf().axes[-1].set_box_aspect(50) 

shap version 0.40.0; matplotlib version 3.5.1
