### ISSUE TITLE
Is there a way to use separate feature labels in plotting vs. the feature names from the data object passed in to Explainer?

### ISSUE THREAD

**Issue by scottfleming** [shap/shap#2498]
Suppose I want to create an Explainer based on some pandas dataframe X_train that has feature names designed to be easy to read from a machine perspective (i.e., underscores/camel case rather than spaces to separate words describing the variable name). On the other hand, I want to use an alternative set of human-readable labels in my `shap` plots (summary plots, bar plots, swarm plots, etc). Is there an easy way to do this via e.g., passing in a dictionary mapping raw feature names to feature labels?

**Comment by francescopisu** [comment]
When you instantiate an Explainer and use it to explain some data, shap builds and returns an [Explanation](https://shap.readthedocs.io/en/latest/generated/shap.Explanation.html#shap.Explanation) object. Such object has a number of parameters which can be set, including a `feature_names` parameter.
```
# create the explainer
exp = shap.Explainer(model) 

# explain dataframe without fancy / readable column values
sh = exp(X_raw)

# associate a list of column names
sh.feature_names = X_raw.rename(columns=COLUMNS_NAME_MAP).columns.tolist()
```

Additionally, if you want to display readable feature values, such as Male/Female instead of 0/1, you could exploit the `display_data` parameter.
```
sh.display_data = X_readable.values
```

**Comment by scottfleming** [comment]
Thanks for the great explanation by Francesco! I was having a hard time finding the right way to do this in the docs for some reason, but that was a great explanation.
