### ISSUE TITLE
Inconsistency in API 

### ISSUE THREAD

**Issue by rosscleung** [shap/shap#2562]
There are several ways to choose explainer and to get the shapley values but it's not readily apparent which way does what. Example:

### Method 1
explainer = shap.Explainer()
shap_values = explainer(X)
**shap_values is an Explainer class, also is a 3D array**

### Method 2
explainer = shap.Explainer()
shap_values = explainer.shap_values(X)
**shap_values is a list, and you can do 2-level indexing**

This gets more confusing as you read through the API documentation. Sometimes it seems like you need to run method 1 for a certain plotting method to work, otherwise you need to throw in an index like shap.plots.partial_dependence(shap_values[0]...)

**Comment by marcinchomicz** [comment]
ad "method 1" - shap_values is not an Explainer class. It is shap._explanation.Explanation class. see the result of shap_values.__class__.__name__ or type(shap_values)

ad "method 2" - it is not a list, it is numpy.ndarray. Once again please see the result of type(shap_values)

In general explainer.shap_values() is invoked as part of performing Explainer() (in fact overriden standard __call__ implementation).
The only thing I would ask for is type annotations in plotting methods :-). But at the end of the day you can find details in implementation - it is pretty well documented.

**Comment by rosscleung** [comment]
Thanks for your response but I wouldn't say the documentation is "well". A lot of people are having trouble running the sample code / documentation examples. It almost feels like this repo is semi-abandoned. It's so useful too! Documentation is in dire of updating. Just yesterday, I couldn't get the waterfall plot to work. After googling around, many people are having similar issues (example: https://github.com/slundberg/shap/issues/1420 and a lot on stack overflow). I'm not well versed enough to help out this repo though :(

**Comment by joseortiz3** [comment]
I agree with the sentiment that the API is not consistent with regards to what needs to be passed to the plotting functions. The methods aren't type-hinted, the documentation doesn't state defaults or required parameters, and generally, too many arguments are required to run plotting functions. A user, for example, shouldn't have to slice several arguments on the same index to generate a plot for a given sample. And many of the examples are outdated because there are lines that don't run in the current version because the package has since been reorganized. The repo appears to be close to being abandoned as of May 2023 - the last commit was almost a year ago and 94 open pull requests.
