### ISSUE TITLE
Force plot outputs data inconsistent with model prediction

### ISSUE THREAD

**Issue by mfdresser** [shap/shap#2608]
Hello,

I have trained a decision tree model to predict a certain parameter for a number of materials. When I directly output the prediction of the model, I get a value that is different compared to the force plot generated by shap. Can you help me understand if I have done something incorrectly or if this is a bug? For reference, I am using python 3.7.12 and shap 0.30.2. I also tried with shap 0.34.0 and I have the same exact issue. Here is a screen shot showing my model predicted value of 1.45 with shap force plot showing the value 15.07 in bold. 
![image](https://user-images.githubusercontent.com/79723109/176742595-1cf51d15-089a-43b6-8aa7-2d6a833ceb84.png)

**Comment by nk-fouque** [comment]
I think this might be the same kind of discrepancy described in #2425 although we have been having it with HuggingFace transformers.
Sadly we haven't had a solution for that...

**Comment by mfdresser** [comment]
Thank you for your response! Do you have any indication if the
discrepancy only occurs once force_plot() is used or is it possible
the problem occurs before that? For example, in another part of my
computational process I use:

explainer = shap.TreeExplainer()
shap_values = explainer.shap_values()

i.e. can I still rely on the values I obtain from shap_values()? Thank you.

**Comment by nk-fouque** [comment]
If I understand the package correctly, the plots only show what the shap_values already contain, you can easily verify the outputs by executing `shap_values[0].values.sum(axis=0)+shap_values[0].base_values`, and check if the values are the same that appear on the plot.
Can't say more about whether you can rely on it because I don't know your use-case, but I am investigating to see if I can trust it for mine so I would be at least a bit cautious with how I use the results
