### ISSUE TITLE
Effect of Monotonic Constraints

### ISSUE THREAD

**Issue by BrianMiner** [shap/shap#261]
Hi Scott-

Is there any information available on what the effects may be in relation to Shapley values with a model (tree based is what I am currently interested in) when monotonic constraints are included? For example, should we see shapley value Partial Dependence Plots following a monotonic constraint when it is introduced into the underlying model?

**Comment by slundberg** [comment]
Hmm. I don't recall the exact way monotonic constraints are implemented in XGBoost, and since Tree Explainer uses conditional expectations that might also cause credit from related features to produce some non-monotonic effects in the dependence plots (though I would expect them to be at least very close to monotonic). One thing I can say for sure without a fair amount of digging is that if you have depth-1 trees (no interactions) then you should see perfectly monotonic dependence plots.

**Comment by jacob-salamy** [comment]
I was curious about this today too. It seems like monotonicity holds for binary variables, at least in terms of presence/absence:

Monotonic increasing:
![monotone_shap](https://user-images.githubusercontent.com/39494067/45717945-742f0980-bb69-11e8-9998-04bd2e040602.png)
 
No monotonic constraint:
![non-monotone](https://user-images.githubusercontent.com/39494067/45717947-7729fa00-bb69-11e8-8664-1b98c38fdcf8.png)

I'm assuming dependence plots for continuous variables would show a similar effect.

Also, thank you Scott for developing a fantastic methodology and package!

**Comment by HugoDLopes** [comment]
@BrianMiner I guess you will notice pretty well on the dependence plots if the monotonicity if being kept or not.

The first tool to evaluate monotonicity might have been Partial Dependence Plots (you can take a look at this pretty nice library [PDPbox](https://github.com/SauceCat/PDPbox) ). Nevertheless, SHAP could be complementary to this one.

**Comment by IvanUkhov** [comment]
Does anybody have more insight into what to expect from different visualizations in the presence of monotonic constraints in XGBoost? I’m specifically curious if it is reasonable to expect monotonicity from the following:

```python
shap.force_plot(explainer.expected_value, z, x)
```
