### ISSUE TITLE
How to explain stacking models? One model output is an input feature to the final model

### ISSUE THREAD

**Issue by DonCorle0ne** [shap/shap#2616]
Hello,

I am working on a problem where model 1 output is an input feature to model 2. Both models share the same features (except the model 1 output) and both are tree based models. How do we do in this case? Does the package already have this functionality?

**Comment by CarlaFernandez** [comment]
I would analyze each model separately. I would create an explainer for model 1, check feature importance, paint some scatter plots, get a feel for the explanations. And then, create another explainer for model 2 with the dataset which includes model 1's output and repeat the process. I don't think there is currently any other way to do this, or even that it makes sense to create one, since probably your targets are very different and so a joint analysis won't be possible :)

**Comment by Sinnaeve** [comment]
> I would analyze each model separately. I would create an explainer for model 1, check feature importance, paint some scatter plots, get a feel for the explanations. And then, create another explainer for model 2 with the dataset which includes model 1's output and repeat the process. I don't think there is currently any other way to do this, or even that it makes sense to create one, since probably your targets are very different and so a joint analysis won't be possible :)

Wouldn't it make sense to explain model 2 output, get feature importance for features: 
[feature_1, ..., feature_N,  Output_of_model1].
Then explain model 1 output : get feature importance for features [feature_1, ..., feature_N], multiply those feature importance by the feature importance of Output_of_model1 from 1st explainer and add the weighted sum to the rest of the feature importance of the first explainer ?
