### ISSUE TITLE
Unable to import SmartExplainer. Running into ModuleNotFoundError: No module named 'tkinter' error

### ISSUE THREAD

**Issue by Dikshit194** [shap/shap#2625]
Hi Team,

I am trying to import SmartExplainer on Windows OS but getting ModuleNotFoundError: No module named 'tkinter' error. So tried installing tkinter but that also did not work. Please find teh below screenshot and please suggest something.
![image](https://user-images.githubusercontent.com/56040416/179793872-765bf67a-e907-4d7a-b7b4-4e903cd04aae.png)
![image](https://user-images.githubusercontent.com/56040416/179793935-9ecf9455-2333-4da0-a9f6-2dbacccfca11.png)

**Comment by remo-help** [comment]
`tkinter` should already be a part of your python distribution

Are you running Python 2.7? In python 2.7 `tkinter` is called as `Tkinter`.

Try rerunning your code in Python 3.

If you can call `python -m Tkinter` then you are in Python 2.7
if you can call `python -m tkinter` you're in Python 3+

**Comment by ian-andriot** [comment]
Just a heads up that this is shap and different than shapish which you are importing from.

Looks like this is neither a shap or shapish issue though, but an environment issue. Specifically this looks like a Linux environment of some sort running python 3.8. After looking into this, it looks like you need to use whichever distros package manager to install tkinter rather than pip.

If it's Ubuntu then something like this should resolve your issue:
```
sudo apt-get install python3-tk
```
