### ISSUE TITLE
SHAP interpretation for a single observation

### ISSUE THREAD

**Issue by psathish-k** [shap/shap#2630]
Hey! I've a query on SHAP interpretation for one observation. I want to represent the SHAP values of a query point in terms of percentages so as to know which feature contributed more towards the model's prediction for that query point.
For example, given a query point, let the SHAP values for features(F) be (F1, F2, F3, F4, F5) = (-0.23, 0.11, 0.25, 0.23, 0.15). If I take the absolute value then it means treating -0.23 and 0.23 as same whereas intuitively they mean different. What would be the best work around in this case?
One approach I thought was to scale the SHAP values to lie between 0 and 1 (MinMaxScaling) and then represent as percentage. Please let me know if this will work. Thanks in advance.

**Comment by remo-help** [comment]
whether a feature's value is -.23 of .23, its absolute contribution in terms of percentage will be the same, you can just transform your features to absolute values and calculate a percentage in terms of total contribution:


```
import numpy as np
import matplotlib as plt

# index of the single decision you want to look at
decision_index = 3

# we transform the shap values to absolute values and take the slice at your index
# explanation == your shap explanation object (output of explainer)
single_decision = explanation.abs[decision_index]

# we find the total amount of contribution of all the values:
total_cont = np.sum(single_decision.values)

# we create a dictionary of feature_name:absolute shap value pairs
feat_val_pairs = dict([(single_decision.feature_names[i], single_decision.values[i])
 for i in range(0,len(single_decision.feature_names))])

# we transform the dictionary to reflect percentages
for i in feat_val_pairs:
    feat_val_pairs[i] = feat_val_pairs[i]/total_cont*100

# then we plot it, but you can also cast it as a dataframe
plt.bar(feat_val_pairs.keys(), feat_val_pairs.values(), color ='red',
        width = 0.4)
plt.show()
```

**Comment by psathish-k** [comment]
Hi Remo!, Thanks for helping me out here.
However, I remember reading @slundberg's reply on one of the issues earlier where he said transforming to absolute values is right only when we are computing the percentage contribution of a feature across the whole dataset and not across features. So for a single observation, let say the SHAP values are in probability space, then sum of SHAP values + Expected value equals the model's probability prediction. So I'm not really convinced to use the absolute value across features to compute percentages.

**Comment by remo-help** [comment]
Hm, I'm struggling to see how you would calculate percentile contribution any other way in this case. Percentages might just not be a good measure for this scenario.

Does it have to be percentages? I think a [waterfall plot](https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/waterfall.html) or [force plot](https://shap.readthedocs.io/en/latest/generated/shap.plots.force.html) would actually be more insightful for this particular case. Since you want to look at a single model decision, percentage contributions may not be useful here.

Do you have the post you're referring to, I'd be interested to read it.

**Comment by psathish-k** [comment]
Hey Remo! Here's the link to the post,
https://github.com/slundberg/shap/issues/933#issuecomment-564269636

Answering to your question, Yes, I need to have it in percentages. So here's exactly what my scenario looks like. First, I'm trying to aggregate the SHAP values of 50 odd features into 8 groups where each group corresponds to a Business function such as sales, operations, etc. So here I can add the SHAP values of each feature to get the group's contribution exactly the way mentioned in the post whose link I've shared above.
Second, I want to know which group contributed the most in favor to model's prediction and by how much. So here's where I'll be representing them as percentages. 

I could just think of one hack here, Since in probability space, sum(SHAP values) + E[x] = predicted_probability, I'll scale the SHAP values of all features to range from 0 to 1 using MinMaxScaling method and represent them as percentages.
Do you think this would work? Or am I missing out something here?

**Comment by remo-help** [comment]
So, I'm not sure why @slundberg 's says that you cannot simply use absolute values here, but that's neither here nor there.

Regarding your proposed solution: I don't see how this is different from simply using absolute values. A MinMaxScaler will just transform your values to a range between 0,1. Which means it will also transform your negative values to a positive value (just a positive value between 0 and 1). So in terms of percentage, your results will be the same as the method I proposed, but you're taking a different way to get there.

If the difference between negative and positive contribution is important for you. Then I would display them as different percentages. You should separate negative contributions from positive contributions.

__Assume your scenario, you have 50 features, separated into 8 groups:__
- for each model decision, you sum the total contributions of all features (no normalizing, no absolute values) in true values. Let this be `TOTAL`
- then you sum all negative contributions and all positive contributions over all features respectively. Let those be `POS` and `NEG`. 
- You take the base value `E` (expected model decision) and you take that as total from which you can calculate a percentage contribution for `POS` and `NEG` over all features. (Say `E=1` and `NEG= .5`, then `NEG` has a total negative contribution of 50%  from the base value). This will be your high-level view.
- From here you can look at your groups and features at 2 different levels of granularity:
- - For each group, you can do the same calculation as above. You find the total `NEG` and `POS` for the group. You can then display how much this group contributes to the global `NEG` and `POS`.
- - Then you can sum all contributions within a group, and see whether the sum contributes to your `TOTAL` or subtracts from it. If it contributes, you can display it as a percentage contribution. If it subtracts, you can transform that into an absolute value, calculate a percentage from `TOTAL` and display it as a 'negative percentage', in the sense that this group contributes an overall negative to your `TOTAL`. Alternatively, you can use `E` here instead of `TOTAL`, to be more consistent. Or you can use `TOTAL` instead of `E` throughout. It depends on whether you want to view the contribution of a feature as a deviation from your base value (then use `E`) or you want to view it as an additive member of the total deviation (which would be `TOTAL`)

This is a lot more complicated, but I think it would be more adequate for your use case. Especially if you're using this to present to management or business leaders who are more used to thinking about net positives and net negatives. It depends on your perspective, if you're an AI engineer, you probable care more about 'feature importance', you want to know how important a feature is for your model decision. If you're management, you're maybe more used to thinking in terms of negative and positive contributions to a net total, which you want to be positive. 
Even if it's counter-intuitive. If a feature has a high negative shap value, its contribution to the model decision is higher than a feature with a low positive value. This is why I suggested you use absolute values.
