### ISSUE TITLE
Define missing value for one or more variables

### ISSUE THREAD

**Issue by jacob-salamy** [shap/shap#276]
I understand that 'missing' means a feature takes its average value from across the whole dataset.

However, I am interested in defining 'missing' as a feature taking the value of 0. 

I only want to apply this to one feature in my dataset: the % discount on an item. I want to estimate the impact that the discount had on amount sold relative to a discount of 0 rather than the average discount.

Does anybody know how I should go about doing this?

**Comment by slundberg** [comment]
Which explainer are you using? To do that you need to redefine the background distribution that determines what missing means (for example by setting all the % discount values to 0). For TreeExplainer that is not easy because the background distribution is recorded in the tree model.

A simple hack would be to subtract the shap_values when you set that feature (% discount) to 0 from the values when you set it to the current value. I don't think that would be exactly the same as changing the background distribution, but it would give the effect you want.
