### ISSUE TITLE
requirements.txt doesn't list all required dependencies

### ISSUE THREAD

**Issue by yurivict** [shap/shap#2827]
The code imports numpy, scipy, but they aren't in requirements.txt

**Comment by dsgibbons** [comment]
Those requirements are installed via `setup.py`.

I'm not sure that we actually need `requirements.txt` anymore. Is that correct @thatlittleboy?

**Comment by thatlittleboy** [comment]
I would say in _some_ ways, yes, we don't need `requirements.txt` anymore.

For the purposes of installing the `shap` library and its required (immediate) dependencies, it's true that `requirements.txt` is not used; pip or conda will read the specification in the `install_requires` in `setup.py`. And these are usually loose version specs, like `numpy`, or `numpy>0.20` etc.

Whereas `requirements.txt` should specify the requirements for the entire project, _including transitive dependencies_, and should be exact (nowadays, people use lock files to do this, though). It captures the state of the project at that time, e.g. what versions of packages were used to run tests, so that if someone were to checkout the repository at any particular SHA, they can reproduce the passing/failing test results, reproduce bugs reported in issues, etc.

That said, I think @yurivict is talking about the first use case / scenario, so I think we can safely close off this issue?

**Comment by dsgibbons** [comment]
Oh we can definitely close this issue. I was more wondering whether we can remove requirements.txt entirely?

**Comment by thatlittleboy** [comment]
> Oh we can definitely close this issue. I was more wondering whether we can remove requirements.txt entirely?

I think we would need something for no.2 one way or another, for better reproducibility, in the future. Whether that takes the form of a `requirements.txt` (via pip-tools) or a lock file (via pdm/poetry/etc.), we can decide later on.

For now, we can remove the `requirements.txt`.
