### ISSUE TITLE
weighted least squares equation to estimate phi

### ISSUE THREAD

**Issue by betterlulu** [shap/shap#287]
Hi, Scot! I have some problems in the kernel.py about weighted least squares equation to estimate phi. 
The variable "eyAdj2 = eyAdj - self.maskMatrix[:, nonzero_inds[-1]] * ( ", you said eliminate one variable with the constraint that all features sum to the output. I want to know why do you eliminate one variable. The matrix calculation can get the phi for all variables once in WLS.

**Comment by slundberg** [comment]
Hi! The reason I eliminate one of the variables is because two of the weights from the Shapley kernel are infinite (meaning they are hard linear constraints). One of these weights eliminates the bias term from the model, while the other one allows us to eliminate one feature from the problem. We could of course have just used a large value for the infinite weights, but eliminating variables prevents any numerical issues.
