### ISSUE TITLE
Doubt about definition in the NIPS article

### ISSUE THREAD

**Issue by vilarinoramon** [shap/shap#299]
Hi, @slundberg ,

I wrote about this doubt before by email. In the beginning of section 4 of your article you set

**$f_{x}(z') = f(h_{x}(z')) = E[f(z)|z_{s}]$**

If I understood it correctly, this is where you set the map $h_{x}$ to be used, which would make it all clear to me. But I couldn't understand clearly the definition of this conditional expectation. How exactly am I supposed to set the base value $E[f(z)]$? And, given $E[f(z)]$, how do I compute, for example, $E[f(z)|z_{1}=x_{1}]$?

I would be very grateful if you could explain to me more explicitly what you are setting at that part of the argument.

Best,

Ramon

**Comment by slundberg** [comment]
That is the definition about how to measure the impact of knowing a set $S$ of features. $E[f(z)]$ can be computed by taking the expected value of your model's output over the training dataset (since z represents an arbitrary sample from the background data distribution). $E[f(z)|z_{1}=x_{1}]$ can be computed using Equation (11) of the paper by finding the expected value of the model's output over all the training data when feature 1 is always constrained to be equal to x_1. There are other ways to compute $E[f(z)|z_{1}=x_{1}]$ for trees that do not require assuming feature independence and they are in our Tree SHAP arXiv paper.

Hope that is helpful!
