### ISSUE TITLE
MAINT: remove changelog, publish GH release notes

### ISSUE THREAD

**Issue by connortann** [shap/shap#3095]
@thatlittleboy I have a proposal about our changelog - I think we can streamline the process a bit.

I originally added a changelog to the SHAP Community Fork, as we weren't making releases and needed a place to put changelog info. However, now that we're back in the main repo, we could remove the changelog and use the GitHub release notes to source the summarised changes (which is what has been done for most of the repo's history).

Some advantages:

1. **Commitless releases**
   - A new commit would not be needed to publish, which streamlines making a new release
   - We'd also need to source the version number from git, as in #3059.
2. **Auto-generated notes**
   - GitHub drafts the release notes messages from PR titles, which one can then manually tidy up and group into "Fix / Added / Changed / etc" subheadings
3. **Less admin on each PR** / simpler checklist

To make the release notes a bit more navigable, we could look at including the release notes in the docs, with [Sphinx Github Changelog](https://sphinx-github-changelog.readthedocs.io/en/latest/). If I get some time next week I'll give it a shot and see how it looks.

We could also make life easier for ourselves by ensuring the names of PRs are clear, if needed by **renaming the PRs before merging**. It's very helpful when the title includes with a verb like "Fix", "Add", "Remove", as that helps organise the messages into useful headings in the release notes. (It doesn't have to be perfect, as one can always reword things in the release notes themselves).

**Comment by thatlittleboy** [comment]
Great! I'm open to the suggested changes. A few things I would wish to have (some are overlapped with your points):

1. If not in CHANGELOG.md, then the changelog should be in the docs. I'm not a fan of the Release notes on GH as a full-on replacement for the CHANGELOG file.
2. Ability to customize the changelog entry messages. If the message is always the PR title (for example), it could be little too restrictive, IMO. Somewhat related: I like the link to the PR on each changelog entry, for example. I find it extremely useful when browsing changelogs myself (in general, not just for SHAP). Hopefully that would still be possible with the new solution.
3. Ability to exclude certain PRs from the changelog. Not all PRs require an entry in the changelog.
4. The "Unreleased" section. I'm assuming we would lose this? since the changelog is updated on release only (If I understand correctly).
5. Proper categorization of each change in the CHANGELOG -- we can also let Github automatically categorize for us based on the labels (instead of relying on the PR titles), https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes. (And of course, we can then adjust it manually if needed, but it should lessen our workload during release time). 

Looking forward to your PR!

**Comment by connortann** [comment]
Agreed on all points 👍
