### ISSUE TITLE
Possible to Generate Summary Plots and Dependence Plots using SKLearn Models?

### ISSUE THREAD

**Issue by Keita1** [shap/shap#31]
Hi,

Thanks for this wonderful resource! It has enhanced my work greatly.

I was wondering if it is possible to generate Summary and Dependence plots using SKLearn generated models. I have been able to duplicate your work using my own data trained on Sklearn's forest models. But I have not been able to create the plots in question.  I also notice you don't include them in your sklearn examples. 

Any help or hint is appreciated!

Thanks,

Keita

**Comment by slundberg** [comment]
Glad you find it helpful! The Tree SHAP algorithm is a complex C++
implementation I added to XGBoost and and Light GBM. Because it is so fast
and exact it is easy to explain lots of examples and so make summary and
dependence plots. The model agnostic results can also be used for this, but
you would have to take the ‘.effects’ and make a matrix of SHAP values
(last column should be the expected value of the model output), and
remember that there is variability in the estimates.

It would be nice to have Tree SHAP in sklearn but I have not invested the
time there yet or reached out to see if they are interested.

**Comment by slundberg** [comment]
FYI: I just added a new function that will make it easier to make summary and dependence plots from the model agnostic Kernel SHAP explainer.

Following the model agnostic (multi-class) example from the front page we can now get:

```
explainer = shap.KernelExplainer(svm.predict_proba, X_train, nsamples=100, link="logit")
shap_values = explainer.shap_values(X_test)

# plot the SHAP values for the Setosa output of the first instance
shap.summary_plot(shap_values[0], X_test[0])
```

**Comment by Keita1** [comment]
Thanks for responding and adding additional functionality!!
