### ISSUE TITLE
SHAP values and influential features different with Kernelexplainer and tree explainer

### ISSUE THREAD

**Issue by DebXl** [shap/shap#313]
Hi,

I tried using shap kernel explainer and shap tree explainer on a sample from Census income classification dataset. I trained using GradientBoostingClassifier.

I got different explanations with the kernel and tree explainers:

Kernel explainer: 

![image](https://user-images.githubusercontent.com/44719871/48050978-b4098900-e1c9-11e8-8859-4f689b4914c9.png)

kernel shap_values for the  record: [ 0.53197299,  0.0154611 , -0.09542535,  0.0010581 , -0.39101478,
       -1.05349858,  0.01213471, -0.25418667, -0.1641437 , -0.05299885,
       -0.04145205, -0.03402004]

Tree explainer:

![image](https://user-images.githubusercontent.com/44719871/48051004-c97eb300-e1c9-11e8-8661-829ac0fe7af4.png)

tree shap_values for the  record: [ 0.00555308,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.01521528,  0.        ,  0.        ,
        0.        , -0.00178008]

From the above, the explanations when using different explainers are  not consistent. I want to understand which explainer to use.

**Comment by slundberg** [comment]
One thing to keep in mind about the TreeExplainer is that is explain the output of the trees in the model, which for gradient boosting and classification is the log odds margin (before the logistic transform to probability). So if you use KernelExplainer to explain the probability output and TreeExplainer to explain the log odds output you will get different results.

That being said, you have similar output values, so it could be more about the fact that the KernelExplainer just uses a single (or a few) reference values, while the TreeExplainer integrates over the whole training dataset. If some of the features happen to have the same value as the reference you passed in to KernelExplainer they will have no impact, while to TreeExplainer they will because they won't always be the same value as every sample is training dataset.

I typically recommend using the TreeExplainer for tree models, just keep in mind you are explaining the margin.
