### ISSUE TITLE
Simple question about LightGBM PredictContrib

### ISSUE THREAD

**Issue by IbanezJS** [shap/shap#317]
Hello there!
LightGBM::GBDT::PredictContrib(const double* features, double* output)

1)Does this method calculates "true" shap_values which are deltas from model expected value on whole dataset?
OR
2)I have to substract beforehand calculated expected_value from each output for every sample row ?

**Comment by slundberg** [comment]
The answer is (1). Just remember the expected value is with respect to the margin.

**Comment by IbanezJS** [comment]
@slundberg Thank you.
Ok. But here it comes another question.
Is it correct to use LightGBM(or others) TreeSHAP routine to calculate shap_values on TEST dataset.
Let's look at the LightGBM::Tree::TreeSHAP code:

- const double w = data_count(node);
- const double hot_zero_fraction = data_count(hot_index) / w;
- const double cold_zero_fraction = data_count(cold_index) / w;

data_count() is a leaf or node weight obtaining as result of learning on TRAIN data. 
So if we provide 'const double *feature_values' from TEST dataset then as a result we get shap_values 'deltas' from TRAIN_data_expected_value (not TEST_data_expected_value).

Summarize. How calculate shap_values on TEST data in a proper way? 
PS i'm not using python. But LightGBM source code directly.

**Comment by slundberg** [comment]
Typically we use the training dataset to represent the background distribution of the data, even when explaining test samples. This means the training dataset gives us our prior about how the data behaves when we don't know things about the current test sample. You could use the test dataset, but sometimes you don't yet have a large test dataset. Also, since your model was built using the training data I think it makes the most sense to use that training data for modeling the expected outcomes when you don't know the value of a feature on a test sample (used when we hold features out during the computation of SHAP values).

**Comment by IbanezJS** [comment]
@slundberg Thanks Scott.
I agree. You describe most common way.
In my case i have time series datasets equally large Data1 Data2 Data3 (chronological order).
Data2=TrainData. Data1=Past_Test. Data3=Future_Test
Expected_value could be slightly different on each dataset. I want check out that order of feature_importance by SHAP measure is the same. E.g. that feature_X is the most powerful over all datasets.

**Comment by slundberg** [comment]
I would just train a model on Data2 then, and use TreeExplainer to rank the features on all three datasets separately. Your expected_value in this case will not change (since it is based on data2) and so the SHAP values will be comparable across the datasets.
