### ISSUE TITLE
shap explainer expected_value is different from model expected value

### ISSUE THREAD

**Issue by siteshi** [shap/shap#318]
Hi I have notice strange behavior 

>>model = RandomForestClassifier(random_state=123)
>>model.fit(X_train, Y_train)
>>y_hat = model.predict(X_train)
>>model_expected_value = [len(np.where(y_hat == label_)[0])/len(y_hat) for label_ in [0,1,2]]
>>print("expected value from model ",model_expected_value )
[0.34814814814814815, 0.3111111111111111, 0.34074074074074073]

>>explainer = shap.TreeExplainer(model)
>>shap_values = explainer.shap_values(X_train)
>>print("expected value from shap ", explainer.expected_value)
[0.3518518518518518, 0.314074074074074, 0.3340740740740741]

As documented:  explainer.expected_value is nothing but average of the classifier/model output over training datatset. Then why both the values are slightly different

**Comment by slundberg** [comment]
Great question! It is because of how sklearn records the training samples in the tree models it builds. Random forests use a random subsample of the data to train each tree, and it is that random subsample that is used in sklearn to record the leaf sample weights in the model. Since TreeExplainer uses the recorded leaf sample weights to represent the training dataset, it will depend on the random sampling used during training. This will cause small variations like the ones you are seeing.

We could eliminate this minor issue by recomputing all the leaf weights directly from the training data, but then we would need to pass X_train and not just the model to the TreeExplainer.

**Comment by siteshi** [comment]
@slundberg: Thanks a lot for the clarification. Make sense now.

**Comment by zyxue** [comment]
Is this also the case for LightGBM models, in which I thought there is no subsampling by default?

```
import lightgbm
import shap

data = sklearn.datasets.load_iris(as_frame=True)

df = data["frame"].sample(100).reset_index(drop=True)

X, y = df.drop(columns='target'), df['target']

model = lightgbm.LGBMClassifier(n_estimators=2, max_depth=2).fit(X, y)

explainer = shap.Explainer(model)

shap_values = explainer.shap_values(X)

print(df.target.value_counts(normalize=True).sort_index().values)
print(np.exp(explainer.expected_value))
```

results in
```
[0.33 0.37 0.3 ]
[0.32722212 0.36802693 0.29728311]
```
