### ISSUE TITLE
ENH: can we remove numba as a dependency requirement?

### ISSUE THREAD

**Issue by jplasser** [shap/shap#3185]
### Problem Description

I want to run shap on my iPad in Juno Jupyter NBs, but there shap can't be installed very likely because of the numba dependency. Is it possible to install, run and use shap without numba?

### Feature request checklist

- [X] I have checked the issue tracker for duplicate issues.
- [ ] I'd be interested in making a PR to implement this feature

**Comment by connortann** [comment]
Numba is a core dependency of shap, so I'm afraid shap cannot be installed without numba.

Furthermore, Juno only supports installation of pure python packages whereas shap has compiled extensions. So, even if shap did not use numba, shap would not be supported by Juno.

I think this enhancement request relates to Juno rather than shap, as it is a question of what types of package they support which is outside our control. For now I will close this issue as "not planned".
