### ISSUE TITLE
Possible to include Anchor?

### ISSUE THREAD

**Issue by keithcallenberg** [shap/shap#32]
A new method was released by the authors of LIME. Would there be any value in adding this somehow to the SHAP package?

Paper title: "Anchors: High-Precision Model-Agnostic Explanations"
Paper: https://homes.cs.washington.edu/~marcotcr/aaai18.pdf
Source: https://github.com/marcotcr/anchor

**Comment by slundberg** [comment]
Anchor is a great method, but it does not easily fall in the class of additive feature attribution methods unified by SHAP, and I would like to keep the shap package focused on doing one thing well at the moment.

That being said...there might be a way to interpret SHAP values in order to make a "anchoring statement". That could be useful for a variety of reasons, including that (last I talked with Marco about it) Anchor currently just focuses on classification problems and not regression.

**Comment by keithcallenberg** [comment]
Makes sense! Thanks.
