### ISSUE TITLE
Question on shap value distribution

### ISSUE THREAD

**Issue by GinoWoz1** [shap/shap#320]
First of all, thanks for the great package. I found some really interesting things using it recently to unstack ensemble models and explain what is happening under the hood. 

Already searched all issues but still had a question on a regression problem where the y data set range was from 60,000 - 700,000.

In your paper you state:

> This method requires retraining the model on all feature subsets S ⊆ F, where F is the set of all
features. It assigns an importance value to each feature that represents the effect on the model
prediction of including that feature. To compute this effect, a model fS∪{i} is trained with that feature
present, and another model fS is trained with the feature withheld. Then, predictions from the two
models are compared on the current input fS∪{i}(xS∪{i}) − fS(xS), where xS represents the values
of the input features in the set S. Since the effect of withholding a feature depends on other features
in the model, the preceding differences are computed for all possible subsets S ⊆ F \ {i}. The
Shapley values are then computed and used as feature attributions. They are a weighted average of all
possible differences:

So for the distribution of shap values - I am getting a little confused as it pertains to the paper and the distribution. If the weighted average of all possible differences is computed, how to explain a single point on the chart below and the resultant distributions?

The confusion arises when it is described in the package that the values represent a large(r) number as it relates to the impact on the model; e.g ExterQual_TA  (low quality ) has a negative effect on the model with the binary value whereas OverallQual has a positive effect on the model. I am having trouble to explain the distribution. For example, what the is the meaning of the binary values range in a regression problem?

![image](https://user-images.githubusercontent.com/17535345/48301985-22409b00-e4ab-11e8-90c9-3a8d285f2ce7.png)

**Comment by slundberg** [comment]
I am not sure I fully understand the question, but a few thoughts that might help:

- Note that the part of the paper you are quoting is describing the Shapley Regression Values approach (the first to ever use Shapley values in ML), but unlike that approach SHAP does not retrain the model on every subset. Figure 1 in the NIPS paper is probably the best way so see what a SHAP value for a feature means. Just remember that we average the impact of the feature over all possible orderings.
- The reason SHAP values for a binary feature (like ExterQual_TA) have a distribution (and not just two values) is because of the interaction effects present in the model. Even if two samples have the same value of ExterQual_TA, ExterQual_TA can impact the model differently because of other features that differ between those two samples. This means for the binary features in the summary plot the width of the blue and red distributions show how much interaction effects impact the importance of that feature.

**Comment by GinoWoz1** [comment]
Thanks. 

So the distribution of ExterQual_TA is the range of possible effects on the model. What does each point represent? Each record in the data set with its respective shap value for that column?

**Comment by slundberg** [comment]
> What does each point represent? Each record in the data set with its respective shap value for that column?

Exactly.

**Comment by GinoWoz1** [comment]
Thanks!
