### ISSUE TITLE
DeepExplainer no longer supports DenseData

### ISSUE THREAD

**Issue by imatiach-msft** [shap/shap#339]
DeepExplainer previously supported DenseData for background data, but now it seems it no longer does.  I noticed however that the documentation says that only background data of numpy or pandas dataframe is supported for Tensorflow:

https://github.com/slundberg/shap/blob/890d85b49228c061a0d46ad76e0bbaa6b506d015/shap/explainers/deep/__init__.py#L42

If the documentation says this, is this then by design, and there was a conscious decision to no longer support DenseData for the background?  Or was that a minor bug and we should actually still support DenseData like the other APIs (and wouldn't it make sense to use KMeans to summarize the background)?

**Comment by slundberg** [comment]
Good point. It was not an intentional design choice. It was just I didn't consider weighting the samples when first building deep explainer. I don't think it would be hard to do. In fact we could just wrap any dataframe or numpy array as dense data when in init to keep a consistent interface. This is also something we could do for TreeExplainer eventually since for our new feature_dependence="independent" assumption we need a dataset just like DeepExplainer.
