### ISSUE TITLE
shap installation failed; python version- 3.12.1

### ISSUE THREAD

**Issue by Kkhurana007** [shap/shap#3468]
shap installation failed; python version- 3.12.1
> 1. with pip I'm getting this error- 
![image](https://github.com/shap/shap/assets/91566244/e45d4908-ecbc-426f-a7ae-d2d47d77d57a)

> 2. then looking at the [official documentation](https://github.com/shap/shap/blob/409e004ca11f0cf9f8ac9fca446bfae85d8453c6/CONTRIBUTING.md#installing-the-latest-version), I was able to install it. It gets activated in the conda environment, 
 
![image](https://github.com/shap/shap/assets/91566244/095312d0-bb51-4ec2-9fa9-3e8189819472)

![image](https://github.com/shap/shap/assets/91566244/382e0ceb-c70d-4d47-b427-b0102bc1c737)

but I get the error when I work with it in the jupyter notebook-
![image](https://github.com/shap/shap/assets/91566244/859b0dbb-71e3-446e-82d9-5f6ed9e82e7d)

Any help?

_Originally posted by @Kkhurana007 in https://github.com/shap/shap/issues/539#issuecomment-1907287136_

**Comment by connortann** [comment]
This is expected, as at present shap does not support python `3.12` and the installation would not be expected to succeed. The error message above is correct: "only version <3.12" are supported".

Related issue to track support for 3.12: #3305 

I'll close this issue for now as this is expected behaviour.

**Comment by detrin** [comment]
Once this will be closed https://github.com/numba/numba/issues/9197
