### ISSUE TITLE
Questions about SHAP paper

### ISSUE THREAD

**Issue by Mark531** [shap/shap#368]
On figure 2, you represent the attribution values phi_i for all features x_i. On this figure, it seems that phi_0 equals E[f(x)], and phi_1 equals E[f(x) | x_1] - E[f(x)], is that correct? It looks like impact encoding. But how comes that phi_2 seems to be computed relatively to phi_1, and so forth?

Besides, I don't understand the notion of variables ordering here. If all features are considered binary, I would naturally compute the attributions this way:
phi_1 = E[f(x) | x_1 = 1] - E[f(x)]
phi_2 = E[f(x) | x_2 = 1] - E[f(x)]
...

What would be the problem of this approach?

**Comment by slundberg** [comment]
Good questions. The diagram in Figure 2 is simply meant to be illustrative, the Shapley values are the average of doing that over all possible orderings, not just the single ordering shown.

It is important to consider the impact of features relative to other features because of interaction effects. When another feature is present it might change the impact of knowing another feature. One practical issue with the approach you suggest is that (if there are interaction effects) they do not sum up to anything meaningful, like the output of the model. If you don't care about your features summing up to something then the approach you suggest is a valid option.

**Comment by Mark531** [comment]
Thanks for your reply.

From what I understand, what you call "ordering" is the order by which subsets of variables are added to the model, is that correct?

What bugs me in that approach is that you theoretically have to retrain the model for every possible subset of variables, which leads to a combinatorial explosion. Fortunately, it seems you found a way to avoid retraining when the model is a forest of decision trees. There should be a simpler approach that takes advantage of the full model, just like the use of log-odds and marginal effects in logistic regression...

Sure, it's convenient to have feature attributions that are additive in the score space. But I'm wondering about the interpretation of SHAP values. How can they be used?

**Comment by slundberg** [comment]
Definition of ordering: That's right.

Retraining your model is one way to estimate the importance of conditioning on a subset of variables (and it will be the same as SHAP if you are using a squared loss) but we instead use conditional expectations exactly so we can define the importance of a feature using only the original full model.

Not sure it answers your question, but I think it is intuitive to consider what the SHAP values of a linear model are with independent features: `shap_values[0,i] = coeff[i] * (x_explain[0,i] - x_train.mean(0)[i])` It is just the coefficient times the mean centered feature value. It is also useful to remember that the units of the SHAP values are the same as the units of the function we are explaining, so for XGBoost logistic regression the units are log-odds (since that's the output of the trees).

**Comment by Mark531** [comment]
Well, even for a simple case like a logistic regression, it looks challenging to evaluate the marginal effect of a variable only from the full model estimated with all variables, especially because of interactions (think of the XOR problem). For tree-based models, the challenge looks similar. I may be wrong but to me, building a decision tree with all but one variables could have a totally different structure than a decision tree with all variables, it's not just a matter of branches to remove. It seems you solved it with your Algorithm 1, but I confess I don't really understand what it does.

Ok, thanks for the details. So, for a XGBoost logistic regression, SHAP values can be interpreted as log-odds. The delicate point remains the presence of interactions between the input variables. For instance, if two variables tend to be very significant only when used together in the model, it may not be perceptible from the SHAP values.

**Comment by slundberg** [comment]
As to your last point, Shapley values equally distribute the credit for interaction effects among the participating features. That means in your example both features would share the credit for the impact. If you want to know what part of a feature's impact is from interaction effects and what part is from main effects you can use the SHAP interaction values. They divide up credit among all pairs of features, so main effects will be on the diagonal of the returned matrix of feature attributions, while interaction effects will be on the off diagonal (with higher order interactions again split evenly among the pairs that make them up). For TreeExplainer you can use `shap_interaction_values` to get them. Hope that's helpful :)

**Comment by Mark531** [comment]
Ok, I'l check SHAP interaction values, that looks promising.

I'd also be interested in a pointer to a full explanation of your algorithm that extracts SHAP values from the XGBoost trees, if there is one.

**Comment by slundberg** [comment]
Unfortunately the best we have right now is the [arXiv paper](https://arxiv.org/abs/1802.03888), I'll share on github though once we have a longer version.

**Comment by Mark531** [comment]
Thank you and happy new year!
