### ISSUE TITLE
shap_values = explainer.shap_values(X_test) is a cumbersome training 

### ISSUE THREAD

**Issue by ghost** [shap/shap#372]
```
import shap

explainer = shap.DeepExplainer(Model.model, X_train) #Using TensorFlow backend.
shap_values = explainer.shap_values(X_test)
```

`X_train.shape` is `(35087, 15, 103)` and `X_test.shape` is `(11696, 15, 103)`

Normally, to train `Model.model`, it takes 15 minutes, but now to get the `shap_values`, it's been 2 hours the computer is running and I did not get any results. 

Is there a way to see the time remaining before getting the `shap_values`?

**Comment by slundberg** [comment]
I should put a warning in there, but it is not advisable to put the whole training dataset into the DeepExplainer since it will average over all the samples you pass for each explanation. For GradientExplainer it is fine to pass the whole training dataset, since it will just sample from it, but not for DeepExplainer. Try just passing 100 or 1000 random background samples instead of 35k. As for printing the progress, that would be a good addition, but right now you can just run it for 100 samples and then extrapolate.
