### ISSUE TITLE
Rational for KernelExplainer sampling 

### ISSUE THREAD

**Issue by andi-jo** [shap/shap#375]
Hi, I would have a couple of more questions on the KernelExplainer:

(1) Are there compelling (analytical) reasons why one should or should not use the full training set as background for the KernelExplainer, other than computation time?

(2) Related, is it correct that only using the full training dataset and averaging over all Shapley value contributions of 2^M imputed inputs (with M features) would return the precise Shapley attributions  lerned by the model for a new observations, leading to N_train * 2^M terms for all features? 

(3) if (2) is correct, does the KernelExplainer actually do this if I give it the full training set? If not, what did I get wrong?

(4) Are there analytical approximations for using smaller background datasets, like X_train.mean(0) or a K-means summary, relative to the full set. 

As you can see from my questions, I am very much interested in calculated exact Shapley values as much as possible and to understand any approximation made.

Two minor maybe typos in the paper and Shapley Kernel Proof, respectively:

- Paper: In Eq. 8 (Thm 1), should the x on the LHS also have a prime or be defined as x’=x\i? 

-  Proof: You say “[...] we only need to consider a single row of this 2^M × M matrix [...]”. Looking at the equation for \phi, this should be a M x 2^M matrix and then referring to a row would refer to a feature component \phi_j. Otherwise a row would correspondon to an arbitrary imputed input not a feature?

Thanks, your dedication is really appreciated.

**Comment by slundberg** [comment]
Great questions!

1) The background set is used to estimate the conditional expectations, so the larger that data set is the better in theory that estimation will be. The issue with using the full dataset with KernelExplainer is that as it is implemented right now it is optimized for a small background set (it evaluates the whole background set for every subset of features it is checking). If you want to use a large background dataset you might consider using the SamplingExplainer, it converges slower with a small background set, but since it just samples from the background set you can pass the whole training dataset without any issues.

2) Yes for a full exact computation you would need N_train * 2^M evaluations of the original model.

3) Yep, if nsamples is large enough KernelExplainer will just enumerate the whole space and give you the exact values.

4) `shap.kmeans` is designed to do just that, with the added constraint that we pick a value for each feature that is actually in the dataset (so we don't pick fractional numbers if the data has only int's for example). In the paper the comparisons used a single background value since they included LIME, which only uses a single background reference value. It would be interesting to quantitatively explore the tradeoffs between different background approximations.

Two comments:
- In that equation x is the original input vector and x' (the "interpretable inputs") is a binary vector representing if each feature is missing or not in x (almost always set to all 1's).
- You are right, I'll leave a todo note here to fix that in the errata. Thanks!

**Comment by andi-jo** [comment]
Thanks again & Happy 2019!

To (1) and (3), is it correct that the KernelExplainer actually does not need feature independence to calculate the precise SHAP values (Eq. 9 in the Paper) when using the full and large enough training set to enumerate the input space, because it evaluates the conditional expectations using the full information set of the model?

Also, using only X_train.mean(0) as beackground amounts to Eq. 11, i.e. assuming feature independence, which would offer a convenient evaluation of SHAP values for the general explainer?

**Comment by slundberg** [comment]
Thanks! No the KernelExplainer uses equation 11 which breaks feature dependence when computing the conditional expectation. This has the upside of "intervening" so to speak to identify what the model is actually touching (and not just correlated with what it is touching), but the downside of potentially evaluating the model on unrealistic inputs.

Using X_train.mean(0) amounts to using equation 12 which assumes you can move the expectation inside the model as if it were linear (which of course models you are using KernelExplainer for are not really linear).

**Comment by andi-jo** [comment]
Thanks! Very helpful again.
