### ISSUE TITLE
use “shap.force_plot()”, then "MemoryError"，maybe need "gc.collect()"

### ISSUE THREAD

**Issue by yfhewei** [shap/shap#39]
run shap.force_plot()  
result     MemoryError: 

Int64Index: 213118 entries,
Columns: 109 entries,
dtypes: float64(40), int64(33), uint8(36)
memory usage: 137.6 MB

**Comment by slundberg** [comment]
If I understand correctly you passed 200k explanations to the force plot
method right? Since that method uses D3 to draw in the browser I would not
recommend using more than 2000 or so data points (for example from a random
subsample). There are not even 200k pixels horizontally anyway so the plot
won't gain much from larger sample sizes.

That help? Perhaps I should throw a warning into the force plot function
for large sizes.

- Scott
