### ISSUE TITLE
Interpretation the Feature Effect plot

### ISSUE THREAD

**Issue by YXSIO** [shap/shap#395]
In the horizontal axis, if we look at the range below 45, there is some overlapping between the blue and red for this single feature. I am wondering what does it indicate? Does it means that the feature value in this range will have both positive and negative impact to the output?
 
Also, when x-axis = 30 for example, what is the corresponding value of the y-axis? Is the corresponding y-axis a single value or a range covered by the upper and lower boundary?

![44](https://user-images.githubusercontent.com/6912870/51345244-51e1c580-1a4f-11e9-9fc3-24540b52e7f6.png)

**Comment by slundberg** [comment]
These plots are designed to work with densely sampled points, so what you are seeing is just an interpolation artifact since there are no samples with a feature value between the left side and 1/3 of the way in to the plot. Perhaps we should have just left a gap there, but the two triangles are just interpolating between a negative and positive value in the plotting code. This is one reason a dependence_plot can be better than sorting a force_plot by a specific feature. The force_plot of an array is best for plotting many equally spaced points, either from clustering the points, or by sorting data samples by time (like we did in our Nature BME paper).

**Comment by YXSIO** [comment]
Thanks for the reply. 
Two follow-up questions: if the plots leave a gap instead of interpolating. Should we expect that there will be no overlap between red and blue? In other words, the small overlapping at the right end of the above plot will only contain red triangle? 

The second questions is: If we only look at a single dot on the plot,  Does the vertical value on of this dot reflect the averaged shape value on the data which share the same feature value? In other words, instance which is 60 on the horizontal axis, will possibly have negative impact(Blue impact) to the output?

**Comment by slundberg** [comment]
1. yes, there is no real overlap between red and blue when looking at a single feature's shap value for this plot because...
2. ...if there are multiple data points with the same x-value and different SHAP values for that feature they will be averaged. Again, not ideal, since in a dependence_plot you would see the true vertical dispersion.

**Comment by YXSIO** [comment]
Gotcha! Thanks very much for the explanation. 

Another following-up: 
How do you interpret the color: red and blue? 

My understanding is that red indicate positive impact to the model output, But I also notice that the blue color in the x-axis = 80 has a positive y value. What is the real interpretation of the color?

**Comment by slundberg** [comment]
Red is positive and blue is negative, it's just that the y-axis is the SHAP value plus the expected_value of the function. So even though the SHAP value is negative for the feature, the y-axis value is still positive because of the large positive expected value of the model's output.

**Comment by YXSIO** [comment]
In that sense, Y axis is the total impact of all the features. The colored area indicates the impact of that specific feature to the final model output, considering all the permutations with and without that feature at that feature value. In other words, the height of the color area at a specific x-axis reflect the amplitude of such impact.  Please correct me if I am wrong.

**Comment by slundberg** [comment]
That's right :)

**Comment by GillesVandewiele** [comment]
I'm still having difficulties in grasping the interpretation of the plot when something else than ["order by similiarity", "order by output value" or "original ordering"] is selected from the x-axis dropdown. Am I correct that the individual shapley force plots are then sorted according to that value? But when I hover over the explanations, it does not seem to be like that (as depicted below):

![screenshot from 2019-03-08 12-06-00](https://user-images.githubusercontent.com/5750603/54025370-9b6ea700-419a-11e9-9702-042b8bf3a4e9.png)


Or should I just ignore that hovering information, and draw a conclusion from this plot that as soon as gest_age >= 240, it starts contributing positively to the model output?

**Comment by slundberg** [comment]
@GillesVandewiele Thanks for pointing that out! That's a bug with the hover values being displayed wrong. The bold hover values should match the x-axis...

**Comment by yanyyyy3** [comment]
I want to ask what the effect of a certain feature in the y-axis means because the value seems to be different from SHAP value. Thanks!

**Comment by slundberg** [comment]
@yanyyyy3 it should be the SHAP value, just remember that the SHAP values are often stacked and also the order of the samples can change.
