### ISSUE TITLE
plt.xlim() doesn't work in dependence_plot() when plotting interaction values

### ISSUE THREAD

**Issue by Barcavin** [shap/shap#405]
Hi,

First of all, I want to say this is a great library for model interpretability. It can help add more insights into the black-box model, especially for business. Thanks for all the work.

The issue I'd like to raise here is about the dependence_plot().

If I want to plot the interaction values with dependence_plot:
```
shap.dependence_plot(
    ("Age", "Age"),
    shap_interaction_values, X.iloc[:2000,:],
    display_features=X_display.iloc[:2000,:],
    xmin = 0,
    xmax = 40
)
```

**xmin** and **xmax** won't work here. I think it is because **xmin** and **xmax** are not passed into the recursive function here. (https://github.com/slundberg/shap/blob/aff7ee81f33899f0d22972f1e8afff98f0ee7ef3/shap/plots/dependence.py#L91-L112)

There is a workaround:
```
shap.dependence_plot(   
    ("Age", "Age"),
    shap_interaction_values, X.iloc[:2000,:],
    display_features=X_display.iloc[:2000,:],
    show=False
)  
plt.xlim(xmin=0,xmax=40)
plt.show()
```

**Comment by slundberg** [comment]
Thanks for pointing that out!

**Comment by slundberg** [comment]
If that doesn't fix the issue let me know

**Comment by jedsd3285** [comment]
Hello! Unsure if it's because I'm using shap v. 0.35.0, but I am finding that ymin similarly does not work on dependence_plot().

I'm not smart enough to investigate if the error is similar to that identified for xmin, but at the very least, the workaround for xmin above seems to work for ymin in my case.

fyi in case not yet addressed in the latest version. :) Brilliant, brilliant idea, this SHAP thing. :) thanks so much!

![Screen Shot 2021-09-04 at 2 06 50 PM](https://user-images.githubusercontent.com/87921090/132084729-3722b5f0-ecb7-4b63-ae39-32d773a05d18.png)
![Screen Shot 2021-09-04 at 2 07 04 PM](https://user-images.githubusercontent.com/87921090/132084733-27fb5b5e-562d-42c4-b870-95328cd5baa3.png)
