### ISSUE TITLE
Questions about tree shap paper

### ISSUE THREAD

**Issue by zhengqm** [shap/shap#422]
Hi Scott, I really enjoy reading your SHAP and Tree SHAP paper. I've been trying to understand the Algorithm2 in the Tree SHAP paper, but still cannot understand how it works.

I can understand that the `RECURSE` procedure does a depth-first traversal, and in each call it passes down the proportion of "zeros" and "ones" paths reaching the node. If I get it right, when reaching a leaf node, the `sum(UNWIND(..))` part in Algorithm2 is calculating the contribution to phi_i from that leaf node. Specifically it "compress" all the weighting information (the factorial term, the term relating to proportion of paths reaching that leaf with or without feature i for all subset) of calculating expectation into m.w, but I cannot figure out how m.w achieves this.

Can you shed some light on how algorithm 2 works, especially about the intuition behind `m.w` and how&why `m.w` is updated in `EXTEND` and `UNWIND`?

Thank you!

**Comment by slundberg** [comment]
Hey! I don't think I can do this question justice here, since that part is very tricky. But we have a journal version of the work coming that might help with the details. I will mention here that one important principle is that all the features that are not on the current path will not get any credit from that leaf, so the factorial term is not the term for a model with all `M` features, but rather for a model with the number of features we have seen so far in the path. So we are increasing the term's model size every time we extend, and increasing its active set size `|S|` if we are following the branch matching the current instance. Hope that helps a bit!

**Comment by zhengqm** [comment]
Hi! Thank you for the response! Really looking forward to the journal version of the work.

**Comment by RioJack01** [comment]
Thanks for the additional detail about the algorithm, Scott.
Could you please clarify which part of code is responsible for the increase the active set size | S | ? 
Perhaps @zhengqm you understood something more about the algorithm during this time, would appreciate some details that you figured out in case.

Thanks to both in advance
