### ISSUE TITLE
Scikit-Optimize models not supported.

### ISSUE THREAD

**Issue by Bacoknight** [shap/shap#426]
I'm currently using scikit-optimize (also known as skopt) to optimise expensive functions, which uses the Random Forest regressor from scikit-learn. Though they are similar objects, I get the following error:
`Exception: Model type not yet supported by TreeExplainer: <class 'skopt.learning.forest.RandomForestRegressor'>`
This issue may be similar to #390 but since it was specifically the RandomForestRegressor used I thought it should work.

**Comment by slundberg** [comment]
If `skopt.learning.forest.RandomForestRegressor` is really the exact same as `sklearn.ensemble.forest.RandomForestRegressor` then you just need to update the check in https://github.com/slundberg/shap/blob/dc53ee14340b6614cbe44c5cfad8a0897029c141/shap/explainers/tree.py#L409-L414 to make this work. But that will require checking and making sure that both models are the same. I'll leave this here for anyone wants to send a PR on it :)

**Comment by Bacoknight** [comment]
Is there any way you'd recommend checking to make sure they are the same? I'd be happy to help out!
Judging from the snippet of code above, the skopt regressor has those attributes too.

**Comment by antoinecarme** [comment]
Hi all,

Thanks for this project.

Just got here, seems the code relies on the name of the class to detect if it is a random forest. One cannot trust the name. You can use

```
elif(isinstance(model, sklearn.ensemble.forest.RandomForestRegressor))
```

instead of : 

```
 elif str(type(model)).endswith("sklearn.ensemble.forest.RandomForestRegressor'>"):
```

the isinstance means that is a random forest or a derived class, even if its name is 'XXSFDSEAFVC'.

Hope this helps.

**Comment by slundberg** [comment]
Thanks @antoinecarme, the reason we have been doing string testing for all the model-type comparisons is because we don't want to assume that all the external packages supported by shap are installed by the user. In this case we though could change it for sklearn, since sklearn is a required dependency. I don't think that would fix this issue though.

@Bacoknight if you just duplicate the if-block for the sklearn RandomForest and change the check to skopt that should do it. You should then check that it works by explaining a model and verifying that the sum of the SHAP values + the explainer.expected_value is equal to the model output for a few predictions.

**Comment by antoinecarme** [comment]
@slundberg 

Agree, we all have our constraints. 

However python is smart enough in that anything that behaves/looks like/has the same structure than a scikit-learn module or a random forest object IS scikit-learn or a  random forest  : 

https://en.wikipedia.org/wiki/Duck_typing

Duck typing allows one to use scikit-learn with scikit-learn installed or not ... until something "seriuous" is requested from scikit-learn, and then ...

**Comment by Bacoknight** [comment]
@slundberg, I've managed to make the addition in the way you've suggested (as well as removing the "=" in the case of no variable value being given as in part a) of [this figure](https://www.nature.com/articles/s41551-018-0304-0/figures/4)) and it all seems to work fine. If I run: 

```
    for index, row in resultDataframe.iterrows():
        print(np.isclose((explainer.expected_value + np.sum(shap_values[index,:])), optimizer.models[-1].predict(np.array(row).reshape(1, -1))))
```

I get a long list of "True"s :).

I'm still trying to wrap my head around the theory of SHAP so this may be a silly question but should we be averaging the SHAP values for every row in our dataset to get the overall SHAP value for our model, or is the SHAP value only defined for a single data point?

**Comment by slundberg** [comment]
@Bacoknight great! You can combine many SHAP values to get a global measure of feature importance, but you don't want to average them (since they can be positive or negative). Instead average their absolute values over the rows like `np.abs(shap_values).mean(0)`.

@antoinecarme right. The issue here being that `elif isinstance(model, lightgbm...)` counts as "serious" and so we fail just by checking, if lightgbm is not installed. We could do `if lightgbm in sys.modules and isinstance(model, lightgbm...)`

**Comment by Bacoknight** [comment]
@slundberg Do you want me to set up a PR or should I just close this? Skopt also features GBRT, so I could add that?

**Comment by slundberg** [comment]
A PR would be great! ...and adding GBRTs is all the better. We will probably also want to leave a test in https://github.com/slundberg/shap/blob/master/tests/explainers/test_tree.py to make sure it doesn't ever break in the future.

**Comment by Bacoknight** [comment]
So after doing a bit of testing, I've noticed something that happens inconsistently: 

If I load the required data from my model for SHAP from a .pkl file, there seems to be an issue in the _cext.dense_tree_shap function. This function is called when I call explainer.shap_values(dataframe). Here's what I'm doing:

```
    model, resultDataframe, bestRow = joblib.load("shap_data.pkl")
    # Initialise SHAP.
    explainer = shap.TreeExplainer(model) # Works fine for skopt model.
    # Determine the SHAP values for every row.
    shapValues = explainer.shap_values(resultDataframe) # "Breaks" here.
    print(shapValues)
```

Sometimes (particularly after restarting the IDE) it works fine and returns a list of SHAP values. However, at other times, the IDE kills the script without any error message (which I imagine is because it crashes in the 'C' portion of the code). I haven't had this issue yet if I run the same code without having loaded the data from a .pkl file i.e when the model is created just before the SHAP analysis. There isn't much to go on since there is no crash log or anything. 

The dataframe I'm using has around 6000 data points (with 12 features), but I'm also getting this error if I try using a subset of this data.

It may also be worth noting that this issue doesn't present itself with the approximate solution option turned on.

[This may be occuring for other models so may be a separate issue altogether]

**Comment by slundberg** [comment]
@Bacoknight It could be related to #430, do you have that patch in the version you are working with?

**Comment by Bacoknight** [comment]
I do now! Seems to have worked, and the models are still acting as they should.

I'll set up a PR and add a test.
