### ISSUE TITLE
shap for stacked LSTM

### ISSUE THREAD

**Issue by galenwilkerson** [shap/shap#428]
Hi, thanks again for this tool.

Are there any issues with stacked LSTMs, or should it just work out of the box?

**Comment by slundberg** [comment]
GradientExplainer and DeepExplainer are both approximations, and I have not benchmarked them on stacked LSTMs, so keep that in mind. But that being said GradientExplainer will for sure work, and DeepExplainer should work as long as all the operations are supported (typical LSTM ones are).

**Comment by echo66** [comment]
@slundberg , when our model is a sequence model, the "order" of feature attributions matters, right? 

If yes, we need to do something similar to what it's done in game theory: evaluate the contribution for all orders?

**Comment by slundberg** [comment]
Well the ordering from Shapley values is designed to measure the importance of a member joining a group. For example if I join the group after you am I less valuable than if I were to join before you? So for sequences going into ML models we don't want to change the order of the sequence, but just mask different subsets (where those subsets are defined by an ordering of how we grow the size of the subsets).

The tricky part about sequence models is that each "feature" in the sequence is very dependent on what came before and after it. So "hiding" a word might make for a strange sentence or sequence if we don't account for the feature dependence. I have future ideas on how to handle that, but none of the current deep learning explainers handle feature dependence explicitly. I have been working on a benchmark for local interpretability methods (in the code right now), and once that gets published I plan to post results here publicly, so that might help better gauge how well we are doing for LSTMs.

**Comment by echo66** [comment]
@slundberg a benchmark for local interpretability methods? Feature importances or does it include things like anchors and local decision tree surrogates? Benchmarking interpretability methods is also something I'm kind of working into (can't say more for now). Better not go into offtopic.
