### ISSUE TITLE
Shap for CNN-RNN Architecture

### ISSUE THREAD

**Issue by jlevy44** [shap/shap#431]
Is it possible to use DeepSHAP on a video, sequence of images, and extract a saliency map for a particular image or at least across all of the images?

Input is dimensions [#samples (can remove this dimension), # images, width, height, RGB], and the final RNN output is the predicted value.

The CNN extracts the features for each image, and the RNN aggregates them, and I want to map the aggregated prediction back to this 3-4D 1 sample data structure.

**Comment by slundberg** [comment]
In theory yes, but since DeepSHAP is just an approximation I can't say how well it will do. I would also compare with GradientExplainer. These types of very deeply connected networks can sometimes cause the attribution methods to be less clear. So just keep that in mind. I have thoughts for helping on this but nothing to share yet.

**Comment by jlevy44** [comment]
Okay thanks. Keep me posted on what comes up. Really curious to learn more.
