### ISSUE TITLE
ufunc 'isnan' not supported for the input types

### ISSUE THREAD

**Issue by le01phuo** [shap/shap#432]
https://github.com/slundberg/shap/blob/bd7a457a80fd58668d4d817b29471fbb827206c5/shap/explainers/tree.py#L89

np.isnan can be applied to NumPy arrays of native dtype (such as np.float64):
In [99]: np.isnan(np.array([np.nan, 0], dtype=np.float64))
Out[99]: array([ True, False], dtype=bool)

but raises TypeError when applied to object arrays:
In [96]: np.isnan(np.array([np.nan, 0], dtype=object))
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

If we have pandas dataframe, we can use "pd.isnull" instead -- it can accept NumPy arrays of object or native dtypes:

In [97]: pd.isnull(np.array([np.nan, 0], dtype=float))
Out[97]: array([ True, False], dtype=bool)

In [98]: pd.isnull(np.array([np.nan, 0], dtype=object))
Out[98]: array([ True, False], dtype=bool)

This issue relates to the Catboost model with feature_dependence="independent", model_output="probability".

**Comment by slundberg** [comment]
Thanks. Could you provide a full example where fixing this makes it run? I don't think `feature_dependence="independent"` will run with catboost even after fixing this since that only works for models supported by the built-in code (not catboost). Having an `object` type array won't work with the built-in code (catboost can convert that to categories automatically). But perhaps fixing this would enable CatBoost to work without `feature_dependence="independent"`?

**Comment by ravi-fractal** [comment]
Hi Sludberg,

We ran a xgboost model on our data and are using TreeExplainer with 
**feature_dependence="independent", model_output="probability"**, we used shap.kmeans(train,100) and got the background data. we are getting the same error.
**ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''**
Is there a way to solve this?

Your help is much appreciated.
Thanks

**Comment by slundberg** [comment]
@ravi-fractal thanks for reporting! That's probably because `shap.kmeans` returns a custom data object designed for use with KernelExplainer, you could unwrap it using the `.data` property. But when using 100 samples for ind tree explainer I would just use 100 random samples (though I haven't compared to see if kmeans would help a bit).

I am marking this todo since TreeExplainer should be able to unwrap the output of shap.kmeans automatically.

**Comment by NancyLele** [comment]
@slundberg 
I aslo met the same problem
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

I want to know has it been resolved?

**Comment by slundberg** [comment]
Now it has :)

**Comment by ravi-fractal** [comment]
Hi slundberg,

Thanks for fixing the issue. Can you let me know which version of the shap package the fix will come with. Should I delete the present shap package and reinstall it.

Thanks in advance

**Comment by slundberg** [comment]
@ravi-fractal you will need to clone master for now. But it will also come with the next version of shap. I'll also tag a new version soon.

**Comment by ravi-fractal** [comment]
Thanks slundberg.. For now I will proceed as you suggested.

**Comment by NancyLele** [comment]
@slundberg ,i want to know when is the next version available online.

**Comment by NancyLele** [comment]
@slundberg  I use the shap version 0.29.1 ,but aslo has the problem

![B7327964-7702-11E9-9A0A-B8CA3AB540C7](https://user-images.githubusercontent.com/7942270/57771651-e0d4c500-7745-11e9-8fff-c8e8f7de60ef.png)

**Comment by atakemura** [comment]
Encountered this error today with lightGBM and pandas dataframe with categorical variables.

Temporary workaround is to change the dtype of the numpy dataframe that is associated with the pandas dataframe.
`TreeExplainer(..., data=x_tr.values.astype(np.float64))`

I think this is specific to the case where you have to supply the background data (you don't need the data if you use treepath depedent), and you have dataframe containing dtypes that doesn't play well with np.isnan but your learning algo doesn't care.

I was playing around with UCI heart dataset if anyone's interested.
```
age                                      float64
sex                                     category
chest_pain_type                         category
//snip
```

**Comment by jotsif** [comment]
Same thing as @atakemura here, category columns are not supported by `np.isnan`

**Comment by Jay-Down** [comment]
Having this issue as well: need to provide a background data set for use with explaining a CatBoost model using model_output="probability" argument, however np.isnan can't be applied to 'category' columns.

**Comment by ManuelZ** [comment]
@Jay-Down I'm having the same problem.

I want the `model_output` to be probabilities, but for that I need to put `feature_perturbation='interventional'`, but for that I need to provide data, but for that I need to not have this "ufunc 'isnan' not supported" error, but for that, according to @slundberg above, I may be out of luck with Catboost.

Is there a way to put `TreeExplainer` in probabilities mode when using Catboost? I'm thinking of moving to XGBoost because of this.

**Comment by su-park** [comment]
I want to get shap_values scaled for 'probability' and have done the above trials but to fail.

I got the same issue. "ufunc 'isnan' supported for the input types, ..."

my model is catboost binary classifier and there are bunch of categorical features.

and my shap version is 0.35.0

**Comment by maviles23** [comment]
Was this ever fix? I get the same issue for using LightGBM categoricals and shap
