### ISSUE TITLE
force_plot stacking order

### ISSUE THREAD

**Issue by david-waterworth** [shap/shap#445]
The image below shows a `shap.force_plot` for time series data with expected_value=0. Red being +ve / Blue -ve contributions. It seems to me that the stacking order is back to front, i.e. ideally in this use case at least, the -ve contributions should be stacked first so they appear below the x-axis, and the red on top. If my understanding is correct this would then produce a line at y=0 separating the +ve and -ve contributions? And more generally this would clearly partition at y=expected_value

I could be wrong and this observation may only hold for this specific data set?

![image](https://user-images.githubusercontent.com/5028974/52676187-66957880-2f7d-11e9-87c6-8991b8f49211.png)

**Comment by slundberg** [comment]
Thanks for sharing. You could do it that way, the downside is that you would no longer be able to see the output of the model as the junction between blue and red. You would have to manually estimate the subtraction between them in order to calculate the model output. If anyone wanted to add that as an option that's fine by me, but I don't think it should be the default behavior.

**Comment by david-waterworth** [comment]
I was thinking that if the stacking order was reversed the model output would be the top of the stack. But then thinking about it some more, that would only work if the red plots were on top of the blue ones which would get messy. So I think the current behaviour makes more sense.
