### ISSUE TITLE
Standalone java implementation

### ISSUE THREAD

**Issue by damienrj** [shap/shap#446]
I have been using shap and been getting good results with python, but am interested in moving towards more of a production java environment. Do you have any recommendations? Potentially use the Java version of xgboost? Also is there any difference between the built in version for xgboost compared to the standalone shap library?

**Comment by slundberg** [comment]
The built in version for xgboost should work with the java bindings, but I have never tested them since I didn’t write the java bindings. The SHAP library supports things like loss explanations that the built in method does not, but for the default settings, TreeExplainer calls the built in version for xgboost, so it should remain consistent :)

**Comment by xydrolase** [comment]
@damienrj Recently I'm also looking into using SHAP in our production JVM environment. To that end, I started a small project called [shap4j](https://github.com/xydrolase/shap4j) which provides Java wrapper of @slundberg's C++ implementation of `TreeExplainer` (https://github.com/slundberg/shap/blob/master/shap/tree_shap.h). 

I figured that by wrapping the `tree_shap.h` implementation directly, you don't have to rely on a specific tree ensemble implementation (e.g. XGBoost). The dependency is also leaner than `xgboost4j`.

Currently I've only implemented the wrapper for the exact algorithm and Saabas, but not feature interactions yet. Planning to add more features down the road.
