### ISSUE TITLE
Recommendations for filtering/grouping correlated features

### ISSUE THREAD

**Issue by jlevy44** [shap/shap#465]
Hi again.

I'm dealing with a high dimensional dataset (~400k) of high correlated features, and am working on explaining them (using gradient explainer) and making sure that I retain enough of the top features for more nuanced explanations.

What's your recommended approach for the number of features to take, and getting rid of these correlated features?

Also, would you recommend interpretations for regression that are based on both positive and negative attributions, or split the analyses into three explanation analyses, one based on pos, one neg and one based on absolute value? I'm also trying to think of the best way to extend these analyses to multi-output regression explanations.

Thanks!

**Comment by slundberg** [comment]
It seems like if you have 400k correlated features they are likely not all individually meaningful, rather groups of them are. If you can somehow create meaningful groups, then you can just sum the SHAP values within each group to get an estimate of the group's importance. Just keep in mind that large groups will likely be more important than small groups just because the model has a better chance of randomly using them (in addition to other more interesting reasons large groups might matter more). As for selecting a specific number you could always do a bootstrap and see how many groups get weights consistently above or below zero.

For your second question, I think seeing positive and negative together is helpful, but depending on the situation I could imagine breaking it apart might make sense. It really depends on who you are communicating with and what you are trying to communicate.

**Comment by jlevy44** [comment]
Is there also a p-value type approach I can use for selecting significant features?

Because I have 400k features its hard to know how many top features to inspect. What would you recommend?

**Comment by jlevy44** [comment]
Thanks for the answers!

**Comment by slundberg** [comment]
You could get P-values by putting permuted versions of the features into the model and then comparing statistics between the permuted columns and the real ones. There is also a paper that explores another approach (not written by me) at: https://arxiv.org/abs/1903.04209

**Comment by jlevy44** [comment]
Thanks! I’ll check it out.
