### ISSUE TITLE
Sub feature importance

### ISSUE THREAD

**Issue by arun-nemani** [shap/shap#505]
Is it possible to also determine the top sub features based on SHAP values.
I posted a screenshot from another user's issues. In the example below, "YearsMade" is the most importance features based on SHAP values, is it also possible to show that years 2010, 2005, and 2009 are the top three most important as well?

![image](https://user-images.githubusercontent.com/15052672/54866786-45773300-4d46-11e9-844f-2b47c6eafb6c.png)

**Comment by arun-nemani** [comment]
I wanted to bring up this issue again and see if anyone has a solution for this. Thanks for the wonderful package!

**Comment by slundberg** [comment]
Hey! Sorry it's hard to keep with with everything on here at the moment. The short answer is yes. Since the global importance of these features was computed by combining many local explanations, there is no reason you can't group these local explanations by time as will as by feature.

So for example you could take the mean absolute SHAP value of YearMade for each year independently. Hopefully that gets at what you are asking!
