### ISSUE TITLE
null's processing in XGBoost

### ISSUE THREAD

**Issue by sergun** [shap/shap#51]
Hi!

Do you know how SHAP walks in XGBoost trees during Shap values calculation? You know there is algorithm of Shap values calculation which says: in case of NULL you should follow both children and there is XGBoost NULL processing logic which says: you should go to only one more optimal child node.

Please clarify.

Sergey.

**Comment by slundberg** [comment]
Good question. There is a distinction between "missing" for the purposes of SHAP value computation and a NULL value given to XGBoost. While NULL in an XGBoost data matrix may reflect "missing" it could represent anything (such as a censored value), and is just routed down the child node that leads to the lowest loss. In SHAP value calculations "missing" means holding a feature out of a conditional expectation, so it means we don't know the value of the feature. Since we don't know the value we integrate over it, which means heading down both branches, even if the NULL value would only follow a single branch.

**Comment by sergun** [comment]
Thank you Scott! 100% matches my logic :-)

Thank you very much for your library and papers.
Frankly speaking I didn't 100% understand why SHAP approach to feature importances is better and closer to expert one than other methods..
But I like very your ideas of visualization of feature contributions, all: for single attribute, for interactions and for cluster in feature space of contributions!

**Comment by slundberg** [comment]
Great. The main idea is that if you want to allocate feature attribution values based on holding things out of your model, and you want the attribution values to sum up to the model output, then Shapley values are the only consistent way of doing that (where consistent means you don't order less important feature above a more important feature). SHAP is the combination of Shapley values and using conditional expectations to "hold things out" of the model.
