### ISSUE TITLE
TreeExplainer vs. KernelExplainer

### ISSUE THREAD

**Issue by Sebber123** [shap/shap#512]
Hi Scott,

I am comparing TreeShap and KernelShap. I understand that TreeShap is always preferred and really like the explainer. Especcially the possibility to calculate interaction effects! However, the inner workings of a model are not always available. Therefore, I am comparing the two. 

My first question is whether TreeSHAP is estimating the SHAP values or computing them exactly. In the abstract of the paper you state "fast exact tree solutions for SHAP values". However, the title of section 3.2 says "Estimating SHAP values in O(TLD2) time". In the text you talk about exact SHAP value computation again. So I am a bit confused:)

The base value of the KernelExplainer does not make sense to me. I think that is because my nsamples and/or background set sizes are too low. Is there a way, other than trial and error, to set these values to minimize computational cost by ensuring some level of accuracy of the estimation?  

Thanks in advance!

**Comment by a-reich** [comment]
Hello, I realize this is an old issue but I've encountered what I think is the same/similar question. I understand that TreeExplainer with feature_perturbation = “tree_path_dependent” is inherently different than exact or "traditional" SHAP values (NeurIPS 2017 paper), but it seems like the "interventional" method is presented as an algorithm to compute the exact values. The TreeExplainer paper has statements like "interventional Tree SHAP exactly computes the traditional Shapley value formula", and in this GH [discussion](https://github.com/christophM/interpretable-ml-book/issues/142#issuecomment-565491323) Scott stated

>there is no disagreement between
`TreeExplainer(model, prior, feature_perturbation="interventional").shap_values(X)`
vs.
`KernelExplainer(model.predict, prior).shap_values(X, nsamples=Inf)`

However, I can easily check on a toy dataset that `TreeExplainer(model, data, feature_perturbation="interventional").shap_values(X)` is giving substantially **different** values than
`shap.explainers.Exact(model.predict_proba, data)`! (or KernelSHAP with nsamples=Inf). Am I missing something, or does interventional TreeExplainer compute something that is again defined differently than original SHAP?

Thanks.

EDIT: Ok, the difference was due to confusion and some subtle behavior in the API as called out here https://github.com/slundberg/shap/issues/1991. I was using an Independent masker with no subsampling (max_samples=np.inf) for Exact, while passing the dataset directly to TreeExplainer, which implicitly creates a masker using the default max_samples = 100. Upon passing the masker directly, both explainers agree to within very small fractions.
