### ISSUE TITLE
summary_plot producing only bar plot

### ISSUE THREAD

**Issue by sathyapramod-r** [shap/shap#649]
Hi, 
summary_plot is producing only a bar plot irrespective of the plot type selected. I have more than 180 features in the plot, but I'm trying to produce summary plot only for 20 features. I have a RandomForest classifier and a Tree Explainer created. 

Is there a potential issue here?

`shap.summary_plot(shap_values_RF_test, X_test,feature_names=input_cols,plot_type='dot',auto_size_plot=True)`

![plot](https://user-images.githubusercontent.com/51961942/59694686-aa87db00-9206-11e9-8cdb-23a28811a676.jpg)

**Comment by slundberg** [comment]
That's because you are plotting a multi-class explanation. The plot type of `dot` is only possible with a single class. So you can just do `shap.summary_plot(shap_values_RF_test[0], X_test,feature_names=input_cols)` and you will get the dot summary plot for the first class.

There should be a warning in the code for this.

**Comment by sathyapramod-r** [comment]
Thank you !!
