### ISSUE TITLE
Code Contribution: summary_plot to display cumulative model decisions

### ISSUE THREAD

**Issue by floidgilbert** [shap/shap#655]
Thank you for `shap`. I've found the package and papers to be very helpful.

I have experienced a limitation with the current summary and force plots when many features contribute a small amount to an overall large change in the model score. I wrote a drop-in replacement for `shap.summary_plot` that adds `plot_type="line"`. The plot below displays typical output. It shows, from top to bottom, the cumulative change in SHAP values across features for all observations. It's similar to an upside-down dot plot with the dots connected.

Notice the three blue lines that crawl off to the left. These are the three observations for which several incremental nudges result in a very unexpected outcome in my model. This plot shows the phenomenon clearly and identifies the shortcomings in my model.

If you are interested in a code contribution, let me know. I am currently working on supporting interaction features in the same plot style. I am also considering a JS plot that will allow a user to identify the ID and feature values for each observation. This would make model diagnostics much easier. I may write up an article to that end that involves these plots.

![image](https://user-images.githubusercontent.com/20666082/59938621-c4960900-9412-11e9-8cfc-85fb0103edac.png)

**Comment by slundberg** [comment]
Very cool! I have also thought about how to best plot effects coming from many features. I was thinking more in terms of correlated groups of features, but this I think could handle that. A PR would be welcome!

A few questions/idea about the plot:
1. How are the features ordered? I think it might make sense to order them by top-to-bottom from most important to least, then flip the summing of the lines so you start at the top with the actual output for each sample. You would then be "taking away" each feature one at a time, showing the biggest changes first.
2. It looks like the color bar doubles as the x-axis, if that's correct then very nice :) ...if you flipped the plot it would then have to be on top, but that seems simple enough.
3. The labels currently line up with the dashed lines, I think it might make more sense if they lined up with the area between the dashed lines, since those features are the delta, not the final value.
4. It would be good to label the first (if flipped) dashed line as the "model output", then change the color bar to be the model output and not just the SHAP value (by adding the expected value). ...not sure about this one, but it is a thought.
5. You may want to try sorting the features by a `shap.common.hclust_ordering` on the shap_values matrix. Then just remove those features that are below your display limit. This would be an alternative to showing the most important features first. It would put features that behave similarly in this plot together and so highlight more patterns.

**Comment by floidgilbert** [comment]
Sounds good. I will get this pulled together and issue a PR. I will submit a new standalone plotting method instead of merging with `shap.summary_plot` (my original idea). Though there are style similarities, this is a different animal requiring different parameters.

1. The features are currently ordered by ascending SHAP magnitude. I will provide parameters to change the order (ascending vs. descending) and the sorting method (e.g. importance vs. hclust).
2. Yes, the color bar shares the x-axis. The observations are colored according to where they strike the x-axis.
3. Good idea.
4. Agreed. I will use a method signature similar to `shap.force_plot` so a base value and link function can be specified.
5. I will give this a try and let the user choose between feature sorting methods (importance vs. hclust vs. none vs. ...).
