### ISSUE TITLE
nonlinearity_2d_handler input dimensionality issue

### ISSUE THREAD

**Issue by eladBenedict** [shap/shap#667]
Hi,

I'm running into a problem when the gradients are computed - 
As can be seen in the image, dup0 is computed based on delta_in0, however delta_in0 and out0 have different shapes (and consequently out0 / delta_in0 and dup0 have different shapes) causing tile to fail.

Note: Computing tf.gradients without the SHAP gradient overrides works fine.

@slundberg, can you please explain the assumptions on the inputs and their dimensionality in this function? I'll gladly fix it with some guidance.

Thanks,
Elad  

![image](https://user-images.githubusercontent.com/11731485/60173126-ca2a8f00-9816-11e9-872c-3ed077c5847c.png)

**Comment by slundberg** [comment]
Interesting. The assumptions right now for this handler are that the input and output dimensions are the same and that the passed op just does some kind of non-linear transform based on both inputs (like taking the element-wise product between two tensors). It looks like one of the inputs is lower rank here.

What operation is this running on? (I can't see because it is cut-off in the image)

**Comment by eladBenedict** [comment]
@slundberg, thanks for the quick reply!
The op is "Mul". 

Yes, one of the inputs is lower rank here - IIUC it relies on broadcasting to work, which I do see that you addressed a few lines later. BTW, if you assume that the input and output have the same shape, when does such broadcasting occur?

Please let me know if you need additional information.
As mentioned, I'll gladly fix this once I figure out what's going on :)    

![image](https://user-images.githubusercontent.com/11731485/60229285-09e88980-989e-11e9-8dd7-8c209e7df486.png)
