### ISSUE TITLE
Outputs in VGG pyTorch example look essentially the same 

### ISSUE THREAD

**Issue by MaxwellRebo** [shap/shap#673]
Here: https://github.com/slundberg/shap/blob/master/notebooks/gradient_explainer/Explain%20an%20Intermediate%20Layer%20of%20VGG16%20on%20ImageNet%20(PyTorch).ipynb

The outputs look essentially the same between different classes. Is this normal/expected? What is causing them to be so similar in this example?

Thanks!

**Comment by slundberg** [comment]
I should start by noting that GradientExplainer can sometimes begin to pickup on high frequency "adversarial-style" signals for really deep conv nets, so sometimes it can be due to that. That being said, in the example you pointed at I think that is not the reason, there it is because both of the top classes were picked due to the same parts of the image. In comparison to all the rest of image-net, those two top classes are reasonably similar to each other, so you might get similar reasons they both got picked. If you want to distinguish between them then you could pass a background dataset of all mongooses, and then your explanation would be "why is this image is a meerkat and not a mongoose" instead of "why is this image a meerkat and not anything else in image net".
