### ISSUE TITLE
Switch to pytest?

### ISSUE THREAD

**Issue by jamesmyatt** [shap/shap#682]
Are you open to switching to pytest rather than nosetests?

The main advantages are:

* Better assertion errors: https://docs.pytest.org/en/latest/assert.html
* Simpler skipping tests: https://docs.pytest.org/en/latest/skipping.html
* Parametrized tests: https://docs.pytest.org/en/latest/parametrize.html

If so, then I can probably provide a PR.

**Comment by jonnor** [comment]
Hi, sorry for no response yet. This is a good idea. I am traging older issues, and see that pytest is now actually being used instead of nosetests. Ref https://github.com/slundberg/shap/blob/45b85c1837283fdaeed7440ec6365a886af4a333/.github/workflows/run_tests.yml#L33

So this issue can be closed. CC @slundberg
