### ISSUE TITLE
Range of shap_value

### ISSUE THREAD

**Issue by LividWo** [shap/shap#70]
Hi Scott,

I am trying to explain my model using SHAP recently. The result is quite convincing, thank you for such a useful tool. 
One thing that is not very clear to me is the range of 'shap_value'. Is it between -1 and 1? I took a look at Shap/explainers/kernel.py but had a hard time understand the code.

**Comment by slundberg** [comment]
Hey! The range of the SHAP values are only bounded by the output magnitude range of the model you are explaining. The SHAP values will sum up to the current output, but when there are canceling effects between features some SHAP values may have a larger magnitude than the model output for a specific instance. If you are explaining a model that outputs a probability then the range of the values will be -1 to 1, because the range of the model output is 0 to 1. If you are explaining a model that outputs a real number or log odds the SHAP values could be larger since the model outputs can be larger. Hope that helps!

**Comment by ghost** [comment]
Hi Scott,

I'm also using SHAP to explain the output of my XGBoost Model and had a few questions. I was looking at your recent "Census income classification with XGBoost" ipython notebook, and I realized that shap_values are not between 0 and 1. Nor do they sum to the model predicted value. Do you why this is happening? Or, should this be happening?

The models prediction for the first value is 0.0266 and shap_value sum for this element is -3.60.

**Comment by ghost** [comment]
I got it, shap values are log odds!

**Comment by alessiapetescia** [comment]
Hello @slundberg , when you say that "the range of the values will be -1 to 1", do you mean that more features could potentially assume values of 1 or -1 as long the overall sum corresponds to the models' output?
