### ISSUE TITLE
IndexError using CatBoost.get_feature_importance(type='ShapValues')

### ISSUE THREAD

**Issue by Ingvar-Y** [shap/shap#701]
When I try to use `shap.summary_plot()` on SHAP values generated by `CatBoost.get_feature_importance(type='ShapValues')` I get an error:
```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-90-fbb33cc74558> in <module>
----> 1 shap.summary_plot(shap_values, df_test)

~\AppData\Local\Continuum\miniconda3\envs\cyclone\lib\site-packages\shap\plots\summary.py in summary_plot(shap_values, features, feature_names, max_display, plot_type, color, axis_color, title, alpha, show, sort, color_bar, auto_size_plot, layered_violin_max_num_bins, class_names)
    158             pl.axhline(y=pos, color="#cccccc", lw=0.5, dashes=(1, 5), zorder=-1)
    159             shaps = shap_values[:, i]
--> 160             values = None if features is None else features[:, i]
    161             inds = np.arange(len(shaps))
    162             np.random.shuffle(inds)

IndexError: index 397 is out of bounds for axis 1 with size 397
```
If I replace `shap_values` by `shap_values[:,:-1]` it works properly.

I guess the problem comes from catboost but since there was a similar issue in the past #172 it would be nice to get a confirmation.

**Comment by Ingvar-Y** [comment]
@slundberg @annaveronika I checked that the problem still exists using catboost=0.16.2 and shap=0.29.3

**Comment by slundberg** [comment]
@Ingvar-Y the issue here is that when catboost (or xgboost) return a contribution matrix they include the expected_value (constant offset) as the last column. For the shap package that value is saved on the explainer object. It is really just a convenience to put it in the last column so only one chunk of memory needs to be dealt with. I think the best solution is just to document this either in CatBoost, or online here for others to find.

**Comment by slundberg** [comment]
Actually I just decided to put a warning directly in the code for this in https://github.com/slundberg/shap/commit/9cd548a41a85cff0a7d0a49862369e843ce6689f
