### ISSUE TITLE
CatBoost TreeExplainer Fails

### ISSUE THREAD

**Issue by AbhinavanT** [shap/shap#753]
Following suit with some other issues I've had in using CatBoost with the shap package, I decided to also try the `explainer` method in the library.

I have the following code to fit my classifier & use TreeExplainer:
``` 
dataset = Pool(data=X,
                     label=labels)

model = CatBoostClassifier(iterations=10,
                           learning_rate=1,
                           depth=2,
                           loss_function='MultiClass')

model.fit(dataset, plot=True)

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)
```
This is a multiclass problems (so labels has 4 different classes in it).

Bare in mind I have modified some underlying shap code in accordance to https://github.com/slundberg/shap/pull/749 just to get past the first set of errors which are described in the PR.

But the code fails at `explainer = shap.TreeExplainer(model)` with the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-56edd766efd2> in <module>
----> 1 explainer = shap.TreeExplainer(model)
      2 shap_values = explainer.shap_values(X.to_numpy())

/opt/conda/anaconda/lib/python3.6/site-packages/shap/explainers/tree.py in __init__(self, model, data, model_output, feature_dependence)
     94         self.feature_dependence = feature_dependence
     95         self.expected_value = None
---> 96         self.model = TreeEnsemble(model, self.data, self.data_missing)
     97 
     98         assert feature_dependence in feature_dependence_codes, "Invalid feature_dependence option!"

/opt/conda/anaconda/lib/python3.6/site-packages/shap/explainers/tree.py in __init__(self, model, data, data_missing)
    629             for i in range(ntrees):
    630                 l = len(self.trees[i].features)
--> 631                 self.children_left[i,:l] = self.trees[i].children_left
    632                 self.children_right[i,:l] = self.trees[i].children_right
    633                 self.children_default[i,:l] = self.trees[i].children_default

ValueError: could not broadcast input array from shape (31) into shape (19)
```

Unfortunately I don't know enough about the methods to really attempt a fix here.

Python - 3.6.8
CatBoost - 0.16.4
Shap - 0.29.3

**Comment by slundberg** [comment]
It looks like the `features` array is the not the same length as the `children_left` array. That would be an issue with the CatBoost loader code since those should be the same. However we could short this code circuit it when we are using the default internal catboost implementation of shap. The best way would be to wrap `cb_loader.get_trees` with a try catch and just make sure that fails whenever it can't handle something (as opposed to return sometime bad as it is doing right now). Then self.trees in the the TreeEnsemble object would be None and we could also use the catboost internal implementation and not any of the extra features in the core shap code.

**Comment by AbhinavanT** [comment]
@slundberg I'll have some free time this weekend, I can have a look at implementing your idea
