### ISSUE TITLE
fetch the predicted value?

### ISSUE THREAD

**Issue by perfecthost22** [shap/shap#840]
hi i wonder if we could fetch all the predicted value from shap? like in Lime by using explain_instance

**Comment by slundberg** [comment]
For a single-output model `explainer.expected_value + shap_values.sum(1)` is the output of the model since the SHAP values sum up to the model's output. However, note that for many logistic classification models this is by default the log-odds output of the model (so you would need to wrap that all in the logistic function to get the probability).
