### ISSUE TITLE
Contrasting examples

### ISSUE THREAD

**Issue by tkellogg** [shap/shap#844]
What's the best way to contrast 2 examples? For example, the user asks:

> Why did the model predict a length of stay of 13 days instead of the 7 days that it predicted for patient X with a similar diagnosis?

Do I use the predicted length of stay of patient X as the base value? Can I just retrieve SHAP values for both and find the Euclidean distance between them? Something else? Is it not possible?

**Comment by slundberg** [comment]
Let's call the current patient Y and the other patient X. The simplest way is to subtract the SHAP values of patient X from those of patient Y. This will give you the delta in the explanations.

If you are just doing this for a single pair of individuals you could also use the values for patient X as the background distribution (so a matrix with one sample), and then explain patient Y. For TreeExplainer you would pass patient X as the background data when constructing the explainer.

The first option is better if you want to contrast many samples in a comparable way since it does this indirectly by comparing their differences from a common background distribution. The second option explains the difference between the samples directly and so is more direct, but may be harder to easily compare across many samples.

**Comment by tkellogg** [comment]
Thanks!

> use the values for patient X as the background distribution (so a matrix with one sample)

What is the "background distribution"? Is it `data` parameter to `TreeExplainer`?

**Comment by slundberg** [comment]
Yep!
