### ISSUE TITLE
shap.TreeExplainer crashes with xgboost R binary when using background data

### ISSUE THREAD

**Issue by oegedijk** [shap/shap#859]
Hi all,

I am trying to load an xgboost model trained in R, and calculate shap values. (reason being I developed an interactive dashboard for displaying shap values etc  which I'd also like to make available to colleagues that still use R)

When I don't supply background data this works fine. However I would like to display probabilities and not just log odds, so I need to supply background data. However this crashes the kernel. 

```
model = xgb.XGBClassifier()
model.load_model(str(Path.cwd() / 'xgboost_R.model')) # binary saved in R with xgboost::save

X = df.drop('target', axis=1 )
y = pd.Series(np.where(df.target=='pos', 1, 0))

model.predict_proba(X)[0] # this works so model correctly loaded

shap_explainer = shap.TreeExplainer(model) # this works fine
shap_explainer = shap.TreeExplainer(model, X, model_output="probability", 
                                    feature_dependence= "independent") # this crashes the kernel
shap_explainer = shap.TreeExplainer(model, X) # also crashes the kernel

# if I refit the model everything works again:
model.fit(X, y)
shap_explainer = shap.TreeExplainer(model) , X, model_output="probability", 
                                    feature_dependence= "independent") # works fine
```

Anyone know a solution to this?

**Comment by slundberg** [comment]
The problem is with the SHAP package loading the XGBoost model. When you don't pass a background distribution then SHAP just calls the (simpler) version embedded inside the XGBoost binary, which is why it doesn't fail in that case (it doesn't need to load the model). We would need to debug why the model being loaded from R is different from one trained in Python. As a temporary fix perhaps you could load it in Python and resave the model?
