### ISSUE TITLE
Interaction plot does not work for sklearn RandomForestRegressor

### ISSUE THREAD

**Issue by resdntalien** [shap/shap#89]
I trained a random forest in sklearn and can run all the other plots out of the box on it, but I can't seem to run the interaction_shap_values. I get this error -- which is cryptic and doesn't make sense. Even if I make the datatype of X a numpy array I get a similar error. 

<img width="1118" alt="screen shot 2018-05-16 at 10 14 34 pm" src="https://user-images.githubusercontent.com/4607845/40157972-bfb7ba16-5956-11e8-83ba-594814b9c2db.png">

**Comment by slundberg** [comment]
What version of shap do you have? That error message got fixed in April to correctly state that currently interaction values are not supported for sklearn models (which I plan to fix that at some point). So it is not a dataframe issue, but you also can't get the interaction values yet unless you are using XGBoost.
