### ISSUE TITLE
depedence_plot: graph size differ

### ISSUE THREAD

**Issue by koyurion** [shap/shap#912]
When I try to omit and practise  the notebook of **dependence_plot.ipynb.** I find that the graph size is different when I set that the "interaction_index" is  same as the "ind"  but the "ind"  is set as the index and column name respetively. **When the "ind"  is set as the column name, the graph is larger.**

![2019-11-26 161454](https://user-images.githubusercontent.com/32454333/69611046-f36e7600-1067-11ea-87c6-def9cd2f00bb.png)

**Comment by koyurion** [comment]
I find this in the **dependence.py**, but I still don't understand why the graph size is set to different size.
![image](https://user-images.githubusercontent.com/32454333/69704983-91794380-112f-11ea-83a6-e54b3735321f.png)

**Comment by slundberg** [comment]
Thanks again! This is a great catch. It was because interaction_index was 0 and ind was 'CRIM'. Later they will both be converted to 0, but that hadn't happened by the time the figsize code was called (and so they look like they are not equal, and hence we reserve extra space for a color bar). I moved the figure sizing after the name conversion and now it works.
