### ISSUE TITLE
Is it Valid to Aggregate SHAP values to Sets of of Features?

### ISSUE THREAD

**Issue by john-curry871** [shap/shap#933]
SHAP values seem to be additive and e.g. the overall feature importance plot simply adds the absolute SHAP values per feature and compares them. This allows us to use SHAP for global importance aswell as local importance. We could also get feature importance for a particular subset of data records the same way.

By the same token, is it valid to get aggregate SHAP values for sets of variables? e.g. "Height", "Weight" and "Eye Colour" into "HumanDescription" or "Temperature", "Humidity" and "Air-Pressure" into "Weather"and rank them accordingly.

https://stackoverflow.com/questions/59193277/is-it-valid-to-aggregate-shap-values-to-sets-of-of-features
Sorry its more of a question than an issue.  Just reposting it here so it might catch your eye.  I think that a good answer to this will really help to clarify the valid use cases for SHAP.

**Comment by slundberg** [comment]
The short answer is **yes**, you can add up SHAP values across the columns to get the importance of a whole group of features (just make sure you don't take the absolute value like we do when going across rows for global feature importance).

The long answer is that when Shapley values "fairly" allocate credit for interaction effects between features, they assume each feature in an interaction effect should get equal credit for the interaction. This means that for high order interaction terms you might get slightly different results when running Shapley values before (and summing) vs. after grouping features (since the new group just gets one chunk of the interaction pie so to speak, as opposed to multiple chunks when it was several features). These differences are typically small though so I wouldn't sweat it much since both ways are reasonable.

**Comment by john-curry871** [comment]
That makes a lot of sense as interaction effects have already been parcelled out.  SHAP's additvity across records is already very useful and this makes it even more so.

**Comment by guilhermeparreira** [comment]
When grouping SHAP values by group features is advisable to sum the SHAP values for each feature. 
However, could I calculate a mean SHAP by group features? Here I would interpret something like that: The average importance of the group feature 'A' is X. 

I am asking this because I want to predict dropout students. 
I have 60 variables regarding grade, 10 monetary/financial and 5 regarding where he lives. 
When I add up the SHAP scores, in 98% of the cases the impact of a dropout is because of its grade (maybe because of the high number of variables regarding grade). I was thinking of this alternative to get more meaningful results.

Is it advisable?

Sorry for asking it here.
Thanks in advance.

**Comment by linzzzzzz** [comment]
I think it might be good to integrate this aggregation logic as a optional input in summary_plot function?

**Comment by MatanBendak** [comment]
Using an aggregation in your case is right (over the absolute SHAP values, as you mentioned).
The use of sum as the aggregation will cause large groups to have more importance. unlike using Mean.

The real question you are asking is a business one:
Do you want to know which group is more important? (then use mean)
Or do you wan to know which group contains the more importance features? (then use sum)

@guilhermeparreira
