### ISSUE TITLE
LSTM model with multistep forecast

### ISSUE THREAD

**Issue by jonatan-klock** [shap/shap#948]
I have an LSTM model applied for time series prediction. It is a multivariate and multi-step model. I.e I predict 2 steps into the future. I have successfully applied the repo to illustrate feature importance with one output time-step, how to apply the repo to n future time steps?

**Comment by slundberg** [comment]
In order to get the future N steps in terms of the original inputs you can either 1) build a composed model that outputs the second step using the output of the first step as an internal state (then explain that model) or 2) You could just explain each time step while allowing it to put credit on previous predicted time step values.

Hope that helps!

**Comment by jonatan-klock** [comment]
These are good suggestions. Thanks
