### ISSUE TITLE
Unable to manually calculate expected value for CatBoostClassifier

### ISSUE THREAD

**Issue by Stuart-D-King** [shap/shap#966]
I seem to be having a hard time manually calculating the base (expected) value from a fitted CatBoostClassifier object. Can someone help me understand why the below code returns two different values for the base value? The exception block is used because calling `shap.TreeExplainer(model)` returns a `    TypeError: object of type 'NoneType' has no len()` error. This is tied to case #757. Thanks for the help.
```python
# Python 3.6.8

import catboost
from catboost import CatBoostClassifier, Pool
from catboost.datasets import titanic
from sklearn.model_selection import train_test_split
import numpy as np
import shap

print(shap.__version__) # 0.33.0
print(catboost.__version__) # 0.20.1

train_df, test_df = titanic()
train_df.fillna(-999, inplace=True)
test_df.fillna(-999, inplace=True)

X = train_df.drop('Survived', axis=1)
y = train_df.Survived

categorical_features_indices = np.where(X.dtypes != np.float)[0]

X_train, X_validation, y_train, y_validation = train_test_split(X, y, train_size=0.75, random_state=42)
X_test = test_df

params = {
    'iterations': 500,
    'learning_rate': 0.1,
    'eval_metric': 'Accuracy',
    'random_seed': 42,
    'logging_level': 'Silent',
}

train_pool = Pool(X_train, y_train, cat_features=categorical_features_indices)
validate_pool = Pool(X_validation, y_validation, cat_features=categorical_features_indices)

model = CatBoostClassifier(**params)
model.fit(train_pool, eval_set=validate_pool)

print(model.predict(train_pool, prediction_type='RawFormulaVal').mean().round(4))
# -0.7318

try:
    # TypeError: object of type 'NoneType' has no len()
    explainer = shap.TreeExplainer(model)
    print(explainer.expected_value.round(4))
except:
    print('Exception!')
    shap_values = model.get_feature_importance(train_pool, type="ShapValues")
    expected_value = shap_values[:,-1][0]
    print(expected_value.round(4))
    # -0.5393
```

**Comment by slundberg** [comment]
I don't know for sure, but it would be good to ask the CatBoost team about it. It could be because of reasons similar to why there can be differences for XGBoost: https://github.com/slundberg/shap/issues/352#issuecomment-455795382

One example reason the model expected value computed internally by catboost could be different is bagging. In that case only a subset of the training samples are used to fit each tree and this can affect the coverage information recorded in the trees.

**Comment by ibuda** [comment]
Hi Stuart, this is a very interesting question. Playing with the example you provided and lurking around with Catboost documentation, I found the following solution. I am not claiming it is an intuitive one, nor that it complies with the documentation text, but you can use it as a workaround.
```
shap_values = model.get_feature_importance(train_pool, type="ShapValues")
base_shap = shap_values.sum(axis=1).mean().round(4)
base_pred = model.predict(train_pool, prediction_type='RawFormulaVal').mean().round(4)
assert base_shap == base_pred # both -0.7318
```
And it makes sense once you look into shap_values given by Catboost, specifically that:
```
predictions = model.predict(train_pool, prediction_type='RawFormulaVal')
assert sum(shap_values[0]).round(4) == predictions[0].round(4)
```
meaning that sum of all shap_values for a given sample is the prediction given by the model.
The reason why I mentioned above that it might not be intuitive above, is because in the Catboost [documentation](https://catboost.ai/docs/concepts/shap-values.html) it says that for a given object the sum of first _feature_count_ shap_values is equal to the prediction on this object. Here, however, we have to sum all shap_values (i.e. _feature_count_ + 1 values) to get the prediction on the object. 

I guess the last value (expected value) would be the prediction given that all features do not influence on model's output. That is why we have to add them all to obtain the output of the model taking into regard what it learned during fitting.

I will ask this question on Catboost github issues page, and will come back here if/once I get any clarification on the matter.

**Comment by slundberg** [comment]
Thanks @ibuda for the extra details! The first feature_count shap_values sum up to the difference between the expected_value of the model (what you would expect not knowing any of the feature's values) and current model output. What the expected_value is depends on the distribution of background sample used to compute it. Typically this is just the training data, but it seems that in CatBoost this is not quite it. The core question here is why CatBoost's internal representation does not produce and expected_value that is the same as `model.predict(train_pool, prediction_type='RawFormulaVal').mean()`.

**Comment by Stuart-D-King** [comment]
Thanks @slundberg and @ibuda. The workaround to get the expected values to tie above is helpful and insightful. 

As @slundberg mentioned, I think the outstanding question is why `explainer.expected_value` doesn't yield the same result as `model.predict(train_pool, prediction_type='RawFormulaVal').mean()`. Please let us know what CatBoost comes back to you with, or if you prefer me to raise the question on their Github issues page.

**Comment by ddofer** [comment]
Based on Catboost - the issue derives from categorical features (with missing values).
