### ISSUE TITLE
Question regarding output and documentation

### ISSUE THREAD

**Issue by andi-jo** [shap/shap#98]
Hi, great work. 

Probably trivial, but I do not really understand some basic in and outputs and wanted to ask if there is a general documentation for all classes and functions. I looked at the source code but couldn't much. Please point in any direction if there is. 

E.g. in the SVM example 

`explainer = shap.KernelExplainer(svm.predict_proba, X_train, link="logit")`  - what does `link `do and are there options?

`shap_values = explainer.shap_values(X_test, nsamples=100)`  - what does `nsamples `do and are there options? How to understand the length/shape of shap_values ?

I assume that `shap_values `are based on sampling and I thought to get a robust estimate. I see however that numerical values for entries on `shap_values ` seem to vary quite a bit only looking at one sample.

**Comment by slundberg** [comment]
Good questions. I don't have proper docs set up yet. But I just pushed doc strings that should answer your first questions. Let me know if they don't make sense.

As for the sampling variability, that depends on the number of features and the `nsamples`. How many feature were you using when you saw a lot of variability?

**Comment by andi-jo** [comment]
Thanks for the very quick reply! This already helped a lot, especially the link explanation. 

Two follow-ups if I may: 

1. Is my understanding correct that, when using `link='identity'`, the shap values can be interpreted as feature attributes from a linear regression model, otherwise log-odds ratios?

2. Regarding sample variability, I think I misunderstood the shap_values output. In the Iris-kNNexample, how is the output to be interpreted from 

`shap_values = shap.KernelExplainer(knn.predict_proba, X_train).shap_values(X_test.iloc[0,:])` ?

It's a list of length-3 with a length-5 array in each element. My guess would be that this relates to the three target classes (if yes, why?) and length-5 because 4 features + constant? I.e. the linear attribution values are always to be found in the `n-1` first entries if `n `is the number of features. 

I have 10 features, how many samples should I take? Is there relation to size/type of the model or the size of the training data set?

**Comment by slundberg** [comment]
Good questions.

1. Yes. If you were explaining a linear model with coefficients beta on a sample x then the SHAP value for each feature i would be beta_i * (x_i - E[x_i]) and the base rate constant at the end would be E[beta @ x].
2. Yes, the three lists each explain the 3 outputs of the model for the three classes. Since SHAP values quantify the impact of features on an output you will get a different SHAP value for a feature for each output of the model. The last (5th) element is a constant base rate of the model.

If you have 10 features then using more than 2^10 = 1024 samples will give no sampling variability. And if you provide a single reference background value to `KernelExplainer` (like `X.mean(0).reshape(1, X.shape[1])`) then this will result in about 1024 evaluations of the underlying model.

If you have 20 features I would recommend perhaps a few hundred samples per feature? But it really depends, if you have very sparse feature impacts then the `l1_reg` option can select them with many fewer samples.

If you can't afford more samples you could always turn up the `l1_reg` until you get enough run-to-run stability, knowing you are forcing more sparsity than truly exists.

Hope that helps!

**Comment by andi-jo** [comment]
Thanks again, this is very helpful. I did not understand one part of your reply. What does it mean to "provide a single reference background value to `KernelExplainer` (like `X.mean(0).reshape(1, X.shape[1])`) "?

**Comment by slundberg** [comment]
Kernel SHAP uses a background set of inputs to approximate the effect of
not knowing a feature's value. If you use just one input then this is like
a reference value that represents missing (hence passing the mean of the
features as the reference). For each sample all the reference set values
get evaluated, hence why if you have one reference sample you get the same
number of original model evaluations during an explanation as nsamples. If
you have 5 background samples passed to the KernelExplainer constructor
then you would get 5 * nsamples evaluations of the original model.

**Comment by andi-jo** [comment]
I think I got it. Thanks again for the quick replies and detailed explanations. Looking forward to explore more. Your work is really plugging a big gap for making machine learning models useful to applications where one needs more than just precise predictions but explanations.
