### ISSUE TITLE
Corrected sum of SHAP values 

### ISSUE THREAD

**Issue by bgreenwell** [shap/shap#998]
@slundberg I’m curious about the approach used to correct the sum of the SHAP values on lines 140-151 in sampling.py. Just curious as to why this particular approach was used as opposed to a simple rescaling? Thanks in advance 🙏.

**Comment by bgreenwell** [comment]
Is it fair to say that this approach provides more adjustment to the SHAP values with larger estimated variance?

**Comment by slundberg** [comment]
That's right. It just ridge regression where the variables with higher variance in their estimates are allowed to move more than those with low variance. (where we are moving them to enforce that they sum to model output like we know they should with an infinite number of samples).

**Comment by bgreenwell** [comment]
Excellent, thank you!

**Comment by NOEPG** [comment]
Hello @slundberg and @bgreenwell ,

I am curious to understand the maths behind this adjustment of the Shapley values to make them sum to the prediction.
First, unless I am misleading, I don't think a scaling would work since we could have a sum of the estimated Shapley values equal to zero.

I understand the motivation behind penalizing the adjustments (additive adjustment according to the code) with respect to the variance. However, I don't get the maths. 

Let's say that we have an error $s$ which is the difference between what the sum of shapley values should actually be, i.e. $\sum_i \phi_i$ (which is the actual prediction minus the expected predition), and the sum of estimated shapley values $\sum_i \hat{\phi}_i$.
(all sums are indexed over the set of features)

My first reflex would be, first without any penalty, to find all the adjustment $a_i$ such that $\sum_i \left( \phi_i - (\hat{\phi}_i - a_i) \right) =s-\sum_i a_i = 0$ but this of course has an infinite number of solutions...
I don't see how adding a penalty for each $a_i$ would change anything. I will still have an infinite number of solutions.

So there must be something I don't understand... What do you mean by ``a ridge regression with one sample of all ones with sum_error[i] as the label and 1/v as the ridge penalties.''?

I would be very grateful if you could help me with some maths clarifications.

Thank you :)

**Comment by NOEPG** [comment]
I understand that `(v - (v * v.sum()) / (1 + v.sum()))` is a distribution (when the `E` in `v = (phi_var[:,i] / phi_var[:,i].max()) * E ` goes to infinity)
This distribution is weighting the error with a high weight when the variance is large and a small one when the variance is low.
The formula really makes sense.
But I don't get how it is related to ridge regression.
